import gzip,hashlib,json,pathlib,shutil
b=pathlib.Path(__file__).parent;r=pathlib.Path('/private/tmp/mpk-w09-refreeze-consumer-continuation');out=b/'standalone-checkpoint-evidence';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
checks=[('program-alias-name-graphs',93),('program-alias-name-graphs-2',93),('program-alias-dual-checkers',186),('control-execution-name-graphs',12),('control-execution-dual-checkers',24),('control-pattern-scope-name-graphs',7),('control-pattern-scope-dual-checkers',14)]
for folder,count in checks:
 s=json.loads((b/folder/'status.json').read_bytes());assert s['status'].startswith('passed_all_') and len(s['stages'])==count and all(x['exit_code']==0 for x in s['stages'])
 if folder.startswith('program-alias-'):continue
 for p in sorted((b/folder).rglob('*')):
  if p.is_file() and p.suffix!='.mpcert':dst=out/folder/p.relative_to(b/folder);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dst)
first=json.loads((b/'standalone-promoted-pin-checks/status.json').read_bytes());last=json.loads((b/'standalone-promoted-pin-checks-3/status.json').read_bytes());assert first['status']=='failed';passed=[s for s in first['stages'] if s['exit_code']==0];assert len(passed)==12;assert last['status'].startswith('passed_both_') and len(last['stages'])==2 and all(s['exit_code']==0 for s in last['stages'])
for folder in ['standalone-promoted-pin-checks','standalone-promoted-pin-checks-2','standalone-promoted-pin-checks-3','json-products-exact-serialization-repair','test-predecessor-input-path-review','ordinary-regeneration-11','ordinary-regeneration-12']:
 for p in sorted((b/folder).rglob('*')):
  if not p.is_file() or 'goldens' in p.relative_to(b/folder).parts:continue
  dst=out/folder/p.relative_to(b/folder);dst.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(p,dst)
for n in ['execution-scope-promotion.json','prepare-execution-scope-promotion.py','execution-scope-promotion-plan.log.txt','completed-ordinary-owner-stages-10-with-execution-sequent-names.json','completed-ordinary-owner-stages-11-with-pattern-scope-names.json','control-execution-sequent-name-rebinding-audit.json','control-pattern-sequent-name-rebinding-audit.json','control-pattern-scope-name-rebinding-audit.json','context-name-rebindings-7.json','context-name-rebindings-8.json','context-name-rebindings-9.json','derive-control-pattern-scope-name-rebindings.py','derive-control-pattern-sequent-name-rebindings.py','derive-control-execution-sequent-name-rebindings.py','run-control-execution-name-graphs.py','run-control-execution-dual-checkers.py','run-control-pattern-scope-name-graphs.py','run-control-pattern-scope-dual-checkers.py','run-standalone-promoted-pins.py','run-standalone-promoted-pins-2.py','run-standalone-promoted-pins-3.py','run-ordinary-regeneration-11.py','run-ordinary-regeneration-12.py','ordinary-source-manifest-11.json','ordinary-source-manifest-12.json','finalize-standalone-execution-checkpoint.py']:
 assert (b/n).is_file(),n;shutil.copy2(b/n,out/n)
failed=b/'completed-ordinary-owner-stages-11-with-pattern-sequent-names.json';raw=failed.read_bytes();archive=out/'pattern-scope-initial-metadata-comparison.json.gz';archive.write_bytes(gzip.compress(raw,mtime=0));assert gzip.decompress(archive.read_bytes())==raw
(out/'pattern-scope-initial-metadata-comparison-archive.json').write_text(json.dumps({'original_raw_sha256':hashlib.sha256(raw).hexdigest(),'archive_sha256':h(archive),'original_bytes':len(raw),'real_status':'failed_completed_stage_lineage','lossless':True},sort_keys=True,indent=2)+'\n')
composed={}
for name in ['standalone-program-promotion.json','slot-boundary-promotion.json','standalone-document-alias-promotion.json','execution-scope-promotion.json']:
 d=json.loads((b/name).read_bytes())
 for row in d['changes']:
  item=dict(row);item['raw_sha256']=row.get('raw_sha256',row.get('sha256'));assert item['raw_sha256'];composed[row['path']]=item
repair=json.loads((b/'json-products-exact-serialization-repair/receipt.json').read_bytes());path='develop/migrations/csharp-03/ordinary-foundation/json-products/certificates.json';assert h(r/path)==repair['actual_owner_expected_raw_sha256'];composed[path]['raw_sha256']=repair['actual_owner_expected_raw_sha256'];composed[path]['exact_serialization_repair']='json-products-exact-serialization-repair/receipt.json'
for path,row in composed.items():assert h(r/path)==row['raw_sha256'],path
receipt={'schema':'mpk.csharp_practical.t01_w09.standalone_and_execution_checkpoint.v1','status':'passed_promoted_actual_program_lineage_selected_owner_pins_exact_graphs_and_both_checkers','selection_reason':'Only the 178 still-current standalone program aliases, two completed original execution/scope owners, and affected control-slot/structural-boundary metadata are promoted. Candidate branches retain full pin/import/mutation checks while avoiding unchanged scalar native-value matrices; contract scopes, source clauses, JSON product and calendar consumers are selected because their names or aggregate metadata change. Original eighteen-source scope/capture owners validate the optional predecessor paths; the source-body review proves every other test byte unchanged. Whole gates remain final T01-W10/T06-W12.','actual_standalone_programs_generated':198,'standalone_current_program_occurrences':178,'standalone_changed_certificate_graph_pairs':93,'standalone_checker_acceptance_stages':186,'standalone_selected_owner_pins_passed':14,'standalone_pin_failures_retained':[{'run':'standalone-promoted-pin-checks','exit_code':101,'reason':'missing three approved-freeze document hex aliases'},{'run':'standalone-promoted-pin-checks-2','exit_code':101,'reason':'one final newline in otherwise identical complete aggregate metadata'}],'slot_and_structural_boundary_certificate_sets':13,'slot_and_structural_boundary_original_bytes_preserved':13,'execution_and_scope_source_owner_corpora':2,'execution_and_scope_certificate_sets':36,'execution_and_scope_original_byte_retentions':6,'execution_and_scope_distinct_changed_graph_pairs':19,'execution_and_scope_fresh_checker_acceptance_stages':38,'scope_exact_original_fresh_pair_reuses':11,'two_test_input_paths_original_bodies_preserved':True,'selected_vc_test_clippy_checks':2,'format_check':'passed','unresolved':'Capture certificate acceptance, three remaining pattern consumers, whole JSON wrapper dual acceptance, relation metrics and all original application proof assembly remain pending. No W09/W10 completion or practical-profile activation is claimed.','application_proof_ids_pending':987,'full_t01_gate':'deferred_to_final_W10','full_t06_gate':'deferred_to_W12','changes':list(composed.values())};(out/'receipt.json').write_text(json.dumps(receipt,sort_keys=True,indent=2)+'\n')
manifest={str(p.relative_to(out)):h(p) for p in sorted(out.rglob('*')) if p.is_file() and p.name!='file-manifest.json'};(out/'file-manifest.json').write_text(json.dumps({'schema':'mpk.evidence_file_manifest.v1','files':manifest},sort_keys=True,indent=2)+'\n');print('verified evidence files',len(manifest),'promoted paths',len(composed),'evidence bytes',sum(p.stat().st_size for p in out.rglob('*') if p.is_file()))
