import hashlib,json,pathlib,shutil
b=pathlib.Path(__file__).parent;r=pathlib.Path('/private/tmp/mpk-w09-refreeze-consumer-continuation');oldroot=pathlib.Path('/private/tmp/mpk-w09-refreeze-metadata-integration');out=b/'execution-scope-promotion-plan';out.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();checks={}
for folder,count in [('control-execution-name-graphs',12),('control-execution-dual-checkers',24),('control-pattern-scope-name-graphs',7),('control-pattern-scope-dual-checkers',14)]:
 s=json.loads((b/folder/'status.json').read_bytes());assert s['status'].startswith('passed_all_') and len(s['stages'])==count and all(x['exit_code']==0 for x in s['stages']);checks[folder]=s
lineages=[('10','completed-ordinary-owner-stages-10-with-execution-sequent-names.json'),('11','completed-ordinary-owner-stages-11-with-pattern-scope-names.json')];changes=[];owners=[]
for number,receipt_name in lineages:
 receipt=json.loads((b/receipt_name).read_bytes());assert not receipt['failures'] and receipt['completed_owner_stages']==1;owner=receipt['files'][0]['family'];owners.append(owner)
 for row in receipt['files']:
  relative='develop/migrations/csharp-03/ordinary-foundation/'+row['family']+'/'+row['generated_path'];old_relative='develop/migrations/csharp-03/ordinary-foundation/'+row['family']+'/'+row['original_path'];fresh=b/f'ordinary-regeneration-{number}/goldens'/row['family']/row['generated_path'];old=r/old_relative;assert h(fresh)==row['generated_raw_sha256'] and h(old)==row['original_raw_sha256'];assert old.read_bytes()==(oldroot/old_relative).read_bytes()
  if fresh.suffix=='.json':assert row['semantic_metadata_preserved']
  target=out/'files'/relative;target.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(fresh,target);changes.append({'path':relative,'before_raw_sha256':h(old),'raw_sha256':h(fresh),'kind':'metadata' if fresh.suffix=='.json' else 'certificate','certificate_bytes_preserved':row.get('certificate_bytes_preserved')})
map7=json.loads((b/'context-name-rebindings-7.json').read_bytes());map9=json.loads((b/'context-name-rebindings-9.json').read_bytes());extra={k:v for k,v in map9.items() if map7.get(k)!=v};reused=[]
for row in json.loads((b/'control-pattern-scope-changed-certificates.json').read_bytes())['cases']:
 parent=row['same_complete_graph_pair_as_execution']
 if parent is None:continue
 graph=next(x for x in checks['control-execution-name-graphs']['stages'] if x['label']==parent);assert (graph['original_raw_sha256'],graph['generated_raw_sha256'])==(row['original_raw_sha256'],row['generated_raw_sha256']);raw=bytes.fromhex(pathlib.Path(row['original_path']).read_text());assert not any(k.encode() in raw for k in extra)
 dual=[x for x in checks['control-execution-dual-checkers']['stages'] if x['case']==parent];assert {x['backend'] for x in dual}=={'rust','go'} and all(x['exit_code']==0 and x['verdict']=='accepted' for x in dual)
 for x in dual:assert x['input_sha256']==hashlib.sha256(bytes.fromhex(pathlib.Path(row['generated_path']).read_text())).hexdigest()
 reused.append({'scope':row['label'],'execution_case':parent,'same_original_and_fresh_certificates':True,'additional_scope_name_mapping_absent_from_complete_old_certificate':True,'graph_sha256':graph['graph_sha256'],'checker_inputs':{x['backend']:x['input_sha256'] for x in dual}})
assert len(reused)==11
receipt={'status':'reviewable_two_completed_source_owners_exact_metadata_graphs_and_both_checkers','source_owner_corpora':owners,'certificate_sets':36,'exact_original_byte_retentions':6,'distinct_changed_certificate_pairs':19,'complete_graph_checks':19,'fresh_checker_acceptance_stages':38,'reused_scope_pairs':reused,'changes':changes,'selection_reason':'Promote only the completed execution and pattern-scope source outputs after complete metadata lineage, complete definition graph comparison and matching Rust/Go acceptance with zero axioms. Eleven scope cases reuse both reports only because the entire old/fresh byte pair is identical to the execution pair and every additional scope name mapping is absent from the old certificate. Default test paths and all source/value/import/mutation checks stay unchanged. Other consumers and all application proofs remain pending.','application_proof_ids_pending':987,'full_t01_gate':'deferred_to_final_W10','full_t06_gate':'deferred_to_W12'};(out/'plan.json').write_text(json.dumps(receipt,sort_keys=True,indent=2)+'\n');print('reviewable changes',len(changes),'reused complete pairs',len(reused))
