use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use mpk_vc::semantic_profile_registry::{
    validate_semantic_profile_registry, RegistryRevision, ValidatedSemanticProfileRegistry,
};
use mpk_vc::successor_source_artifacts::{
    import_successor_source_manifest_json, import_successor_source_map_json,
    import_successor_vir_json, successor_contract_hash_value, successor_source_manifest_hash_value,
    successor_source_map_hash_value, successor_vir_hash_value, SuccessorSourceManifestStage,
    SuccessorSourceManifestValidationContext, SuccessorSourceMapValidationContext,
};
use mpk_vc::successor_vc::{
    emit_successor_vc_skeleton, generate_successor_vc, import_successor_vc_json,
    import_successor_vc_skeleton_json, SuccessorVcSource, SUCCESSOR_VC_HASH_DOMAIN,
    SUCCESSOR_VC_SCHEMA, SUCCESSOR_VC_SKELETON_SCHEMA,
};
use mpk_vc::{
    canonical_json_bytes, hash_domain_separated_raw, input_set_hash, parse_strict_json,
    sha256_raw_file_bytes, CapturedInput, InputEntry, InputKind, ReleaseRegistryIdentity,
    SafetyEvidenceRoute, StrictJsonLimits, VcCertificateSkeletonV1, VcDocument, VcGroupKind,
    VcTerm, VirSafetyCheck,
};
use serde_json::{json, Value};

const ZERO_SHA256: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";
const CSHARP_SOURCE: &[u8] = b"namespace Vector; public static class RequiredChecks { public static int Identity(int x) => x; public static int Run(int x, int y, uint ux, uint uy, bool choose) => choose ? Identity(x) : x; }\n";
const CSHARP_CALLEE_CONTRACT: &[u8] = b"{\"schema\":\"mpk.csharp.contract.v0\",\"semantic_profile\":\"mpk.csharp.scalar.v0\",\"method\":\"Vector.RequiredChecks::Identity(i32)->i32\",\"requires\":[],\"ensures\":[{\"lhs\":{\"result\":0},\"op\":\"eq\",\"rhs\":{\"parameter\":\"x\"}}],\"modifies\":[],\"abrupt_completion\":\"forbidden\",\"termination\":\"total\"}\n";
const CSHARP_CONTRACT: &[u8] = b"{\"schema\":\"mpk.csharp.contract.v0\",\"semantic_profile\":\"mpk.csharp.scalar.v0\",\"method\":\"Vector.RequiredChecks::Run(i32,i32,u32,u32,bool)->i32\",\"requires\":[],\"ensures\":[{\"bool\":true}],\"modifies\":[],\"abrupt_completion\":\"forbidden\",\"termination\":\"total\"}\n";
const CSHARP_CALLEE_FUNCTION: &str = "Vector.RequiredChecks::Identity(i32)->i32";
const CSHARP_FUNCTION: &str = "Vector.RequiredChecks::Run(i32,i32,u32,u32,bool)->i32";

struct OwnedCapturedInput {
    kind: InputKind,
    normalized_path: String,
    bytes: Vec<u8>,
}

struct ValidatedSource {
    vir: mpk_vc::successor_source_artifacts::ValidatedSuccessorVir,
    manifest: mpk_vc::successor_source_artifacts::ValidatedSuccessorSourceManifest,
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    fs::read(repository_root().join(relative.as_ref()))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.as_ref().display()))
}

fn load(relative: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&read(relative)).expect("checked-in JSON")
}

fn canonical(value: &Value) -> Vec<u8> {
    let encoded = serde_json::to_vec(value).expect("JSON serializes");
    let strict = parse_strict_json(
        &encoded,
        StrictJsonLimits::new(268_435_456, 268_435_456, 768, 1_048_576),
    )
    .expect("strict JSON");
    canonical_json_bytes(&strict).expect("canonical JSON")
}

fn registry() -> ValidatedSemanticProfileRegistry {
    validate_semantic_profile_registry(
        &read("release/bundles/semantic-profile-registry.json"),
        RegistryRevision::Revision3,
    )
    .expect("revision-3 semantic registry")
}

fn profile_contract(profile: &str) -> Value {
    match profile {
        "go" => json!({
            "profile_entry_sha256": "b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id": "mpk.profile.vc.go_fixed.v0",
            "value": {
                "contract_profile_id": "mpk.go.contract.v0",
                "required_check_profile_id": "mpk.go.fixed.v0",
                "verification_limit_profile_id": "mpk.verify.limits.v0"
            }
        }),
        "rust" => json!({
            "profile_entry_sha256": "1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id": "mpk.profile.vc.rust_checked.v0",
            "value": {
                "contract_profile_id": "mpk.rust.contract.v0",
                "required_check_profile_id": "mpk.rust.checked.v0",
                "verification_limit_profile_id": "mpk.verify.limits.v0"
            }
        }),
        "csharp" => load("develop/specs/vectors/csharp-profile-v0.json")["profile_contracts"]
            .as_array()
            .expect("C# profile contracts")
            .iter()
            .find(|contract| contract["field"] == "vc")
            .expect("C# VC profile contract")["envelope"]
            .clone(),
        other => panic!("unknown test profile {other}"),
    }
}

fn input_kind(value: &Value) -> InputKind {
    match value.as_str().expect("input kind") {
        "source" => InputKind::Source,
        "contract" => InputKind::Contract,
        "build_manifest" => InputKind::BuildManifest,
        "lockfile" => InputKind::Lockfile,
        other => panic!("unknown input kind {other}"),
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = input_kind(&entry["kind"]);
            let normalized_path = entry["normalized_path"]
                .as_str()
                .expect("normalized input path")
                .to_owned();
            let path = repository_root().join(source_root).join(&normalized_path);
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match kind {
                    InputKind::BuildManifest if normalized_path == "Cargo.toml" => {
                        GENERATED_CARGO_TOML.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "Cargo.lock" => {
                        GENERATED_CARGO_LOCK.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "go.sum" => Vec::new(),
                    _ => panic!("read captured input {}: {error}", path.display()),
                },
                Err(error) => panic!("read captured input {}: {error}", path.display()),
            };
            assert_eq!(entry["size_bytes"], bytes.len() as u64);
            assert_eq!(entry["sha256"], sha256_raw_file_bytes(&bytes).to_hex());
            OwnedCapturedInput {
                kind,
                normalized_path,
                bytes,
            }
        })
        .collect()
}

fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.normalized_path,
            bytes: &input.bytes,
        })
        .collect()
}

fn staged_source(
    registry: &ValidatedSemanticProfileRegistry,
    root: &str,
    source_root: &str,
) -> ValidatedSource {
    let vir_bytes = read(format!("{root}/vir.json"));
    let map_bytes = read(format!("{root}/source-map.json"));
    let manifest_bytes = read(format!("{root}/source-manifest.frontend.json"));
    let manifest_value: Value = serde_json::from_slice(&manifest_bytes).expect("manifest JSON");
    let storage = captured_storage(source_root, &manifest_value);
    let captured = captured_refs(&storage);
    let vir = import_successor_vir_json(&vir_bytes, registry).expect("successor VIR");
    let map = import_successor_source_map_json(
        &map_bytes,
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("successor source map");
    let release_registry = serde_json::from_value::<ReleaseRegistryIdentity>(
        manifest_value["release_registry"].clone(),
    )
    .expect("release-registry identity");
    let manifest = import_successor_source_manifest_json(
        &manifest_bytes,
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("successor source manifest");
    ValidatedSource { vir, manifest }
}

fn csharp_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let context =
        load("release/bundles/candidates/csharp.json")["tuples"][0]["semantic_context"].clone();
    let bool_type = json!({"kind":"bool"});
    let i32_type = json!({"kind":"bv","width":32,"signed":true});
    let u32_type = json!({"kind":"bv","width":32,"signed":false});
    let mut callee_contract = json!({
        "semantic_context": context.clone(),
        "unit_id": "payment-policy",
        "function_id": CSHARP_CALLEE_FUNCTION,
        "requires": [],
        "ensures": [{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies": [],
        "panic": "forbidden",
        "termination": "total",
        "loops": [],
        "contract_hash": ZERO_SHA256
    });
    callee_contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&callee_contract)
            .expect("C# callee contract hash")
            .as_str()
            .to_owned(),
    );
    let variable = |name: &str| json!({"var":name});
    let overflow =
        |operation: &str| json!({"kind":"integer_no_overflow","operation":operation,"signed":true});
    let binary = |id: &str, op: &str, lhs: Value, rhs: Value, ty: Value, checks: Vec<Value>| {
        json!({
            "id": id,
            "kind": "BinOp",
            "lhs": lhs,
            "op": op,
            "rhs": rhs,
            "safety_checks": checks,
            "type": ty
        })
    };
    let mut instructions = vec![
        binary(
            "t1",
            "bv_add",
            variable("p0"),
            variable("arg1"),
            i32_type.clone(),
            vec![overflow("add")],
        ),
        binary(
            "t2",
            "bv_sub",
            variable("t1"),
            variable("arg1"),
            i32_type.clone(),
            vec![overflow("sub")],
        ),
        binary(
            "t3",
            "bv_mul",
            variable("t2"),
            variable("arg1"),
            i32_type.clone(),
            vec![overflow("mul")],
        ),
        json!({
            "id":"t4",
            "kind":"UnaryOp",
            "op":"bv_neg",
            "safety_checks":[overflow("neg")],
            "type":i32_type.clone(),
            "value":variable("t3")
        }),
        binary(
            "t5",
            "bv_sdiv",
            variable("t4"),
            variable("arg1"),
            i32_type.clone(),
            vec![
                json!({"kind":"divisor_nonzero"}),
                json!({"kind":"signed_divrem_representable","operation":"div"}),
            ],
        ),
        binary(
            "t6",
            "bv_srem",
            variable("t4"),
            variable("arg1"),
            i32_type.clone(),
            vec![
                json!({"kind":"divisor_nonzero"}),
                json!({"kind":"signed_divrem_representable","operation":"rem"}),
            ],
        ),
        binary(
            "t7",
            "bv_udiv",
            variable("arg2"),
            variable("arg3"),
            u32_type.clone(),
            vec![json!({"kind":"divisor_nonzero"})],
        ),
        binary(
            "t8",
            "bv_urem",
            variable("arg2"),
            variable("arg3"),
            u32_type,
            vec![json!({"kind":"divisor_nonzero"})],
        ),
        binary(
            "t9",
            "bv_add",
            variable("t5"),
            variable("t6"),
            i32_type.clone(),
            vec![],
        ),
    ];
    instructions.push(json!({
        "id":"t10",
        "kind":"CallStatic",
        "type":i32_type.clone(),
        "function":CSHARP_CALLEE_FUNCTION,
        "contract_hash":callee_contract["contract_hash"],
        "args":[variable("t9")],
        "safety_checks":[]
    }));
    let mut contract = json!({
        "semantic_context": context,
        "unit_id": "payment-policy",
        "function_id": CSHARP_FUNCTION,
        "requires": [],
        "ensures": [{"lhs":{"result":0},"op":"eq","rhs":{"result":0}}],
        "modifies": [],
        "panic": "forbidden",
        "termination": "total",
        "loops": [],
        "contract_hash": ZERO_SHA256
    });
    contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&contract)
            .expect("C# contract hash")
            .as_str()
            .to_owned(),
    );
    let mut vir = json!({
        "schema": "mpk.vir.v1",
        "semantic_context": contract["semantic_context"].clone(),
        "units": [{
            "id":"payment-policy",
            "name":"payment-policy",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":CSHARP_CALLEE_FUNCTION,
                "unit_id":"payment-policy",
                "name":"Identity",
                "params":[{"id":"arg0","type":i32_type.clone()}],
                "results":[{"id":"result0","type":i32_type.clone()}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":callee_contract,
                "features_used":[]
            },{
                "id":CSHARP_FUNCTION,
                "unit_id":"payment-policy",
                "name":"Run",
                "params":[
                    {"id":"arg0","type":i32_type.clone()},
                    {"id":"arg1","type":i32_type.clone()},
                    {"id":"arg2","type":{"kind":"bv","width":32,"signed":false}},
                    {"id":"arg3","type":{"kind":"bv","width":32,"signed":false}},
                    {"id":"arg4","type":bool_type}
                ],
                "results":[{"id":"result0","type":i32_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{
                        "kind":"Branch",
                        "cond":{"var":"arg4"},
                        "then_label":"bb2",
                        "then_args":[],
                        "else_label":"bb1",
                        "else_args":[]
                    }
                },{
                    "label":"bb1",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Jump","label":"bb3","args":[{"var":"arg0"}]}
                },{
                    "label":"bb2",
                    "parameters":[],
                    "instructions":[{
                        "id":"t0",
                        "kind":"CallStatic",
                        "type":i32_type.clone(),
                        "function":CSHARP_CALLEE_FUNCTION,
                        "contract_hash":callee_contract["contract_hash"],
                        "args":[{"var":"arg0"}],
                        "safety_checks":[]
                    }],
                    "terminator":{"kind":"Jump","label":"bb3","args":[{"var":"t0"}]}
                },{
                    "label":"bb3",
                    "parameters":[{"id":"p0","type":i32_type.clone()}],
                    "instructions":instructions,
                    "terminator":{"kind":"Return","values":[{"var":"t10"}]}
                }],
                "contracts":contract,
                "features_used":["branch","call_static"]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir["vir_hash"] = Value::String(
        successor_vir_hash_value(&vir)
            .expect("C# VIR hash")
            .as_str()
            .to_owned(),
    );
    let vir = import_successor_vir_json(&canonical(&vir), registry).expect("C# successor VIR");

    let captured_storage = [
        OwnedCapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/identity.json".to_owned(),
            bytes: CSHARP_CALLEE_CONTRACT.to_vec(),
        },
        OwnedCapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/required.json".to_owned(),
            bytes: CSHARP_CONTRACT.to_vec(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Required.cs".to_owned(),
            bytes: CSHARP_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&captured_storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"src/Required.cs",
            "start":0,
            "end":CSHARP_SOURCE.len()
        })
    };
    let mut entries = vec![
        json!({
            "reference":{"kind":"function","unit_id":"payment-policy","function_id":CSHARP_CALLEE_FUNCTION},
            "origin":origin()
        }),
        json!({
            "reference":{
                "kind":"terminator",
                "unit_id":"payment-policy",
                "function_id":CSHARP_CALLEE_FUNCTION,
                "block":"bb0"
            },
            "origin":origin()
        }),
        json!({
            "reference":{"kind":"function","unit_id":"payment-policy","function_id":CSHARP_FUNCTION},
            "origin":origin()
        }),
        json!({
            "reference":{
                "kind":"instruction",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":"bb2",
                "instruction":"t0"
            },
            "origin":origin()
        }),
    ];
    for index in 1..=10 {
        entries.push(json!({
            "reference":{
                "kind":"instruction",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":"bb3",
                "instruction":format!("t{index}")
            },
            "origin":origin()
        }));
    }
    for index in 0..=3 {
        entries.push(json!({
            "reference":{
                "kind":"terminator",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":format!("bb{index}")
            },
            "origin":origin()
        }));
    }
    let mut source_map = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":entries,
        "source_map_hash":ZERO_SHA256
    });
    source_map["source_map_hash"] = Value::String(
        successor_source_map_hash_value(&source_map)
            .expect("C# source-map hash")
            .as_str()
            .to_owned(),
    );
    let source_map = import_successor_source_map_json(
        &canonical(&source_map),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("C# successor source map");

    let inputs = captured_storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release_registry_value = load("release/bundles/bundle-registry.json");
    let release_registry = ReleaseRegistryIdentity {
        schema: release_registry_value["schema"]
            .as_str()
            .expect("release schema")
            .to_owned(),
        id: release_registry_value["id"]
            .as_str()
            .expect("release ID")
            .to_owned(),
        registry_sha256: release_registry_value["registry_sha256"]
            .as_str()
            .expect("release hash")
            .to_owned(),
    };
    let mut manifest = json!({
        "schema":"mpk.source_manifest.v1",
        "semantic_context":vir.module().semantic_context(),
        "selection":{
            "schema":"mpk.selection.csharp_methods.v0",
            "value":{
                "compilation":"payment-policy",
                "contracts":["contracts/identity.json","contracts/required.json"],
                "methods":[CSHARP_CALLEE_FUNCTION,CSHARP_FUNCTION],
                "sources":["src/Required.cs"]
            }
        },
        "limit_profile":"mpk.vir.limits.v0",
        "release_registry":release_registry,
        "toolchain":{
            "bundle_id":"toolchain.csharp.roslyn-5_6_0.dotnet-10_0_11.candidate.v1",
            "distribution_sha256":"6cc7711334ffcd9216cfb241e1508491abb62a13b01ebc9b2d883a1ace9627bc",
            "components":[]
        },
        "frontend":{
            "bundle_id":"frontend.csharp.csharp2vir.candidate.v1",
            "name":"csharp2vir",
            "version":"0.1.0",
            "binary_sha256":"e245d50913f8589be6fd763aa9185d3812b932a5dabc0e21ed03744eafa09f49",
            "subordinate_binaries":[]
        },
        "units":[{"identity":"payment-policy","name":"payment-policy","kind":"compilation"}],
        "target":{"id":"linux-x64","pointer_width":64},
        "inputs":inputs,
        "input_set_hash":input_set_hash(&inputs).expect("input-set hash").as_str(),
        "vir_hash":vir.hash().as_str(),
        "source_map_hash":source_map.hash().as_str(),
        "source_manifest_hash":ZERO_SHA256
    });
    manifest["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&manifest)
            .expect("C# source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("C# successor manifest");
    ValidatedSource { vir, manifest }
}

fn generated_pair<'a>(
    registry: &'a ValidatedSemanticProfileRegistry,
    source: &'a ValidatedSource,
    contract: &'a Value,
) -> (
    mpk_vc::successor_vc::ValidatedSuccessorVc,
    mpk_vc::successor_vc::ValidatedSuccessorVcSkeleton,
) {
    let linked = SuccessorVcSource {
        registry,
        vir: &source.vir,
        manifest: &source.manifest,
        profile_contract: contract,
    };
    let first = generate_successor_vc(linked).expect("successor VC generation");
    let second = generate_successor_vc(linked).expect("repeat successor VC generation");
    assert_eq!(first.canonical_bytes(), second.canonical_bytes());
    assert_eq!(first.document().schema(), SUCCESSOR_VC_SCHEMA);
    assert_eq!(first.document().source_ir_schema(), "mpk.vir.v1");
    assert_eq!(
        first.document().source_manifest_schema(),
        "mpk.source_manifest.v1"
    );
    assert_eq!(first.hash(), first.document().vc_hash());
    assert!(!first.canonical_bytes().ends_with(b"\n"));
    assert!(serde_json::from_slice::<VcDocument>(first.canonical_bytes()).is_err());

    let skeleton = emit_successor_vc_skeleton(&first, linked).expect("successor skeleton");
    let repeated = emit_successor_vc_skeleton(&first, linked).expect("repeat skeleton");
    assert_eq!(skeleton.canonical_bytes(), repeated.canonical_bytes());
    assert_eq!(skeleton.skeleton().schema(), SUCCESSOR_VC_SKELETON_SCHEMA);
    assert_eq!(skeleton.skeleton().source_vc_hash(), first.hash());
    assert!(!skeleton.canonical_bytes().ends_with(b"\n"));
    assert!(serde_json::from_slice::<VcCertificateSkeletonV1>(skeleton.canonical_bytes()).is_err());
    (first, skeleton)
}

#[test]
fn all_three_profiles_generate_canonical_successor_vc_and_skeleton_bytes() {
    let registry = registry();
    let go = staged_source(
        &registry,
        "fixtures/vir-go/frontend/basic-arith",
        "fixtures/go-basic",
    );
    let rust = staged_source(
        &registry,
        "fixtures/rust-basic/positive/checked-addition/artifacts",
        "rust-tools/rust2vir/testdata/positive/checked-addition/source",
    );
    let csharp = csharp_source(&registry);
    let go_contract = profile_contract("go");
    let rust_contract = profile_contract("rust");
    let csharp_contract = profile_contract("csharp");

    let (go_vc, _) = generated_pair(&registry, &go, &go_contract);
    let (rust_vc, _) = generated_pair(&registry, &rust, &rust_contract);
    let (csharp_vc, _) = generated_pair(&registry, &csharp, &csharp_contract);
    assert_eq!(go_vc.document().semantic_context().source_language(), "go");
    assert_eq!(
        rust_vc.document().semantic_context().source_language(),
        "rust"
    );
    assert_eq!(
        csharp_vc.document().semantic_context().source_language(),
        "csharp"
    );
    assert_eq!(SUCCESSOR_VC_HASH_DOMAIN.as_str(), "MPK-VC-2.0");
    assert_ne!(go_vc.hash(), rust_vc.hash());
    assert_ne!(rust_vc.hash(), csharp_vc.hash());
}

#[test]
fn successor_vc_test_owns_each_consumed_frozen_vector_set() {
    let manifest = load("develop/specs/vectors/manifest.json");
    for path in [
        "develop/specs/vectors/csharp-profile-v0.json",
        "develop/specs/vectors/semantic-profile-registry-v1.json",
        "develop/specs/vectors/semantic-profile-registry-v2.json",
    ] {
        let record = manifest["vectors"]
            .as_array()
            .expect("vector manifest records")
            .iter()
            .find(|record| record["path"] == path)
            .unwrap_or_else(|| panic!("missing vector manifest record {path}"));
        assert!(record["implementation_test_owners"]
            .as_array()
            .expect("implementation test owners")
            .iter()
            .any(|owner| owner == "crates/mpk-vc/tests/successor_vc.rs"));
    }
}

#[test]
fn go_and_rust_obligations_are_active_and_deterministic() {
    let registry = registry();
    let go = staged_source(
        &registry,
        "fixtures/vir-go/frontend/basic-arith",
        "fixtures/go-basic",
    );
    let rust = staged_source(
        &registry,
        "fixtures/rust-basic/positive/checked-addition/artifacts",
        "rust-tools/rust2vir/testdata/positive/checked-addition/source",
    );
    let go_contract = profile_contract("go");
    let rust_contract = profile_contract("rust");
    let (go_vc, _) = generated_pair(&registry, &go, &go_contract);
    let (rust_vc, _) = generated_pair(&registry, &rust, &rust_contract);

    assert!(!go_vc.document().functions().is_empty());
    assert!(!rust_vc.document().functions().is_empty());
    assert_eq!(go_vc.document().semantic_context().source_language(), "go");
    assert_eq!(
        rust_vc.document().semantic_context().source_language(),
        "rust"
    );
}

#[test]
fn csharp_required_checks_reach_the_checked_bool_bv_foundation() {
    let registry = registry();
    let csharp = csharp_source(&registry);
    let contract = profile_contract("csharp");
    let (vc, skeleton) = generated_pair(&registry, &csharp, &contract);
    let observed = vc
        .required_checks()
        .iter()
        .map(|audit| audit.check().clone())
        .collect::<Vec<_>>();
    let expected = vec![
        VirSafetyCheck::IntegerNoOverflow {
            operation: mpk_vc::OverflowOperation::Add,
            signed: true,
        },
        VirSafetyCheck::IntegerNoOverflow {
            operation: mpk_vc::OverflowOperation::Sub,
            signed: true,
        },
        VirSafetyCheck::IntegerNoOverflow {
            operation: mpk_vc::OverflowOperation::Mul,
            signed: true,
        },
        VirSafetyCheck::IntegerNoOverflow {
            operation: mpk_vc::OverflowOperation::Neg,
            signed: true,
        },
        VirSafetyCheck::DivisorNonzero {},
        VirSafetyCheck::SignedDivremRepresentable {
            operation: mpk_vc::DivRemOperation::Div,
        },
        VirSafetyCheck::DivisorNonzero {},
        VirSafetyCheck::SignedDivremRepresentable {
            operation: mpk_vc::DivRemOperation::Rem,
        },
        VirSafetyCheck::DivisorNonzero {},
        VirSafetyCheck::DivisorNonzero {},
    ]
    .into_iter()
    .flat_map(|check| [check.clone(), check])
    .collect::<Vec<_>>();
    assert_eq!(vc.required_checks().len(), expected.len());
    assert_eq!(observed, expected);
    let run = vc
        .document()
        .functions()
        .iter()
        .find(|function| function.function_id == CSHARP_FUNCTION)
        .expect("C# caller VC");
    let callee = vc
        .document()
        .functions()
        .iter()
        .find(|function| function.function_id == CSHARP_CALLEE_FUNCTION)
        .expect("C# callee VC");
    let members = run
        .members
        .iter()
        .map(|member| (member.id.as_str(), member))
        .collect::<BTreeMap<_, _>>();
    for audit in vc.required_checks() {
        assert_eq!(audit.function_id(), CSHARP_FUNCTION);
        assert_eq!(
            audit.evidence_route(),
            SafetyEvidenceRoute::GroupedCertificate {
                foundation: "Std.Program.Base"
            }
        );
        let member = members[audit.member_id()];
        let mut names = BTreeSet::new();
        collect_term_names(&member.conclusion, &mut names);
        assert!(
            names
                .iter()
                .any(|name| name.starts_with("Std.BitVec.BV32.")),
            "{} has no checked BV32 path: {names:?}",
            audit.member_id()
        );
        assert!(names.iter().all(|name| {
            name.starts_with("Std.BitVec.")
                || name.starts_with("Std.Bool.")
                || name == "Std.Eq"
                || name == "Std.Logic.Imp"
        }));
    }
    let run_contract = run
        .groups
        .iter()
        .find(|group| group.kind == VcGroupKind::Contract)
        .expect("C# caller contract group");
    let callee_contract = callee
        .groups
        .iter()
        .find(|group| group.kind == VcGroupKind::Contract)
        .expect("C# callee contract group");
    assert!(run_contract
        .dependencies
        .contains(&callee_contract.declaration_name));
    assert_eq!(
        skeleton.skeleton().theorem_declarations().len(),
        vc.document()
            .functions()
            .iter()
            .map(|function| function.groups.len())
            .sum::<usize>()
    );
}

#[test]
fn successor_linkage_and_old_new_boundaries_fail_closed() {
    let registry = registry();
    let csharp = csharp_source(&registry);
    let contract = profile_contract("csharp");
    let linked = SuccessorVcSource {
        registry: &registry,
        vir: &csharp.vir,
        manifest: &csharp.manifest,
        profile_contract: &contract,
    };
    let vc = generate_successor_vc(linked).expect("successor VC");
    let skeleton = emit_successor_vc_skeleton(&vc, linked).expect("successor skeleton");

    let mut wrong_context: Value = serde_json::from_slice(vc.canonical_bytes()).expect("VC JSON");
    wrong_context["semantic_context"] =
        load("release/bundles/candidates/go.json")["tuples"][0]["semantic_context"].clone();
    rehash_vc_value(&mut wrong_context);
    assert!(import_successor_vc_json(&canonical(&wrong_context), linked).is_err());

    let mut wrong_vir: Value = serde_json::from_slice(vc.canonical_bytes()).expect("VC JSON");
    wrong_vir["source_ir_hash"] = Value::String(ZERO_SHA256.to_owned());
    rehash_vc_value(&mut wrong_vir);
    assert!(import_successor_vc_json(&canonical(&wrong_vir), linked).is_err());

    let mut wrong_manifest: Value = serde_json::from_slice(vc.canonical_bytes()).expect("VC JSON");
    wrong_manifest["source_manifest_hash"] = Value::String(ZERO_SHA256.to_owned());
    rehash_vc_value(&mut wrong_manifest);
    assert!(import_successor_vc_json(&canonical(&wrong_manifest), linked).is_err());

    let mut wrong_function_contract: Value =
        serde_json::from_slice(vc.canonical_bytes()).expect("VC JSON");
    wrong_function_contract["functions"][0]["contract_hash"] =
        Value::String(ZERO_SHA256.to_owned());
    rehash_vc_value(&mut wrong_function_contract);
    assert!(import_successor_vc_json(&canonical(&wrong_function_contract), linked).is_err());

    let mut wrong_member: Value = serde_json::from_slice(vc.canonical_bytes()).expect("VC JSON");
    wrong_member["functions"][0]["members"][0]["group_id"] =
        Value::String("crossed.group".to_owned());
    rehash_vc_value(&mut wrong_member);
    assert!(import_successor_vc_json(&canonical(&wrong_member), linked).is_err());

    let mut wrong_contract = contract.clone();
    wrong_contract["value"]["required_check_profile_id"] =
        Value::String("mpk.rust.checked.v0".to_owned());
    assert!(generate_successor_vc(SuccessorVcSource {
        profile_contract: &wrong_contract,
        ..linked
    })
    .is_err());

    let mut wrong_declaration: Value =
        serde_json::from_slice(skeleton.canonical_bytes()).expect("skeleton JSON");
    wrong_declaration["theorem_declarations"][0]["member_ids"] = json!([]);
    assert!(import_successor_vc_skeleton_json(
        &canonical(&wrong_declaration),
        vc.canonical_bytes(),
        linked,
    )
    .is_err());

    let mut wrong_vc_link: Value =
        serde_json::from_slice(skeleton.canonical_bytes()).expect("skeleton JSON");
    wrong_vc_link["source_vc_hash"] = Value::String(ZERO_SHA256.to_owned());
    assert!(import_successor_vc_skeleton_json(
        &canonical(&wrong_vc_link),
        vc.canonical_bytes(),
        linked,
    )
    .is_err());

    let mut noncanonical_vc = b" ".to_vec();
    noncanonical_vc.extend_from_slice(vc.canonical_bytes());
    assert!(import_successor_vc_json(&noncanonical_vc, linked).is_err());

    let active_vc = load("develop/specs/vectors/vc-v1.json")["fixtures"][0]["input"].clone();
    assert!(import_successor_vc_json(&canonical(&active_vc), linked).is_err());
    assert!(serde_json::from_slice::<VcDocument>(vc.canonical_bytes()).is_err());
    assert!(serde_json::from_slice::<VcCertificateSkeletonV1>(skeleton.canonical_bytes()).is_err());
}

fn collect_term_names(term: &VcTerm, output: &mut BTreeSet<String>) {
    match term {
        VcTerm::Constant { name } => {
            output.insert(name.clone());
        }
        VcTerm::Apply { function, args } => {
            output.insert(function.clone());
            for argument in args {
                collect_term_names(argument, output);
            }
        }
        VcTerm::Convert { value, .. } => collect_term_names(value, output),
        VcTerm::Forall { body, .. } => collect_term_names(body, output),
        VcTerm::Var { .. } | VcTerm::Bound { .. } | VcTerm::BitVecLiteral { .. } => {}
    }
}

fn rehash_vc_value(value: &mut Value) {
    value["vc_hash"] = Value::String(ZERO_SHA256.to_owned());
    let mut payload = value.clone();
    payload
        .as_object_mut()
        .expect("VC object")
        .remove("vc_hash");
    value["vc_hash"] = Value::String(
        hash_domain_separated_raw(SUCCESSOR_VC_HASH_DOMAIN, &canonical(&payload))
            .expect("successor VC hash")
            .to_hex(),
    );
}
