include!("builder.rs");
include!("normalizer.rs");
use serde_json::{json,Value};
use std::{fs,path::Path};
fn hex(p:&Path)->Vec<u8>{let h=fs::read_to_string(p).unwrap().split_whitespace().collect::<String>();(0..h.len()).step_by(2).map(|i|u8::from_str_radix(&h[i..i+2],16).unwrap()).collect()}
fn expression(b:&Builder,t:u32)->u32 {let TermNode::App{function,arguments}=&b.c.term_table[t as usize]else{panic!("expected truth")};let TermNode::Const{global,..}=b.c.term_table[*function as usize]else{panic!("expected Eq")};assert_eq!(b.c.name_table[b.c.declarations[global as usize].name as usize],"Std.Eq");assert_eq!(arguments.len(),3);arguments[1]}
fn main(){std::thread::Builder::new().stack_size(64*1024*1024).spawn(run).unwrap().join().unwrap();}
fn run(){let a=std::env::args().collect::<Vec<_>>();let repo=Path::new(&a[1]);let out=Path::new(&a[2]);fs::create_dir_all(out).unwrap();
 let root=repo.join("develop/migrations/csharp-03/ordinary-foundation/control-predicates/with-packed-pattern-proof-types");let meta:Value=serde_json::from_slice(&fs::read(root.join("is_binding.json")).unwrap()).unwrap();let raw=hex(&root.join("is_binding.hex"));assert_eq!(meta["certificate_sha256"],mpk_cert::hash_hex(&mpk_cert::certificate_hash(&raw)));let original=mpk_cert::decode_canonical_certificate(&raw).unwrap();let mut b=Builder::from(original.clone());let mut reports=vec![];
 for (i,path) in meta["pattern_proof_types"].as_array().unwrap().iter().enumerate(){let name=path["refinement_proposition_definition"].as_str().unwrap();let DeclarationKind::Def{value:mut goal,..}=b.c.declarations[b.globals[name]as usize].kind else{panic!("named type")};let mut binders=vec![];while let TermNode::Pi{ty,body}=b.c.term_table[goal as usize]{binders.push(ty);goal=body;}assert_eq!(binders.len(),2);let mut facts=vec![];
  for item in path["premise_proofs"].as_array().unwrap(){let theorem=item["theorem"].as_str().unwrap();let DeclarationKind::Theorem{mut ty,..}=b.c.declarations[b.globals[theorem]as usize].kind else{panic!("checked projection")};for _ in 0..binders.len(){let TermNode::Pi{body,..}=b.c.term_table[ty as usize]else{panic!("premise spine")};ty=body;}let expression=expression(&b,ty);let env=b.var(1).unwrap();let scope=b.var(0).unwrap();let proof=call(&mut b,theorem,vec![env,scope]).unwrap();facts.push((expression,true,proof));}
  let value=expression(&b,goal);eprintln!("Path {i}, goal {value}, {} complete scope facts",facts.len());let result=prove_boolean_in_context(&mut b,value,true,&facts);
  match result{Ok(mut proof)=>{for binder in binders.into_iter().rev(){proof=b.lam(binder,proof).unwrap();}let ty=b.constant(name).unwrap();publish_theorem(&mut b,&format!("Probe.OriginalPattern.Path{i}"),ty,proof).unwrap();reports.push(json!({"path":i,"generated":true,"original_type":name}));},Err(e)=>{reports.push(json!({"path":i,"generated":false,"original_type":name,"error":format!("{e:?}")}));break;}}
 }
 assert!(b.c.term_table.starts_with(&original.term_table));for (old,new) in original.declarations.iter().zip(&b.c.declarations){assert_eq!(old.kind,new.kind);assert_eq!(original.name_table[old.name as usize],b.c.name_table[new.name as usize]);}
 fs::write(out.join("diagnostic-partial.mpcert"),b.clone_for_diagnostic()).unwrap();let required=meta["pattern_proof_types"].as_array().unwrap().len();fs::write(out.join("generation.json"),serde_json::to_vec_pretty(&json!({"diagnostic_only":true,"application_scope_pending":true,"required_paths":required,"paths":reports})).unwrap()).unwrap();if reports.len()==required&&reports.iter().all(|x|x["generated"]==true){let bytes=b.finish();fs::write(out.join("candidate.mpcert"),bytes).unwrap();}
}
