//! CSHARP-03-T02-W08: private predecessor-producer migration.
//!
//! The installed revision-3 routes remain untouched.  These tests inject the
//! candidate registry and migration adapter directly, exercise real checked-in
//! Go/Rust frontend artifacts, bind the complete scalar C#/Java corpora, and
//! reject every frozen protocol/linkage/limit mutation owned by W08.

use mpk_cli::csharp_practical_frontend_protocol::{
    build_csharp_practical_frontend_request, emit_csharp_practical_frontend_diagnostic,
    validate_csharp_practical_frontend_process, PracticalDiagnosticFamily,
    PracticalDiagnosticFinding, PracticalDiagnosticLocation, PracticalFrontendProtocolCode,
    PracticalFrontendValidationContext, ValidatedPracticalFrontendRequest,
    CSHARP_PRACTICAL_PUBLIC_DIAGNOSTIC_MESSAGE,
};
use mpk_cli::csharp_practical_migration::{
    migrate_predecessor_frontend, retained_predecessor_limit, select_private_csharp_producer,
    validate_private_successor_schema, validate_retained_predecessor_limit,
    PredecessorMigrationCode, PredecessorProducer, PrivateCSharpProducerRoute,
    PrivatePredecessorMigration, PrivateSuccessorArtifact, PrivateSuccessorSchemaKind,
    RETAINED_PREDECESSOR_LIMITS, SUCCESSOR_CLOSED_INSTANCES_SCHEMA,
    SUCCESSOR_FRONTEND_DIAGNOSTIC_SCHEMA, SUCCESSOR_FRONTEND_MANIFEST_SCHEMA,
    SUCCESSOR_FRONTEND_REQUEST_SCHEMA, SUCCESSOR_FRONTEND_SUCCESS_SCHEMA,
    SUCCESSOR_SEMANTIC_BINDINGS_SCHEMA, SUCCESSOR_SOURCE_ARTIFACTS_SCHEMA,
    SUCCESSOR_SOURCE_MAP_SCHEMA, SUCCESSOR_VIR_SCHEMA,
};
use mpk_cli::frontend_protocol::FrontendProcessFacts;
use mpk_cli::successor_frontend_protocol::{
    validate_successor_frontend_process, AcceptedSuccessorFrontendEnvelope,
    SuccessorFrontendProtocolRequest,
};
use mpk_vc::csharp_practical_registry::{
    canonical_successor_registry_transport, csharp_practical_selection_hash,
    successor_profile_entry_hash, successor_profile_registry_hash,
    successor_validated_request_hash, validate_candidate_successor_registry,
    validate_successor_semantic_request, SuccessorCompiledSemanticProfile,
    SuccessorProfileContract, ValidatedSuccessorRegistry, ValidatedSuccessorRequest,
    CSHARP_PRACTICAL_SELECTION_SCHEMA, FOUNDATION_DESCRIPTOR_CONTENT_SHA256,
    FOUNDATION_DESCRIPTOR_ID, FOUNDATION_DESCRIPTOR_SCHEMA, SUCCESSOR_CANDIDATE_REVISION,
    SUCCESSOR_CONTRACT_FIELDS, SUCCESSOR_PROFILE_ORDER, SUCCESSOR_SEMANTIC_CONTEXT_SCHEMA,
    SUCCESSOR_SEMANTIC_REGISTRY_ENTRY_SCHEMA, SUCCESSOR_SEMANTIC_REGISTRY_SCHEMA,
    SUCCESSOR_VALIDATED_REQUEST_SCHEMA,
};
use mpk_vc::csharp_practical_source_artifacts::{
    bind_practical_artifact_context, capture_original_inputs, OriginalInput, OriginalInputKind,
};
use mpk_vc::csharp_practical_vir_model::{
    registered_foundation_definitions_transport, registered_foundation_descriptor_transport,
    validate_registered_foundation_bundle,
};
use mpk_vc::semantic_profile_registry::{
    validate_registry_selection_envelope, validate_registry_semantic_context,
    validate_semantic_profile_registry, RegistryRevision, ValidatedSemanticProfileRegistry,
};
use mpk_vc::{
    canonical_json_bytes, hash_domain_separated_raw, sha256_raw_file_bytes, CapturedInput,
    HashDomain, InputKind, ReleaseRegistryIdentity, SourceReference, StrictJsonValue,
    SyntheticPermission,
};
use serde_json::{json, Map, Value};
use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

const WORK_ITEM: &str = "CSHARP-03-T02-W08";
const OWNER: &str = "crates/mpk-cli/tests/csharp_practical_migration.rs#CSHARP-03-T02-W08";
const PACKAGE_PATH: &str = "develop/specs/vectors/csharp-practical-profile-v1.json";
const ACTIVE_REGISTRY_PATH: &str = "release/bundles/semantic-profile-registry.json";
const GO_ROOT: &str = "fixtures/vir-go";
const RUST_ROOT: &str = "fixtures/rust-basic/positive";
const ZERO_SHA256: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";

struct OwnedCapturedInput {
    kind: InputKind,
    normalized_path: String,
    bytes: Vec<u8>,
}

struct CandidateRegistry {
    value: Value,
    validated: ValidatedSuccessorRegistry,
}

struct DiagnosticFixture {
    request: ValidatedPracticalFrontendRequest,
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    let relative = relative.as_ref();
    fs::read(repository_root().join(relative))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.display()))
}

fn load(relative: impl AsRef<Path>) -> Value {
    let relative = relative.as_ref();
    serde_json::from_slice(&read(relative))
        .unwrap_or_else(|error| panic!("decode {}: {error}", relative.display()))
}

fn active_registry() -> ValidatedSemanticProfileRegistry {
    validate_semantic_profile_registry(&read(ACTIVE_REGISTRY_PATH), RegistryRevision::Revision3)
        .expect("active revision-3 registry")
}

fn candidate_registry() -> CandidateRegistry {
    let profiles = SUCCESSOR_PROFILE_ORDER
        .into_iter()
        .map(candidate_entry)
        .collect::<Vec<_>>();
    let mut value = json!({
        "schema": SUCCESSOR_SEMANTIC_REGISTRY_SCHEMA,
        "id": SUCCESSOR_SEMANTIC_REGISTRY_SCHEMA,
        "revision": SUCCESSOR_CANDIDATE_REVISION,
        "profiles": profiles,
        "registry_sha256": ZERO_SHA256,
    });
    value["registry_sha256"] =
        Value::String(successor_profile_registry_hash(&value).expect("candidate registry hash"));
    let transport =
        canonical_successor_registry_transport(&value).expect("candidate registry transport");
    let validated =
        validate_candidate_successor_registry(&transport).expect("candidate registry validates");
    CandidateRegistry { value, validated }
}

fn candidate_entry(profile: SuccessorCompiledSemanticProfile) -> Value {
    let contracts = SUCCESSOR_CONTRACT_FIELDS
        .into_iter()
        .map(|field| {
            (
                field.as_str().to_owned(),
                Value::String(SuccessorProfileContract::new(profile, field).contract_id()),
            )
        })
        .collect::<Map<_, _>>();
    let mut entry = json!({
        "schema": SUCCESSOR_SEMANTIC_REGISTRY_ENTRY_SCHEMA,
        "source_language": profile.source_language(),
        "semantic_profile": profile.semantic_profile(),
        "semantic_parameters_schema": profile.semantic_parameters_schema(),
        "selection_schema": profile.selection_schema(),
        "foundation_descriptor": foundation_descriptor(),
        "contracts": contracts,
        "entry_sha256": ZERO_SHA256,
    });
    entry["entry_sha256"] =
        Value::String(successor_profile_entry_hash(&entry).expect("candidate entry hash"));
    entry
}

fn foundation_descriptor() -> Value {
    json!({
        "schema": FOUNDATION_DESCRIPTOR_SCHEMA,
        "id": FOUNDATION_DESCRIPTOR_ID,
        "content_sha256": FOUNDATION_DESCRIPTOR_CONTENT_SHA256,
    })
}

fn candidate_request(
    registry: &CandidateRegistry,
    old_context: &Value,
    selection: &Value,
) -> ValidatedSuccessorRequest {
    let profile = old_context["semantic_profile"]
        .as_str()
        .expect("predecessor semantic profile");
    let entry = registry.value["profiles"]
        .as_array()
        .expect("candidate profiles")
        .iter()
        .find(|entry| entry["semantic_profile"] == profile)
        .expect("candidate predecessor entry");
    let context = json!({
        "schema": SUCCESSOR_SEMANTIC_CONTEXT_SCHEMA,
        "profile_registry": {
            "schema": registry.value["schema"],
            "id": registry.value["id"],
            "revision": registry.value["revision"],
            "registry_sha256": registry.value["registry_sha256"],
        },
        "profile_entry_sha256": entry["entry_sha256"],
        "source_language": old_context["source_language"],
        "semantic_profile": old_context["semantic_profile"],
        "semantic_parameters": old_context["semantic_parameters"],
        "foundation_descriptor": foundation_descriptor(),
    });
    let mut request = json!({
        "schema": SUCCESSOR_VALIDATED_REQUEST_SCHEMA,
        "semantic_context": context,
        "selection": selection,
        "request_sha256": ZERO_SHA256,
    });
    request["request_sha256"] =
        Value::String(successor_validated_request_hash(&request).expect("successor request hash"));
    validate_successor_semantic_request(&registry.validated, &canonical(&request))
        .expect("successor request validates")
}

fn canonical(value: &Value) -> Vec<u8> {
    canonical_json_bytes(&to_strict(value)).expect("canonical JSON")
}

fn canonical_line(value: &Value) -> Vec<u8> {
    let mut bytes = canonical(value);
    bytes.push(b'\n');
    bytes
}

fn to_strict(value: &Value) -> StrictJsonValue {
    match value {
        Value::Null => StrictJsonValue::Null,
        Value::Bool(value) => StrictJsonValue::Bool(*value),
        Value::Number(value) => StrictJsonValue::Integer(value.as_i64().expect("integer")),
        Value::String(value) => StrictJsonValue::String(value.clone()),
        Value::Array(values) => StrictJsonValue::Array(values.iter().map(to_strict).collect()),
        Value::Object(values) => StrictJsonValue::Object(
            values
                .iter()
                .map(|(name, value)| (name.clone(), to_strict(value)))
                .collect(),
        ),
    }
}

fn process(stdout: &[u8], exit_code: i32) -> FrontendProcessFacts<'_> {
    FrontendProcessFacts {
        exit_code: Some(exit_code),
        signaled: false,
        stdout,
        stderr_observed_bytes: 0,
    }
}

fn exit_for_status(status: &str) -> i32 {
    match status {
        "ir-lowered" => 0,
        "frontend-error" => 1,
        "rejected" => 3,
        "source-error" => 4,
        other => panic!("unknown predecessor status {other}"),
    }
}

fn dummy_release() -> ReleaseRegistryIdentity {
    ReleaseRegistryIdentity {
        schema: "mpk.release.registry.v1".into(),
        id: "mpk.release.registry.v1".into(),
        registry_sha256: "2".repeat(64),
    }
}

fn validate_predecessor(
    registry: &ValidatedSemanticProfileRegistry,
    envelope: &Value,
    captured_inputs: &[CapturedInput<'_>],
    synthetic_permissions: &[SyntheticPermission],
) -> AcceptedSuccessorFrontendEnvelope {
    let context = validate_registry_semantic_context(registry, &envelope["semantic_context"])
        .expect("predecessor semantic context");
    let selection =
        validate_registry_selection_envelope(registry, &context, &envelope["selection"])
            .expect("predecessor selection");
    let release = envelope
        .get("source_manifest")
        .and_then(|manifest| manifest.get("release_registry"))
        .map(|value| serde_json::from_value(value.clone()).expect("release registry identity"))
        .unwrap_or_else(dummy_release);
    let stdout = canonical_line(envelope);
    validate_successor_frontend_process(
        SuccessorFrontendProtocolRequest {
            registry,
            semantic_context: &context,
            selection: &selection,
            release_registry: &release,
            captured_inputs,
            synthetic_permissions,
        },
        process(
            &stdout,
            exit_for_status(envelope["status"].as_str().expect("status")),
        ),
    )
    .expect("predecessor envelope validates")
}

fn input_kind(value: &Value) -> InputKind {
    match value.as_str().expect("input kind") {
        "source" => InputKind::Source,
        "contract" => InputKind::Contract,
        "build_manifest" => InputKind::BuildManifest,
        "lockfile" => InputKind::Lockfile,
        other => panic!("unknown input kind {other}"),
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = input_kind(&entry["kind"]);
            let normalized_path = entry["normalized_path"]
                .as_str()
                .expect("normalized path")
                .to_owned();
            let path = repository_root().join(source_root).join(&normalized_path);
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(error)
                    if error.kind() == std::io::ErrorKind::NotFound
                        && kind == InputKind::BuildManifest
                        && normalized_path == "Cargo.toml" =>
                {
                    GENERATED_CARGO_TOML.to_vec()
                }
                Err(error)
                    if error.kind() == std::io::ErrorKind::NotFound
                        && kind == InputKind::Lockfile
                        && normalized_path == "Cargo.lock" =>
                {
                    GENERATED_CARGO_LOCK.to_vec()
                }
                Err(error)
                    if error.kind() == std::io::ErrorKind::NotFound
                        && kind == InputKind::Lockfile =>
                {
                    Vec::new()
                }
                Err(error) => panic!("read captured input {}: {error}", path.display()),
            };
            assert_eq!(bytes.len() as u64, entry["size_bytes"].as_u64().unwrap());
            assert_eq!(
                sha256_raw_file_bytes(&bytes).to_hex(),
                entry["sha256"].as_str().unwrap()
            );
            OwnedCapturedInput {
                kind,
                normalized_path,
                bytes,
            }
        })
        .collect()
}

fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.normalized_path,
            bytes: &input.bytes,
        })
        .collect()
}

fn go_synthetic_permissions(source_map: &Value) -> Vec<SyntheticPermission> {
    source_map["entries"]
        .as_array()
        .expect("source map entries")
        .iter()
        .filter(|entry| entry["origin"]["kind"] == "synthetic")
        .map(|entry| SyntheticPermission {
            reference: serde_json::from_value::<SourceReference>(entry["reference"].clone())
                .expect("synthetic source reference"),
            reason: entry["origin"]["reason"]
                .as_str()
                .expect("synthetic reason")
                .to_owned(),
        })
        .collect()
}

fn diagnostic_fixture() -> DiagnosticFixture {
    let registry = candidate_registry();
    let mut selection = json!({
        "schema": CSHARP_PRACTICAL_SELECTION_SCHEMA,
        "compilation_id": "migration.protocol",
        "source_paths": ["src/Input.cs"],
        "selected_root_ids": [format!("mpk.csharp.source.{}", "1".repeat(64))],
        "sidecar_paths": [],
        "selection_sha256": ZERO_SHA256,
    });
    selection["selection_sha256"] = Value::String(
        csharp_practical_selection_hash(&selection).expect("practical selection hash"),
    );
    let practical_context = json!({
        "source_language": "csharp",
        "semantic_profile": "mpk.csharp.practical.v1",
        "semantic_parameters": {
            "schema": "mpk.semantic_parameters.csharp_practical.v1",
            "value": {
                "check_overflow_default": true,
                "documentation_mode": "none",
                "language_version": "14.0",
                "nullable_context": "enable",
                "optimization": "release",
                "platform": "x64",
                "pointer_width": 64,
                "preprocessor_symbols": [],
                "source_kind": "regular",
                "target_framework": "net10.0",
                "target_id": "linux-x64",
                "unsafe": false,
            },
        },
    });
    let semantic_request = candidate_request(&registry, &practical_context, &selection);
    let foundation = validate_registered_foundation_bundle(
        registered_foundation_descriptor_transport(),
        registered_foundation_definitions_transport(),
    )
    .expect("registered foundation");
    let context =
        bind_practical_artifact_context(&semantic_request, &foundation).expect("artifact context");
    let captures = capture_original_inputs(
        &context,
        vec![OriginalInput {
            kind: OriginalInputKind::Source,
            path: "src/Input.cs".into(),
            bytes: b"0123456789".to_vec(),
        }],
    )
    .expect("diagnostic capture");
    let request = build_csharp_practical_frontend_request(&semantic_request, &captures, &[])
        .expect("diagnostic frontend request");
    DiagnosticFixture { request }
}

fn family(code: &str) -> PracticalDiagnosticFamily {
    match code {
        "CSHARP_PRACTICAL_PROTOCOL" => PracticalDiagnosticFamily::Protocol,
        "CSHARP_PRACTICAL_LIMIT" => PracticalDiagnosticFamily::Limit,
        "CSHARP_PRACTICAL_DECLARATION" => PracticalDiagnosticFamily::Declaration,
        "CSHARP_PRACTICAL_TYPE" => PracticalDiagnosticFamily::Type,
        "CSHARP_PRACTICAL_DEPENDENCY" => PracticalDiagnosticFamily::Dependency,
        "CSHARP_PRACTICAL_GENERIC" => PracticalDiagnosticFamily::Generic,
        "CSHARP_PRACTICAL_SOURCE_BINDING" => PracticalDiagnosticFamily::SourceBinding,
        "CSHARP_PRACTICAL_OBJECT" => PracticalDiagnosticFamily::Object,
        "CSHARP_PRACTICAL_INITIALIZER" => PracticalDiagnosticFamily::Initializer,
        "CSHARP_PRACTICAL_OWNERSHIP" => PracticalDiagnosticFamily::Ownership,
        "CSHARP_PRACTICAL_ARRAY" => PracticalDiagnosticFamily::Array,
        "CSHARP_PRACTICAL_COLLECTION" => PracticalDiagnosticFamily::Collection,
        "CSHARP_PRACTICAL_ORDER" => PracticalDiagnosticFamily::Order,
        "CSHARP_PRACTICAL_STRING" => PracticalDiagnosticFamily::String,
        "CSHARP_PRACTICAL_PARSE_FORMAT" => PracticalDiagnosticFamily::ParseFormat,
        "CSHARP_PRACTICAL_FLOAT" => PracticalDiagnosticFamily::Float,
        "CSHARP_PRACTICAL_DECIMAL" => PracticalDiagnosticFamily::Decimal,
        "CSHARP_PRACTICAL_NULLABLE" => PracticalDiagnosticFamily::Nullable,
        "CSHARP_PRACTICAL_RESULT" => PracticalDiagnosticFamily::Result,
        "CSHARP_PRACTICAL_BUSINESS_VALUE" => PracticalDiagnosticFamily::BusinessValue,
        "CSHARP_PRACTICAL_LOOP_CONTRACT" => PracticalDiagnosticFamily::LoopContract,
        "CSHARP_PRACTICAL_SWITCH" => PracticalDiagnosticFamily::Switch,
        "CSHARP_PRACTICAL_PATTERN" => PracticalDiagnosticFamily::Pattern,
        "CSHARP_PRACTICAL_EXCEPTION" => PracticalDiagnosticFamily::Exception,
        "CSHARP_PRACTICAL_BOUNDARY" => PracticalDiagnosticFamily::Boundary,
        "CSHARP_PRACTICAL_TRANSITION" => PracticalDiagnosticFamily::Transition,
        "CSHARP_PRACTICAL_EFFECT" => PracticalDiagnosticFamily::Effect,
        "CSHARP_PRACTICAL_FOUNDATION" => PracticalDiagnosticFamily::Foundation,
        "CSHARP_PRACTICAL_LOWERING" => PracticalDiagnosticFamily::Lowering,
        other => panic!("unknown practical diagnostic family {other}"),
    }
}

fn validate_practical_diagnostic(
    fixture: &DiagnosticFixture,
    stdout: &[u8],
    validated: bool,
) -> Result<
    mpk_cli::csharp_practical_frontend_protocol::AcceptedPracticalFrontendEnvelope,
    PracticalFrontendProtocolCode,
> {
    validate_csharp_practical_frontend_process(
        PracticalFrontendValidationContext {
            raw_request: fixture.request.canonical_bytes(),
            validated_request: validated.then_some(&fixture.request),
            artifact_context: None,
            captured_inputs: None,
            expected_artifacts: None,
        },
        process(stdout, 3),
    )
    .map_err(|error| error.code())
}

fn emitted_diagnostic(
    fixture: &DiagnosticFixture,
    families: &[PracticalDiagnosticFamily],
) -> Vec<u8> {
    let findings = families
        .iter()
        .copied()
        .map(|family| PracticalDiagnosticFinding {
            family,
            location: None,
        })
        .collect::<Vec<_>>();
    emit_csharp_practical_frontend_diagnostic(
        fixture.request.canonical_bytes(),
        Some(&fixture.request),
        &findings,
    )
    .expect("emit diagnostic")
}

fn replace_once(bytes: &[u8], from: &str, to: &str) -> Vec<u8> {
    let text = std::str::from_utf8(bytes).expect("UTF-8 transport");
    assert_eq!(
        text.matches(from).count(),
        1,
        "unique mutation target {from}"
    );
    text.replacen(from, to, 1).into_bytes()
}

fn parse_line(bytes: &[u8]) -> Value {
    let document = bytes.strip_suffix(b"\n").unwrap_or(bytes);
    serde_json::from_slice(document).expect("JSON line")
}

fn schema_accepts(kind: PrivateSuccessorSchemaKind, value: &Value) -> bool {
    validate_private_successor_schema(kind, &serde_json::to_vec(value).expect("schema transport"))
        .is_ok()
}

fn wrong_type(value: &Value) -> Value {
    match value {
        Value::Null => json!(false),
        Value::Bool(_) => json!({}),
        Value::Number(_) => json!("wrong"),
        Value::String(_) => json!({}),
        Value::Array(_) => json!(false),
        Value::Object(_) => json!("wrong"),
    }
}

fn schema_target<'a>(
    bases: &'a BTreeMap<&str, Value>,
    id: &str,
) -> (PrivateSuccessorSchemaKind, &'a Value) {
    let (target, base_key) = if id.starts_with("schema.frontend_diagnostic_v2.") {
        (
            PrivateSuccessorSchemaKind::FrontendDiagnostic,
            "frontend_diagnostic_v2",
        )
    } else if id.starts_with("schema.frontend_source_artifacts_v2.") {
        (
            PrivateSuccessorSchemaKind::FrontendSourceArtifacts,
            "frontend_source_artifacts_v2",
        )
    } else if id.starts_with("schema.frontend_success_v2.") {
        (
            PrivateSuccessorSchemaKind::FrontendSuccess,
            "frontend_success_v2",
        )
    } else if id.starts_with("schema.nested_diagnostic_entry_v2.") {
        (
            PrivateSuccessorSchemaKind::DiagnosticEntry,
            "nested_diagnostic_entry_v2",
        )
    } else {
        (
            PrivateSuccessorSchemaKind::DiagnosticRequestLinkage,
            "union_frontend_diagnostic_request_linkage",
        )
    };
    let base = if target == PrivateSuccessorSchemaKind::DiagnosticRequestLinkage
        && id.contains(".unvalidated.")
    {
        &bases["union_frontend_diagnostic_request_linkage.unvalidated"]
    } else {
        &bases[base_key]
    };
    (target, base)
}

fn execute_schema_vector(vector: &Value, bases: &BTreeMap<&str, Value>) -> bool {
    let id = vector["id"].as_str().expect("schema vector id");
    let (target, base) = schema_target(bases, id);
    if id.ends_with(".duplicate_key") {
        let raw = vector["inputs"]["raw_utf8"]
            .as_str()
            .expect("duplicate raw bytes");
        return validate_private_successor_schema(target, raw.as_bytes()).is_err();
    }
    if id.ends_with(".valid") {
        return schema_accepts(target, base);
    }
    if id.ends_with(".missing_field") {
        return base
            .as_object()
            .expect("schema object")
            .keys()
            .all(|field| {
                let mut changed = base.clone();
                changed.as_object_mut().unwrap().remove(field);
                !schema_accepts(target, &changed)
            });
    }
    if id.ends_with(".unknown_field") {
        let mut changed = base.clone();
        changed["future"] = json!(true);
        return !schema_accepts(target, &changed);
    }
    if id.ends_with(".wrong_field_type") {
        return base
            .as_object()
            .expect("schema object")
            .keys()
            .all(|field| {
                let mut changed = base.clone();
                changed[field] = wrong_type(&base[field]);
                !schema_accepts(target, &changed)
            });
    }
    if id.ends_with(".later_version") {
        let mut changed = base.clone();
        changed["schema"] = json!(format!(
            "{}.v3",
            base["schema"].as_str().unwrap().trim_end_matches(".v2")
        ));
        return !schema_accepts(target, &changed);
    }
    if id.ends_with(".unknown_tag") {
        let mut changed = base.clone();
        changed["state"] = json!("future");
        return !schema_accepts(target, &changed);
    }
    panic!("unhandled schema vector {id}")
}

fn schema_bases(fixture: &DiagnosticFixture) -> BTreeMap<&'static str, Value> {
    let diagnostic = parse_line(&emitted_diagnostic(
        fixture,
        &[PracticalDiagnosticFamily::Protocol],
    ));
    let unvalidated = parse_line(
        &emit_csharp_practical_frontend_diagnostic(
            fixture.request.canonical_bytes(),
            None,
            &[PracticalDiagnosticFinding {
                family: PracticalDiagnosticFamily::Protocol,
                location: None,
            }],
        )
        .expect("unvalidated diagnostic"),
    );
    let context = serde_json::to_value(fixture.request.semantic_request().semantic_context())
        .expect("successor context JSON");
    let reference = |schema: &str| {
        json!({
            "schema": schema,
            "sha256": "1".repeat(64),
            "canonical_bytes": 1,
        })
    };
    let artifacts = json!({
        "schema": SUCCESSOR_SOURCE_ARTIFACTS_SCHEMA,
        "semantic_context": context,
        "selection_sha256": fixture.request.semantic_request().selection()["selection_sha256"],
        "vir": reference(SUCCESSOR_VIR_SCHEMA),
        "source_map": reference(SUCCESSOR_SOURCE_MAP_SCHEMA),
        "source_manifest": reference(SUCCESSOR_FRONTEND_MANIFEST_SCHEMA),
        "semantic_bindings": reference(SUCCESSOR_SEMANTIC_BINDINGS_SCHEMA),
        "closed_instances": reference(SUCCESSOR_CLOSED_INSTANCES_SCHEMA),
        "foundation_descriptor": foundation_descriptor(),
        "boundary_contracts": [],
        "transition_contracts": [],
        "artifacts_sha256": "2".repeat(64),
    });
    let success = json!({
        "schema": SUCCESSOR_FRONTEND_SUCCESS_SCHEMA,
        "request_sha256": fixture.request.request_sha256(),
        "semantic_context": artifacts["semantic_context"],
        "artifacts": artifacts,
        "success_sha256": "3".repeat(64),
    });
    BTreeMap::from([
        ("frontend_diagnostic_v2", diagnostic.clone()),
        ("frontend_source_artifacts_v2", success["artifacts"].clone()),
        ("frontend_success_v2", success),
        (
            "nested_diagnostic_entry_v2",
            diagnostic["diagnostics"][0].clone(),
        ),
        (
            "union_frontend_diagnostic_request_linkage",
            diagnostic["request_linkage"].clone(),
        ),
        (
            "union_frontend_diagnostic_request_linkage.unvalidated",
            unvalidated["request_linkage"].clone(),
        ),
    ])
}

fn execute_diagnostic_vector(vector: &Value, fixture: &DiagnosticFixture) -> bool {
    let id = vector["id"].as_str().expect("diagnostic vector id");
    match id {
        "diagnostic.forbidden_public_data" => {
            let valid = emitted_diagnostic(fixture, &[PracticalDiagnosticFamily::Protocol]);
            let changed = replace_once(
                &valid,
                CSHARP_PRACTICAL_PUBLIC_DIAGNOSTIC_MESSAGE,
                vector["inputs"]["message_contains"].as_str().unwrap(),
            );
            validate_practical_diagnostic(fixture, &changed, true)
                .is_err_and(|code| code == PracticalFrontendProtocolCode::PublicData)
        }
        "diagnostic.invalid_location" => {
            let location = &vector["inputs"]["location"];
            emit_csharp_practical_frontend_diagnostic(
                fixture.request.canonical_bytes(),
                Some(&fixture.request),
                &[PracticalDiagnosticFinding {
                    family: PracticalDiagnosticFamily::Protocol,
                    location: Some(PracticalDiagnosticLocation {
                        source_file_ordinal: location["source_file_ordinal"].as_u64().unwrap()
                            as u16,
                        start_byte: location["start_byte"].as_u64().unwrap() as u32,
                        end_byte: location["end_byte"].as_u64().unwrap() as u32,
                    }),
                }],
            )
            .is_err_and(|error| error.code() == PracticalFrontendProtocolCode::DiagnosticLocation)
        }
        "diagnostic.mixed_phase" => {
            let valid = emitted_diagnostic(fixture, &[PracticalDiagnosticFamily::Lowering]);
            let changed = replace_once(&valid, "\"phase\":8", "\"phase\":0");
            validate_practical_diagnostic(fixture, &changed, true)
                .is_err_and(|code| code == PracticalFrontendProtocolCode::DiagnosticPhase)
        }
        "diagnostic.phase_above" => {
            let valid = emitted_diagnostic(fixture, &[PracticalDiagnosticFamily::Lowering]);
            let changed = replace_once(&valid, "\"phase\":8", "\"phase\":9");
            validate_practical_diagnostic(fixture, &changed, true)
                .is_err_and(|code| code == PracticalFrontendProtocolCode::DiagnosticPhase)
        }
        "diagnostic.phase_min" | "diagnostic.phase_max" => {
            let expected = family(vector["inputs"]["code"].as_str().unwrap());
            let valid = emitted_diagnostic(fixture, &[expected]);
            validate_practical_diagnostic(fixture, &valid, true).is_ok_and(|accepted| {
                accepted.phase() == Some(expected.phase())
                    && accepted.diagnostics()[0].family() == expected
            })
        }
        _ if id.starts_with("diagnostic.precedence_") => {
            let failures = vector["inputs"]["failures"].as_array().unwrap();
            let findings = failures
                .iter()
                .map(|value| family(value.as_str().unwrap()))
                .collect::<Vec<_>>();
            let valid = emitted_diagnostic(fixture, &findings);
            let expected = vector["expected"]["primary"].as_str().unwrap();
            validate_practical_diagnostic(fixture, &valid, true)
                .is_ok_and(|accepted| accepted.diagnostics()[0].family().as_str() == expected)
        }
        _ => panic!("unhandled diagnostic vector {id}"),
    }
}

fn selected_hash(request: &Value) -> String {
    let selection = &request["semantic_request"]["selection"];
    selection["selection_sha256"]
        .as_str()
        .map(str::to_owned)
        .unwrap_or_else(|| sha256_raw_file_bytes(&canonical(selection)).to_hex())
}

fn frontend_linkage_accepts(result: &Value, request: &Value, request_validated: bool) -> bool {
    if result.get("artifacts").is_some() && result["schema"] == SUCCESSOR_FRONTEND_DIAGNOSTIC_SCHEMA
    {
        return false;
    }
    let expected_context = &request["semantic_request"]["semantic_context"];
    if result["schema"] == SUCCESSOR_FRONTEND_SUCCESS_SCHEMA {
        return result["request_sha256"] == request["request_sha256"]
            && result["semantic_context"] == *expected_context
            && result["artifacts"]["semantic_context"] == *expected_context
            && result["artifacts"]["selection_sha256"] == selected_hash(request)
            && schema_accepts(
                PrivateSuccessorSchemaKind::FrontendSourceArtifacts,
                &result["artifacts"],
            );
    }
    if result["schema"] != SUCCESSOR_FRONTEND_DIAGNOSTIC_SCHEMA {
        return false;
    }
    let linkage = &result["request_linkage"];
    if !request_validated {
        return linkage == &json!({"state":"unvalidated"});
    }
    linkage["state"] == "validated"
        && linkage["request_sha256"] == request["request_sha256"]
        && linkage["semantic_context"] == *expected_context
}

fn execute_linkage_vector(
    vector: &Value,
    success: &Value,
    diagnostic: &Value,
    unvalidated: &Value,
    request: &Value,
) -> bool {
    let id = vector["id"].as_str().expect("linkage vector id");
    match id {
        "frontend_linkage.success" => frontend_linkage_accepts(success, request, true),
        "frontend_linkage.success_context_mismatch" => {
            let mut changed = success.clone();
            changed["semantic_context"] = json!({});
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.success_request_mismatch" => {
            let mut changed = success.clone();
            changed["request_sha256"] = json!("4".repeat(64));
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.artifact_context_mismatch" => {
            let mut changed = success.clone();
            changed["artifacts"]["semantic_context"] = json!({});
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.artifact_selection_mismatch" => {
            let mut changed = success.clone();
            changed["artifacts"]["selection_sha256"] = json!("5".repeat(64));
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.diagnostic_partial_artifacts" => {
            let mut changed = diagnostic.clone();
            changed["artifacts"] = json!({});
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.diagnostic_unvalidated_after_validation" => {
            !frontend_linkage_accepts(unvalidated, request, true)
        }
        "frontend_linkage.diagnostic_unvalidated_before_validation" => {
            frontend_linkage_accepts(unvalidated, request, false)
        }
        "frontend_linkage.diagnostic_validated_context_mismatch" => {
            let mut changed = diagnostic.clone();
            changed["request_linkage"]["semantic_context"] = json!({});
            !frontend_linkage_accepts(&changed, request, true)
        }
        "frontend_linkage.diagnostic_validated_request_mismatch" => {
            let mut changed = diagnostic.clone();
            changed["request_linkage"]["request_sha256"] = json!("6".repeat(64));
            !frontend_linkage_accepts(&changed, request, true)
        }
        _ => panic!("unhandled linkage vector {id}"),
    }
}

fn execute_dispatch_vector(vector: &Value) -> bool {
    match vector["id"].as_str().unwrap() {
        "dispatch.scalar" => {
            select_private_csharp_producer(SuccessorCompiledSemanticProfile::CSharpScalarV0, false)
                == Ok(PrivateCSharpProducerRoute::ScalarV0)
        }
        "dispatch.practical" => {
            select_private_csharp_producer(
                SuccessorCompiledSemanticProfile::CSharpPracticalV1,
                false,
            ) == Ok(PrivateCSharpProducerRoute::PracticalV1)
        }
        "dispatch.ambient_override" => {
            select_private_csharp_producer(SuccessorCompiledSemanticProfile::CSharpScalarV0, true)
                .is_err_and(|error| error.code() == PredecessorMigrationCode::AmbientOverride)
        }
        "dispatch.unknown" => {
            select_private_csharp_producer(SuccessorCompiledSemanticProfile::GoFixedV0, false)
                .is_err_and(|error| error.code() == PredecessorMigrationCode::UnsupportedProfile)
        }
        other => panic!("unhandled dispatch vector {other}"),
    }
}

fn execute_limit_vector(vector: &Value) -> bool {
    let inputs = &vector["inputs"];
    let id = inputs["counter"].as_str().expect("limit counter");
    let maximum = inputs["inclusive_maximum"].as_u64().expect("limit maximum");
    let value = inputs["value"].as_u64().expect("limit value");
    retained_predecessor_limit(id).is_ok_and(|limit| limit.inclusive_maximum == maximum)
        && (validate_retained_predecessor_limit(id, value).is_ok()
            == (vector["expected"]["accept"] == true))
}

#[test]
fn csharp_03_t02_w08_executes_all_178_frozen_vectors() {
    let package = load(PACKAGE_PATH);
    let vectors = package["vectors"]
        .as_array()
        .expect("profile vectors")
        .iter()
        .filter(|vector| vector["implementation_owner"] == WORK_ITEM)
        .collect::<Vec<_>>();
    assert_eq!(vectors.len(), 178);
    assert!(vectors
        .iter()
        .all(|vector| vector["production_test_owner"] == OWNER));
    let counts = vectors.iter().fold(BTreeMap::new(), |mut counts, vector| {
        *counts
            .entry(vector["family"].as_str().expect("vector family"))
            .or_insert(0_usize) += 1;
        counts
    });
    assert_eq!(
        counts,
        BTreeMap::from([
            ("diagnostic", 34),
            ("dispatch", 4),
            ("frontend_linkage", 10),
            ("limit", 96),
            ("schema", 34),
        ])
    );
    assert_eq!(RETAINED_PREDECESSOR_LIMITS.len(), 32);
    assert_eq!(
        RETAINED_PREDECESSOR_LIMITS
            .iter()
            .map(|limit| limit.id)
            .collect::<BTreeSet<_>>()
            .len(),
        32
    );

    let fixture = diagnostic_fixture();
    let bases = schema_bases(&fixture);
    let request = parse_line(fixture.request.canonical_bytes());
    let success = &bases["frontend_success_v2"];
    let diagnostic = &bases["frontend_diagnostic_v2"];
    let unvalidated = parse_line(
        &emit_csharp_practical_frontend_diagnostic(
            fixture.request.canonical_bytes(),
            None,
            &[PracticalDiagnosticFinding {
                family: PracticalDiagnosticFamily::Protocol,
                location: None,
            }],
        )
        .expect("unvalidated diagnostic"),
    );
    for vector in vectors {
        let id = vector["id"].as_str().expect("vector id");
        let passed = match vector["family"].as_str().unwrap() {
            "diagnostic" => execute_diagnostic_vector(vector, &fixture),
            "dispatch" => execute_dispatch_vector(vector),
            "frontend_linkage" => {
                execute_linkage_vector(vector, success, diagnostic, &unvalidated, &request)
            }
            "limit" => execute_limit_vector(vector),
            "schema" => execute_schema_vector(vector, &bases),
            family => panic!("unexpected W08 vector family {family}"),
        };
        assert!(passed, "frozen W08 vector failed: {id}");
    }
}

fn artifact<'a>(case: &'a Value, kind: &str) -> &'a Value {
    case["artifacts"]
        .as_array()
        .expect("artifact descriptors")
        .iter()
        .find(|artifact| artifact["kind"] == kind)
        .unwrap_or_else(|| panic!("missing {kind} for {}", case["id"]))
}

fn checked_artifact(root: &str, descriptor: &Value) -> Vec<u8> {
    let path = descriptor["path"].as_str().expect("artifact path");
    let bytes = read(Path::new(root).join(path));
    assert_eq!(bytes.len() as u64, descriptor["bytes"].as_u64().unwrap());
    assert_eq!(
        sha256_raw_file_bytes(&bytes).to_hex(),
        descriptor["sha256"].as_str().unwrap()
    );
    bytes
}

fn assert_final_hash(artifact: &PrivateSuccessorArtifact, hash_field: &str, domain: &'static str) {
    let hash = artifact.sha256();
    let suffix = format!(",\"{hash_field}\":\"{hash}\"}}");
    assert!(
        artifact.canonical_bytes().ends_with(suffix.as_bytes()),
        "{} must end in its hash field",
        artifact.schema()
    );
    let mut preimage =
        artifact.canonical_bytes()[..artifact.canonical_bytes().len() - suffix.len()].to_vec();
    preimage.push(b'}');
    assert_eq!(
        hash_domain_separated_raw(HashDomain::new(domain), &preimage)
            .expect("artifact hash")
            .to_hex(),
        hash,
        "{} hash",
        artifact.schema()
    );
}

fn contains_string(value: &Value, needle: &str) -> bool {
    match value {
        Value::String(value) => value == needle,
        Value::Array(values) => values.iter().any(|value| contains_string(value, needle)),
        Value::Object(values) => values.values().any(|value| contains_string(value, needle)),
        Value::Null | Value::Bool(_) | Value::Number(_) => false,
    }
}

fn assert_common_migration(migration: &PrivatePredecessorMigration, producer: PredecessorProducer) {
    assert_eq!(migration.producer(), producer);
    assert_eq!(
        migration.request().schema(),
        SUCCESSOR_FRONTEND_REQUEST_SCHEMA
    );
    assert_final_hash(
        migration.request(),
        "request_sha256",
        "MPK-FRONTEND-REQUEST-2.0",
    );
    let mut expected_stdout = migration.frontend_result().canonical_bytes().to_vec();
    expected_stdout.push(b'\n');
    assert_eq!(migration.frontend_stdout(), expected_stdout);
    assert_eq!(
        migration
            .frontend_stdout()
            .iter()
            .filter(|byte| **byte == b'\n')
            .count(),
        1
    );
    assert_eq!(migration.equivalence().axiom_count(), 0);
    assert_eq!(migration.equivalence().practical_foundation_instances(), 0);
    for digest in [
        migration.equivalence().source_behavior_sha256(),
        migration.equivalence().obligation_sha256(),
        migration.equivalence().verdict_sha256(),
    ] {
        assert_eq!(digest.len(), 64);
        assert!(digest
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte)));
    }

    let request = parse_line(migration.request().canonical_bytes());
    assert_eq!(request["schema"], SUCCESSOR_FRONTEND_REQUEST_SCHEMA);
    assert_eq!(
        request["semantic_request"]["semantic_context"]["profile_registry"]["revision"],
        SUCCESSOR_CANDIDATE_REVISION
    );
    let result = parse_line(migration.frontend_result().canonical_bytes());
    for predecessor_schema in [
        "mpk.frontend.cli.v1",
        "mpk.vir.v1",
        "mpk.source_map.v1",
        "mpk.source_manifest.v1",
    ] {
        assert!(
            !contains_string(&result, predecessor_schema),
            "predecessor schema escaped: {predecessor_schema}"
        );
    }

    if let Some(artifacts) = migration.artifacts() {
        assert_eq!(
            migration.frontend_result().schema(),
            SUCCESSOR_FRONTEND_SUCCESS_SCHEMA
        );
        assert_eq!(result["request_sha256"], request["request_sha256"]);
        assert_eq!(
            result["semantic_context"],
            request["semantic_request"]["semantic_context"]
        );
        assert_eq!(
            result["artifacts"]["semantic_context"],
            result["semantic_context"]
        );
        assert!(schema_accepts(
            PrivateSuccessorSchemaKind::FrontendSourceArtifacts,
            &result["artifacts"],
        ));
        for (artifact, hash_field, domain, schema) in [
            (
                artifacts.vir(),
                "vir_sha256",
                "MPK-VIR-2.0",
                SUCCESSOR_VIR_SCHEMA,
            ),
            (
                artifacts.source_map(),
                "source_map_sha256",
                "MPK-SOURCE-MAP-2.0",
                SUCCESSOR_SOURCE_MAP_SCHEMA,
            ),
            (
                artifacts.source_manifest(),
                "manifest_sha256",
                "MPK-SOURCE-MANIFEST-2.0",
                SUCCESSOR_FRONTEND_MANIFEST_SCHEMA,
            ),
            (
                artifacts.semantic_bindings(),
                "binding_set_sha256",
                "MPK-CSHARP-SEMANTIC-BINDING-SET-1.0",
                SUCCESSOR_SEMANTIC_BINDINGS_SCHEMA,
            ),
            (
                artifacts.closed_instances(),
                "closed_set_sha256",
                "MPK-CSHARP-CLOSED-INSTANCES-1.0",
                SUCCESSOR_CLOSED_INSTANCES_SCHEMA,
            ),
            (
                artifacts.source_artifacts(),
                "artifacts_sha256",
                "MPK-FRONTEND-SOURCE-ARTIFACTS-2.0",
                SUCCESSOR_SOURCE_ARTIFACTS_SCHEMA,
            ),
        ] {
            assert_eq!(artifact.schema(), schema);
            assert_final_hash(artifact, hash_field, domain);
        }
        assert_final_hash(
            migration.frontend_result(),
            "success_sha256",
            "MPK-FRONTEND-SUCCESS-2.0",
        );
        let closed = parse_line(artifacts.closed_instances().canonical_bytes());
        assert_eq!(closed["instances"], json!([]));
        assert_eq!(closed["semantic_profile"], producer.semantic_profile());
    } else {
        assert_eq!(
            migration.frontend_result().schema(),
            SUCCESSOR_FRONTEND_DIAGNOSTIC_SCHEMA
        );
        assert_final_hash(
            migration.frontend_result(),
            "diagnostic_sha256",
            "MPK-FRONTEND-DIAGNOSTIC-2.0",
        );
        assert_eq!(result["status"], "rejected");
        assert!(result.get("artifacts").is_none());
        assert_eq!(result["request_linkage"]["state"], "validated");
        assert_eq!(
            result["request_linkage"]["request_sha256"],
            request["request_sha256"]
        );
        assert_eq!(
            result["raw_request_sha256"],
            sha256_raw_file_bytes(migration.request().canonical_bytes()).to_hex()
        );
        assert_eq!(
            result["raw_request_size_bytes"],
            migration.request().canonical_bytes().len() as u64
        );
    }
}

struct SyntheticFailure<'a> {
    status: &'a str,
    phase: &'a str,
    code: &'a str,
    message: &'a str,
}

fn synthetic_failure(
    registry: &ValidatedSemanticProfileRegistry,
    context: &Value,
    selection: &Value,
    failure: SyntheticFailure<'_>,
    captured: &[CapturedInput<'_>],
) -> AcceptedSuccessorFrontendEnvelope {
    let issue = json!({"code": failure.code, "message": failure.message});
    let rejected = failure.status == "rejected";
    let envelope = json!({
        "schema": "mpk.frontend.cli.v1",
        "status": failure.status,
        "phase": failure.phase,
        "semantic_context": context,
        "selection": selection,
        "rejected_features": if rejected { vec![issue.clone()] } else { Vec::new() },
        "diagnostics": if rejected { Vec::new() } else { vec![issue] },
    });
    validate_predecessor(registry, &envelope, captured, &[])
}

#[test]
fn csharp_03_t02_w08_migrates_the_complete_real_go_corpus_twice() {
    let active = active_registry();
    let candidate = candidate_registry();
    let index = load(format!("{GO_ROOT}/frontend-index.json"));
    assert_eq!(index["positive_source_count"], 13);
    assert_eq!(index["negative_source_count"], 8);
    assert_eq!(index["deterministic_runs"], 2);

    let mut positive_ids = BTreeSet::new();
    for case in index["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        assert!(positive_ids.insert(id));
        let envelope_bytes = checked_artifact(GO_ROOT, artifact(case, "frontend_envelope"));
        let envelope: Value = serde_json::from_slice(&envelope_bytes).unwrap();
        let manifest_bytes = checked_artifact(GO_ROOT, artifact(case, "source_manifest_frontend"));
        let manifest: Value = serde_json::from_slice(&manifest_bytes).unwrap();
        let map_bytes = checked_artifact(GO_ROOT, artifact(case, "source_map"));
        let source_map: Value = serde_json::from_slice(&map_bytes).unwrap();
        let storage = captured_storage(case["source_root"].as_str().unwrap(), &manifest);
        let captured = captured_refs(&storage);
        let permissions = go_synthetic_permissions(&source_map);
        let predecessor = validate_predecessor(&active, &envelope, &captured, &permissions);
        let request = candidate_request(
            &candidate,
            &envelope["semantic_context"],
            &envelope["selection"],
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: first migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: second migration: {error}"));
        assert_eq!(first, second, "{id}: two-run artifact equality");
        assert_common_migration(&first, PredecessorProducer::Go);
    }
    assert_eq!(positive_ids.len(), 13);

    let mut negative_ids = BTreeSet::new();
    for case in index["negative_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        assert!(negative_ids.insert(id));
        let envelope_bytes = checked_artifact(GO_ROOT, &case["artifact"]);
        let envelope: Value = serde_json::from_slice(&envelope_bytes).unwrap();
        let source_path = case["source_path"].as_str().unwrap();
        let source_bytes = read(Path::new(case["source_root"].as_str().unwrap()).join(source_path));
        let captured = [CapturedInput {
            kind: InputKind::Source,
            normalized_path: source_path,
            bytes: &source_bytes,
        }];
        let predecessor = validate_predecessor(&active, &envelope, &captured, &[]);
        let request = candidate_request(
            &candidate,
            &envelope["semantic_context"],
            &envelope["selection"],
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: first rejection migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: second rejection migration: {error}"));
        assert_eq!(first, second, "{id}: two-run rejection equality");
        assert!(first.artifacts().is_none());
        assert_common_migration(&first, PredecessorProducer::Go);
    }
    assert_eq!(negative_ids.len(), 8);
}

#[test]
fn csharp_03_t02_w08_migrates_the_complete_real_rust_corpus_twice() {
    let active = active_registry();
    let candidate = candidate_registry();
    let index = load(format!("{RUST_ROOT}/frontend-index.json"));
    assert_eq!(index["cases"].as_array().unwrap().len(), 13);
    assert_eq!(index["deterministic_runs"], 2);

    for case in index["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        let envelope_bytes = checked_artifact(RUST_ROOT, artifact(case, "frontend_envelope"));
        let envelope: Value = serde_json::from_slice(&envelope_bytes).unwrap();
        let manifest_bytes =
            checked_artifact(RUST_ROOT, artifact(case, "source_manifest_frontend"));
        let manifest: Value = serde_json::from_slice(&manifest_bytes).unwrap();
        let storage = captured_storage(case["source_root"].as_str().unwrap(), &manifest);
        let captured = captured_refs(&storage);
        let predecessor = validate_predecessor(&active, &envelope, &captured, &[]);
        let request = candidate_request(
            &candidate,
            &envelope["semantic_context"],
            &envelope["selection"],
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: first migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: second migration: {error}"));
        assert_eq!(first, second, "{id}: two-run artifact equality");
        assert_common_migration(&first, PredecessorProducer::Rust);
    }

    let negative = load("fixtures/rust-basic/negative-diagnostics-v1.json");
    assert_eq!(negative["case_count"], 73);
    let exemplar = &index["cases"][0];
    let context = &exemplar["semantic_context"];
    let selection = &exemplar["selection"];
    let request = candidate_request(&candidate, context, selection);
    let mut ids = BTreeSet::new();
    for case in negative["cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        assert!(ids.insert(id));
        let predecessor = synthetic_failure(
            &active,
            context,
            selection,
            SyntheticFailure {
                status: case["status"].as_str().unwrap(),
                phase: case["phase"].as_str().unwrap(),
                code: case["code"].as_str().unwrap(),
                message: "Rust frontend rejected the frozen case",
            },
            &[],
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &[])
            .unwrap_or_else(|error| panic!("{id}: first rejection migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &[])
            .unwrap_or_else(|error| panic!("{id}: second rejection migration: {error}"));
        assert_eq!(first, second, "{id}: two-run rejection equality");
        assert!(first.artifacts().is_none());
        assert_common_migration(&first, PredecessorProducer::Rust);
    }
    assert_eq!(ids.len(), 73);
}

fn active_context(profile: &str, parameters: &Value) -> Value {
    let registry = load(ACTIVE_REGISTRY_PATH);
    predecessor_context(&registry, profile, parameters)
}

fn predecessor_context(registry: &Value, profile: &str, parameters: &Value) -> Value {
    let entry = registry["profiles"]
        .as_array()
        .unwrap()
        .iter()
        .find(|entry| entry["semantic_profile"] == profile)
        .unwrap_or_else(|| panic!("missing active profile {profile}"));
    json!({
        "profile_registry": {
            "schema": registry["schema"],
            "id": registry["id"],
            "revision": registry["revision"],
            "registry_sha256": registry["registry_sha256"],
        },
        "profile_entry_sha256": entry["entry_sha256"],
        "source_language": entry["source_language"],
        "semantic_profile": entry["semantic_profile"],
        "semantic_parameters": parameters,
    })
}

fn scalar_baseline_storage(profile: &Value) -> Vec<OwnedCapturedInput> {
    profile["case_harness"]["baseline_files"]
        .as_object()
        .unwrap()
        .iter()
        .map(|(path, value)| {
            let (kind, bytes) = if path.ends_with(".json") {
                (InputKind::Contract, canonical_line(value))
            } else {
                (
                    InputKind::Source,
                    value.as_str().expect("baseline source").as_bytes().to_vec(),
                )
            };
            OwnedCapturedInput {
                kind,
                normalized_path: path.clone(),
                bytes,
            }
        })
        .collect()
}

fn csharp_message(status: &str, code: &str) -> &'static str {
    if code == "CSHARP_SOURCE_DIAGNOSTIC" {
        "C# compiler diagnostic CS0103"
    } else if code.starts_with("CSHARP_LIMIT_") {
        "C# profile limit exceeded"
    } else {
        match status {
            "source-error" => "C# source is invalid",
            "rejected" => "C# source is outside the frozen profile",
            "frontend-error" => "C# frontend failed closed",
            other => panic!("unexpected C# failure status {other}"),
        }
    }
}

fn java_message(status: &str, code: &str) -> &'static str {
    if code.starts_with("JAVA_LIMIT_") {
        "Java profile limit exceeded"
    } else {
        match status {
            "source-error" => "Java source is invalid",
            "rejected" => "Java source is outside the frozen profile",
            "frontend-error" => "Java frontend failed closed",
            other => panic!("unexpected Java failure status {other}"),
        }
    }
}

#[test]
fn csharp_03_t02_w08_binds_complete_scalar_csharp_corpus_and_migrates_all_rejections() {
    let profile = load("develop/specs/vectors/csharp-profile-v0.json");
    assert_eq!(profile["accepted_cases"].as_array().unwrap().len(), 30);
    assert_eq!(profile["rejected_cases"].as_array().unwrap().len(), 88);
    let active = active_registry();
    let candidate = candidate_registry();
    let context = active_context("mpk.csharp.scalar.v0", &profile["semantic_parameters"]);
    let selection = &profile["case_harness"]["baseline_selection"];
    let request = candidate_request(&candidate, &context, selection);
    let storage = scalar_baseline_storage(&profile);
    let captured = captured_refs(&storage);
    let mut ids = BTreeSet::new();
    for case in profile["rejected_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        assert!(ids.insert(id));
        let expected = &case["expect"];
        let status = expected["status"].as_str().unwrap();
        let code = expected["code"].as_str().unwrap();
        let predecessor = synthetic_failure(
            &active,
            &context,
            selection,
            SyntheticFailure {
                status,
                phase: expected["phase"].as_str().unwrap(),
                code,
                message: csharp_message(status, code),
            },
            &captured,
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: first rejection migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: second rejection migration: {error}"));
        assert_eq!(first, second, "{id}: two-run rejection equality");
        assert!(first.artifacts().is_none());
        assert_common_migration(&first, PredecessorProducer::CSharpScalar);
    }
    assert_eq!(ids.len(), 88);
    assert_eq!(
        profile["accepted_cases"]
            .as_array()
            .unwrap()
            .iter()
            .map(|case| case["id"].as_str().unwrap())
            .collect::<BTreeSet<_>>()
            .len(),
        30
    );
}

#[test]
fn csharp_03_t02_w08_binds_complete_java_corpus_and_migrates_all_rejections() {
    let profile = load("develop/specs/vectors/java-profile-v0.json");
    assert_eq!(profile["accepted_cases"].as_array().unwrap().len(), 49);
    assert_eq!(profile["rejected_cases"].as_array().unwrap().len(), 99);
    let active = active_registry();
    let candidate = candidate_registry();
    let context = &profile["semantic_context_fixture"];
    let selection = &profile["selection_fixture"];
    let request = candidate_request(&candidate, context, selection);
    let storage = scalar_baseline_storage(&profile);
    let captured = captured_refs(&storage);
    let mut ids = BTreeSet::new();
    for case in profile["rejected_cases"].as_array().unwrap() {
        let id = case["id"].as_str().unwrap();
        assert!(ids.insert(id));
        let status = case["expected_status"].as_str().unwrap();
        let code = case["expected_code"].as_str().unwrap();
        let predecessor = synthetic_failure(
            &active,
            context,
            selection,
            SyntheticFailure {
                status,
                phase: case["expected_phase"].as_str().unwrap(),
                code,
                message: java_message(status, code),
            },
            &captured,
        );
        let first = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: first rejection migration: {error}"));
        let second = migrate_predecessor_frontend(&request, &predecessor, &captured)
            .unwrap_or_else(|error| panic!("{id}: second rejection migration: {error}"));
        assert_eq!(first, second, "{id}: two-run rejection equality");
        assert!(first.artifacts().is_none());
        assert_common_migration(&first, PredecessorProducer::Java);
    }
    assert_eq!(ids.len(), 99);
    assert_eq!(
        profile["accepted_cases"]
            .as_array()
            .unwrap()
            .iter()
            .map(|case| case["id"].as_str().unwrap())
            .collect::<BTreeSet<_>>()
            .len(),
        49
    );
}

struct DifferenceReportCase {
    report: &'static str,
    language: &'static str,
    profile: &'static str,
    accepted_source: &'static str,
    accepted_array: &'static str,
    accepted_count: u64,
    accepted_ids_sha256: &'static str,
    rejected_source: &'static str,
    rejected_array: &'static str,
    rejected_count: u64,
    rejected_ids_sha256: &'static str,
}

fn case_ids_sha256(source: &Value, field: &str) -> String {
    let ids = source[field]
        .as_array()
        .unwrap_or_else(|| panic!("{field} array"))
        .iter()
        .map(|case| case["id"].clone())
        .collect::<Vec<_>>();
    sha256_raw_file_bytes(&serde_json::to_vec(&ids).expect("case ID transport")).to_hex()
}

fn assert_test_owner_exists(owner: &str) {
    let (path, test) = owner.split_once('#').expect("path#test owner");
    let source = String::from_utf8(read(path)).expect("UTF-8 test owner");
    let test = if test.starts_with("CSHARP-") {
        test.to_ascii_lowercase().replace('-', "_")
    } else {
        test.to_owned()
    };
    assert!(
        source.contains(&format!("fn {test}")),
        "missing test owner {owner}"
    );
}

#[test]
fn csharp_03_t02_w08_validates_all_four_semantic_difference_reports() {
    let cases = [
        DifferenceReportCase {
            report:
                "develop/migrations/csharp-03/predecessor-producer-csharp-scalar-difference.json",
            language: "csharp",
            profile: "mpk.csharp.scalar.v0",
            accepted_source: "develop/specs/vectors/csharp-profile-v0.json",
            accepted_array: "accepted_cases",
            accepted_count: 30,
            accepted_ids_sha256: "6cd6e506265a9927280ab2435262c9f970d1168d3d28e97f61c21c4181282b80",
            rejected_source: "develop/specs/vectors/csharp-profile-v0.json",
            rejected_array: "rejected_cases",
            rejected_count: 88,
            rejected_ids_sha256: "70e9ad33d258606e99d3231f62aa18147157b87d410eebc5e16080694ac518e2",
        },
        DifferenceReportCase {
            report: "develop/migrations/csharp-03/predecessor-producer-go-difference.json",
            language: "go",
            profile: "mpk.go.fixed.v0",
            accepted_source: "fixtures/vir-go/frontend-index.json",
            accepted_array: "cases",
            accepted_count: 13,
            accepted_ids_sha256: "8e06b6617d0f6e635b8ed11d24921889bf5b31ea386eea9887fae5e9233af287",
            rejected_source: "fixtures/vir-go/frontend-index.json",
            rejected_array: "negative_cases",
            rejected_count: 8,
            rejected_ids_sha256: "6f6662344f5313d2e41b6ecb78491161387ed3967e8ac574d4c130df6975d1ee",
        },
        DifferenceReportCase {
            report: "develop/migrations/csharp-03/predecessor-producer-java-difference.json",
            language: "java",
            profile: "mpk.java.scalar.v0",
            accepted_source: "develop/specs/vectors/java-profile-v0.json",
            accepted_array: "accepted_cases",
            accepted_count: 49,
            accepted_ids_sha256: "fdd9fd37a60009bdead68e47240b9dfeee94a9ad1fd772513c094eec8fcd0849",
            rejected_source: "develop/specs/vectors/java-profile-v0.json",
            rejected_array: "rejected_cases",
            rejected_count: 99,
            rejected_ids_sha256: "98a218ccd4fe38a29c8e5052df17046c9be040e7ba4fbe2e7f788dfd92490168",
        },
        DifferenceReportCase {
            report: "develop/migrations/csharp-03/predecessor-producer-rust-difference.json",
            language: "rust",
            profile: "mpk.rust.checked.v0",
            accepted_source: "fixtures/rust-basic/positive/frontend-index.json",
            accepted_array: "cases",
            accepted_count: 13,
            accepted_ids_sha256: "f0a8c8a0571180bea5121b4d0282a3a981e04f571a0403215565b0c5a11ef189",
            rejected_source: "fixtures/rust-basic/negative-diagnostics-v1.json",
            rejected_array: "cases",
            rejected_count: 73,
            rejected_ids_sha256: "d3d044a9b9b5b6e3c1c6c779da2152246ba2357988d6bc62238e68cef3afb35f",
        },
    ];

    let mut languages = BTreeSet::new();
    for case in cases {
        assert!(languages.insert(case.language));
        let report = load(case.report);
        assert_eq!(
            report["schema"],
            "mpk.csharp_practical.predecessor_producer_difference.v1"
        );
        assert_eq!(report["work_item"], WORK_ITEM);
        assert_eq!(report["source_language"], case.language);
        assert_eq!(report["semantic_profile"], case.profile);
        assert_eq!(
            report["predecessor_artifacts"]["frontend"],
            "mpk.frontend.cli.v1"
        );
        assert_eq!(report["predecessor_artifacts"]["vir"], "mpk.vir.v1");
        assert_eq!(
            report["successor_artifacts"]["frontend_success"],
            SUCCESSOR_FRONTEND_SUCCESS_SCHEMA
        );
        assert_eq!(
            report["successor_artifacts"]["frontend_diagnostic"],
            SUCCESSOR_FRONTEND_DIAGNOSTIC_SCHEMA
        );
        assert_eq!(
            report["successor_artifacts"]["source_artifacts"],
            SUCCESSOR_SOURCE_ARTIFACTS_SCHEMA
        );
        assert_eq!(report["successor_artifacts"]["vir"], SUCCESSOR_VIR_SCHEMA);

        let accepted = load(case.accepted_source);
        let rejected = if case.accepted_source == case.rejected_source {
            accepted.clone()
        } else {
            load(case.rejected_source)
        };
        assert_eq!(
            accepted[case.accepted_array].as_array().unwrap().len() as u64,
            case.accepted_count
        );
        assert_eq!(
            rejected[case.rejected_array].as_array().unwrap().len() as u64,
            case.rejected_count
        );
        assert_eq!(
            case_ids_sha256(&accepted, case.accepted_array),
            case.accepted_ids_sha256
        );
        assert_eq!(
            case_ids_sha256(&rejected, case.rejected_array),
            case.rejected_ids_sha256
        );
        assert_eq!(report["corpus"]["accepted_case_count"], case.accepted_count);
        assert_eq!(
            report["corpus"]["accepted_case_ids_sha256"],
            case.accepted_ids_sha256
        );
        assert_eq!(report["corpus"]["rejected_case_count"], case.rejected_count);
        assert_eq!(
            report["corpus"]["rejected_case_ids_sha256"],
            case.rejected_ids_sha256
        );

        let expected_accepted_raw = sha256_raw_file_bytes(&read(case.accepted_source)).to_hex();
        let expected_rejected_raw = sha256_raw_file_bytes(&read(case.rejected_source)).to_hex();
        if case.accepted_source == case.rejected_source {
            assert_eq!(report["corpus"]["source"], case.accepted_source);
            assert_eq!(report["corpus"]["source_raw_sha256"], expected_accepted_raw);
        } else {
            assert_eq!(report["corpus"]["accepted_source"], case.accepted_source);
            assert_eq!(
                report["corpus"]["accepted_source_raw_sha256"],
                expected_accepted_raw
            );
            assert_eq!(report["corpus"]["rejected_source"], case.rejected_source);
            assert_eq!(
                report["corpus"]["rejected_source_raw_sha256"],
                expected_rejected_raw
            );
        }

        assert_eq!(
            report["execution"]["private_adapter"],
            "crates/mpk-cli/src/csharp_practical_migration.rs"
        );
        assert_eq!(report["execution"]["owner"], OWNER);
        assert_eq!(report["execution"]["two_run_artifact_equality"], true);
        assert_eq!(report["execution"]["public_format_selector"], false);
        assert_eq!(report["execution"]["installed_route"], false);
        assert_test_owner_exists(report["execution"]["owner"].as_str().unwrap());
        assert_test_owner_exists(
            report["execution"]["interpreter_vc_checker_owner"]
                .as_str()
                .unwrap(),
        );
        if let Some(owner) = report["execution"]["real_frontend_owner"].as_str() {
            assert_test_owner_exists(owner);
        }
        if let Some(path) = report["execution"]["baseline_difference_report"].as_str() {
            assert_eq!(
                report["execution"]["baseline_difference_report_raw_sha256"],
                sha256_raw_file_bytes(&read(path)).to_hex()
            );
        }
        for field in [
            "source_behavior_changes",
            "obligation_changes",
            "verdict_changes",
            "axiom_inventory_changes",
            "practical_foundation_instances",
        ] {
            assert_eq!(report["comparison"][field], 0, "{} {field}", case.language);
        }
        assert_eq!(
            report["comparison"]["certificate_format"],
            "mpk-certificate-v0"
        );
    }
    assert_eq!(languages, BTreeSet::from(["csharp", "go", "java", "rust"]));
}

#[test]
fn csharp_03_t02_w08_has_no_public_format_selector_or_installed_route() {
    let migration = String::from_utf8(read("crates/mpk-cli/src/csharp_practical_migration.rs"))
        .expect("migration source");
    for forbidden in [
        "--frontend-format",
        "--artifact-version",
        "--legacy",
        "MPK_FRONTEND_FORMAT",
        "MPK_ARTIFACT_VERSION",
    ] {
        assert!(
            !migration.contains(forbidden),
            "public selector {forbidden}"
        );
    }
    for routed_source in [
        "crates/mpk-cli/src/main.rs",
        "crates/mpk-cli/src/successor_cli.rs",
        "crates/mpk-cli/src/frontend_runner.rs",
        "crates/mpk-cli/src/java_frontend_runner.rs",
        "crates/mpk-cli/src/successor_frontend_runner.rs",
    ] {
        let source = String::from_utf8(read(routed_source)).expect("route source");
        assert!(
            !source.contains("migrate_predecessor_frontend")
                && !source.contains("csharp_practical_migration"),
            "W08 leaked into {routed_source}"
        );
    }

    let profile = load("develop/specs/vectors/csharp-profile-v0.json");
    let revision_two_vectors = load("develop/specs/vectors/semantic-profile-registry-v2.json");
    let revision_two_value = &revision_two_vectors["registry"];
    let revision_two = validate_semantic_profile_registry(
        &canonical_line(revision_two_value),
        RegistryRevision::Revision2,
    )
    .expect("historical revision-2 registry");
    let context = predecessor_context(
        revision_two_value,
        "mpk.csharp.scalar.v0",
        &profile["semantic_parameters"],
    );
    let selection = &profile["case_harness"]["baseline_selection"];
    let storage = scalar_baseline_storage(&profile);
    let captured = captured_refs(&storage);
    let rejection = &profile["rejected_cases"][0]["expect"];
    let status = rejection["status"].as_str().unwrap();
    let code = rejection["code"].as_str().unwrap();
    let predecessor = synthetic_failure(
        &revision_two,
        &context,
        selection,
        SyntheticFailure {
            status,
            phase: rejection["phase"].as_str().unwrap(),
            code,
            message: csharp_message(status, code),
        },
        &captured,
    );
    let candidate = candidate_registry();
    let request = candidate_request(&candidate, &context, selection);
    assert_eq!(
        migrate_predecessor_frontend(&request, &predecessor, &captured)
            .expect_err("historical predecessor registry must not migrate")
            .code(),
        PredecessorMigrationCode::IdentityMismatch
    );
}
