use std::fs;
use std::path::{Path, PathBuf};

use mpk_cert::encode::SourceManifest as CertificateSourceManifest;
use mpk_cert::{certificate_hash, decode_canonical_certificate, hash_hex};
use mpk_cli::policy_profile::lookup_strategy_registration;
use mpk_cli::policy_schema::{PolicyEvidenceV1, PolicyHelperArtifact, PolicyVerificationOptions};
use mpk_cli::program_certificate::{assemble_program_certificate_alpha, ProgramCertificateOutcome};
use mpk_cli::successor_policy::{
    generate_staged_successor_policy_scan, import_staged_successor_policy_scan_json,
    run_staged_successor_policy, SuccessorPolicyCode, SuccessorPolicyPhase,
    SuccessorPolicyScanSource, SuccessorPolicySource, SUCCESSOR_POLICY_EVIDENCE_SCHEMA,
    SUCCESSOR_POLICY_SCAN_SCHEMA, SUCCESSOR_PROGRAM_CERTIFICATE_PROFILE,
};
use mpk_vc::semantic_profile_registry::{
    validate_inactive_semantic_profile_registry, CompiledSemanticProfile, InactiveRegistryRevision,
    ValidatedSemanticProfileRegistry,
};
use mpk_vc::successor_source_artifacts::{
    import_successor_source_manifest_json, import_successor_source_map_json,
    import_successor_vir_json, successor_contract_hash_value, successor_source_manifest_hash_value,
    successor_source_map_hash_value, successor_vir_hash_value, SuccessorSourceManifestStage,
    SuccessorSourceManifestValidationContext, SuccessorSourceMapValidationContext,
    ValidatedSuccessorSourceManifest, ValidatedSuccessorSourceMap, ValidatedSuccessorVir,
};
use mpk_vc::successor_vc::{
    emit_successor_vc_skeleton, generate_successor_vc, SuccessorVcSource, ValidatedSuccessorVc,
    ValidatedSuccessorVcSkeleton,
};
use mpk_vc::{
    canonical_json_bytes, input_set_hash, parse_strict_json, sha256_raw_file_bytes, CapturedInput,
    InputEntry, InputKind, ReleaseRegistryIdentity, SemanticParameters, SemanticProfile,
    SourceReference, StrictJsonLimits, SyntheticPermission, VcDocument,
};
use serde_json::{json, Value};

const ZERO_SHA256: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";
const CSHARP_FUNCTION: &str = "Vector.RequiredChecks::Identity(i32)->i32";
const CSHARP_SOURCE: &[u8] = include_bytes!(
    "../../../develop/migrations/csharp-02-staging/policy/csharp/source/src/Required.cs"
);
const CSHARP_CONTRACT: &[u8] = include_bytes!(
    "../../../develop/migrations/csharp-02-staging/policy/csharp/source/contracts/identity.json"
);
const GO_SOURCE: &[u8] = b"package arith\n\nfunc Identity(x int64) int64 { return x }\n";
const UPDATE_FIXTURES_ENV: &str = "MPK_UPDATE_CSHARP_POLICY_FIXTURES";
const FIXTURE_ROOT: &str = "develop/migrations/csharp-02-staging/policy/csharp";

struct OwnedCapturedInput {
    kind: InputKind,
    normalized_path: String,
    bytes: Vec<u8>,
}

struct ValidatedSource {
    storage: Vec<OwnedCapturedInput>,
    vir: ValidatedSuccessorVir,
    source_map: ValidatedSuccessorSourceMap,
    manifest: ValidatedSuccessorSourceManifest,
}

struct GeneratedPair {
    vc: ValidatedSuccessorVc,
    skeleton: ValidatedSuccessorVcSkeleton,
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    fs::read(repository_root().join(relative.as_ref()))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.as_ref().display()))
}

fn load(relative: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&read(relative)).expect("checked-in JSON")
}

fn canonical(value: &Value) -> Vec<u8> {
    let encoded = serde_json::to_vec(value).expect("JSON serializes");
    let strict = parse_strict_json(
        &encoded,
        StrictJsonLimits::new(268_435_456, 268_435_456, 768, 1_048_576),
    )
    .expect("strict JSON");
    canonical_json_bytes(&strict).expect("canonical JSON")
}

fn registry() -> ValidatedSemanticProfileRegistry {
    validate_inactive_semantic_profile_registry(
        &read("develop/migrations/csharp-02-staging/semantic-profile-registry.json"),
        InactiveRegistryRevision::Revision2,
    )
    .expect("revision-2 semantic registry")
}

fn input_kind(value: &Value) -> InputKind {
    match value.as_str().expect("input kind") {
        "source" => InputKind::Source,
        "contract" => InputKind::Contract,
        "build_manifest" => InputKind::BuildManifest,
        "lockfile" => InputKind::Lockfile,
        other => panic!("unknown input kind {other}"),
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = input_kind(&entry["kind"]);
            let normalized_path = entry["normalized_path"]
                .as_str()
                .expect("normalized input path")
                .to_owned();
            let path = repository_root().join(source_root).join(&normalized_path);
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match kind {
                    InputKind::BuildManifest if normalized_path == "Cargo.toml" => {
                        GENERATED_CARGO_TOML.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "Cargo.lock" => {
                        GENERATED_CARGO_LOCK.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "go.sum" => Vec::new(),
                    _ => panic!("read captured input {}: {error}", path.display()),
                },
                Err(error) => panic!("read captured input {}: {error}", path.display()),
            };
            assert_eq!(entry["size_bytes"], bytes.len() as u64);
            assert_eq!(entry["sha256"], sha256_raw_file_bytes(&bytes).to_hex());
            OwnedCapturedInput {
                kind,
                normalized_path,
                bytes,
            }
        })
        .collect()
}

fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.normalized_path,
            bytes: &input.bytes,
        })
        .collect()
}

fn staged_source(
    registry: &ValidatedSemanticProfileRegistry,
    artifact_root: &str,
    source_root: &str,
) -> ValidatedSource {
    let vir_bytes = read(format!("{artifact_root}/vir.json"));
    let map_bytes = read(format!("{artifact_root}/source-map.json"));
    let manifest_bytes = read(format!("{artifact_root}/source-manifest.frontend.json"));
    let manifest_value: Value = serde_json::from_slice(&manifest_bytes).expect("manifest JSON");
    let map_value: Value = serde_json::from_slice(&map_bytes).expect("source-map JSON");
    let storage = captured_storage(source_root, &manifest_value);
    let captured = captured_refs(&storage);
    let vir = import_successor_vir_json(&vir_bytes, registry).expect("successor VIR");
    let synthetic_permissions = map_value["entries"]
        .as_array()
        .expect("source-map entries")
        .iter()
        .filter(|entry| entry["origin"]["kind"] == "synthetic")
        .map(|entry| {
            let reason = entry["origin"]["reason"]
                .as_str()
                .expect("synthetic reason");
            assert_eq!(reason, "go.control_flow_join");
            SyntheticPermission {
                reference: serde_json::from_value::<SourceReference>(entry["reference"].clone())
                    .expect("synthetic reference"),
                reason: reason.to_owned(),
            }
        })
        .collect::<Vec<_>>();
    let source_map = import_successor_source_map_json(
        &map_bytes,
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &synthetic_permissions,
        },
    )
    .expect("successor source map");
    let release_registry = serde_json::from_value::<ReleaseRegistryIdentity>(
        manifest_value["release_registry"].clone(),
    )
    .expect("release-registry identity");
    let manifest = import_successor_source_manifest_json(
        &manifest_bytes,
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("successor source manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

fn csharp_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let context = load("develop/migrations/csharp-02-staging/csharp-bundle-candidate.json")
        ["tuples"][0]["semantic_context"]
        .clone();
    let i32_type = json!({"kind":"bv","width":32,"signed":true});
    let mut contract = json!({
        "semantic_context": context.clone(),
        "unit_id": "payment-policy",
        "function_id": CSHARP_FUNCTION,
        "requires": [],
        "ensures": [{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies": [],
        "panic": "forbidden",
        "termination": "total",
        "loops": [],
        "contract_hash": ZERO_SHA256
    });
    contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&contract)
            .expect("C# contract hash")
            .as_str()
            .to_owned(),
    );
    let mut vir = json!({
        "schema":"mpk.vir.v1",
        "semantic_context":context,
        "units":[{
            "id":"payment-policy",
            "name":"payment-policy",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":CSHARP_FUNCTION,
                "unit_id":"payment-policy",
                "name":"Identity",
                "params":[{"id":"arg0","type":i32_type.clone()}],
                "results":[{"id":"result0","type":i32_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":contract,
                "features_used":[]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir["vir_hash"] = Value::String(
        successor_vir_hash_value(&vir)
            .expect("C# VIR hash")
            .as_str()
            .to_owned(),
    );
    let vir = import_successor_vir_json(&canonical(&vir), registry).expect("C# successor VIR");

    let storage = vec![
        OwnedCapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/identity.json".to_owned(),
            bytes: CSHARP_CONTRACT.to_vec(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Required.cs".to_owned(),
            bytes: CSHARP_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"src/Required.cs",
            "start":0,
            "end":CSHARP_SOURCE.len()
        })
    };
    let mut source_map = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":[{
            "reference":{"kind":"function","unit_id":"payment-policy","function_id":CSHARP_FUNCTION},
            "origin":origin()
        },{
            "reference":{
                "kind":"terminator",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":"bb0"
            },
            "origin":origin()
        }],
        "source_map_hash":ZERO_SHA256
    });
    source_map["source_map_hash"] = Value::String(
        successor_source_map_hash_value(&source_map)
            .expect("C# source-map hash")
            .as_str()
            .to_owned(),
    );
    let source_map = import_successor_source_map_json(
        &canonical(&source_map),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("C# successor source map");

    let inputs = storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release_registry_value = load("develop/migrations/csharp-02-staging/bundle-registry.json");
    let release_registry = ReleaseRegistryIdentity {
        schema: release_registry_value["schema"]
            .as_str()
            .expect("release schema")
            .to_owned(),
        id: release_registry_value["id"]
            .as_str()
            .expect("release ID")
            .to_owned(),
        registry_sha256: release_registry_value["registry_sha256"]
            .as_str()
            .expect("release hash")
            .to_owned(),
    };
    let mut manifest = json!({
        "schema":"mpk.source_manifest.v1",
        "semantic_context":vir.module().semantic_context(),
        "selection":{
            "schema":"mpk.selection.csharp_methods.v0",
            "value":{
                "compilation":"payment-policy",
                "contracts":["contracts/identity.json"],
                "methods":[CSHARP_FUNCTION],
                "sources":["src/Required.cs"]
            }
        },
        "limit_profile":"mpk.vir.limits.v0",
        "release_registry":release_registry,
        "toolchain":{
            "bundle_id":"toolchain.csharp.roslyn-5_6_0.dotnet-10_0_11.candidate.v1",
            "distribution_sha256":"6cc7711334ffcd9216cfb241e1508491abb62a13b01ebc9b2d883a1ace9627bc",
            "components":[]
        },
        "frontend":{
            "bundle_id":"frontend.csharp.csharp2vir.candidate.v1",
            "name":"csharp2vir",
            "version":"0.1.0",
            "binary_sha256":"0783dc269c152ad1b13e77f42f9eff6f6891002c65890bc1445f2fe1a1a0410d",
            "subordinate_binaries":[]
        },
        "units":[{"identity":"payment-policy","name":"payment-policy","kind":"compilation"}],
        "target":{"id":"linux-x64","pointer_width":64},
        "inputs":inputs,
        "input_set_hash":input_set_hash(&inputs).expect("input-set hash").as_str(),
        "vir_hash":vir.hash().as_str(),
        "source_map_hash":source_map.hash().as_str(),
        "source_manifest_hash":ZERO_SHA256
    });
    manifest["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&manifest)
            .expect("C# source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("C# successor manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

fn go_identity_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let baseline = load(
        "develop/migrations/csharp-02-staging/go/frontend/basic-arith/source-manifest.frontend.json",
    );
    let context = baseline["semantic_context"].clone();
    let package = "github.com/finitefield-org/mpk/fixtures/go-basic/positive/arith";
    let function = format!("{package}.Identity");
    let i64_type = json!({"kind":"bv","width":64,"signed":true});
    let mut contract = json!({
        "semantic_context":context.clone(),
        "unit_id":package,
        "function_id":function,
        "requires":[],
        "ensures":[{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies":[],
        "panic":"forbidden",
        "termination":"total",
        "loops":[],
        "contract_hash":ZERO_SHA256
    });
    contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&contract)
            .expect("Go contract hash")
            .as_str()
            .to_owned(),
    );
    let mut vir = json!({
        "schema":"mpk.vir.v1",
        "semantic_context":context,
        "units":[{
            "id":package,
            "name":"arith",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":function,
                "unit_id":package,
                "name":"Identity",
                "params":[{"id":"arg0","type":i64_type.clone()}],
                "results":[{"id":"result0","type":i64_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":contract,
                "features_used":[]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir["vir_hash"] = Value::String(
        successor_vir_hash_value(&vir)
            .expect("Go VIR hash")
            .as_str()
            .to_owned(),
    );
    let vir = import_successor_vir_json(&canonical(&vir), registry).expect("Go successor VIR");

    let storage = vec![
        OwnedCapturedInput {
            kind: InputKind::BuildManifest,
            normalized_path: "go.mod".to_owned(),
            bytes: read("fixtures/go-basic/go.mod"),
        },
        OwnedCapturedInput {
            kind: InputKind::Lockfile,
            normalized_path: "go.sum".to_owned(),
            bytes: Vec::new(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "positive/arith/arith.go".to_owned(),
            bytes: GO_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"positive/arith/arith.go",
            "start":0,
            "end":GO_SOURCE.len()
        })
    };
    let mut source_map = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":[{
            "reference":{"kind":"function","unit_id":package,"function_id":function},
            "origin":origin()
        },{
            "reference":{
                "kind":"terminator",
                "unit_id":package,
                "function_id":function,
                "block":"bb0"
            },
            "origin":origin()
        }],
        "source_map_hash":ZERO_SHA256
    });
    source_map["source_map_hash"] = Value::String(
        successor_source_map_hash_value(&source_map)
            .expect("Go source-map hash")
            .as_str()
            .to_owned(),
    );
    let source_map = import_successor_source_map_json(
        &canonical(&source_map),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("Go successor source map");
    let inputs = storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release_registry =
        serde_json::from_value::<ReleaseRegistryIdentity>(baseline["release_registry"].clone())
            .expect("Go release-registry identity");
    let mut manifest = baseline;
    manifest["selection"]["value"]["function"] = Value::String(function);
    manifest["inputs"] = serde_json::to_value(&inputs).expect("Go inputs");
    manifest["input_set_hash"] = Value::String(
        input_set_hash(&inputs)
            .expect("Go input-set hash")
            .as_str()
            .to_owned(),
    );
    manifest["vir_hash"] = Value::String(vir.hash().as_str().to_owned());
    manifest["source_map_hash"] = Value::String(source_map.hash().as_str().to_owned());
    manifest["source_manifest_hash"] = Value::String(ZERO_SHA256.to_owned());
    manifest["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&manifest)
            .expect("Go source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("Go successor manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

fn profile_contract(profile: &str, field: &str) -> Value {
    match (profile, field) {
        ("go", "vc") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.vc.go_fixed.v0",
            "value":{
                "contract_profile_id":"mpk.go.contract.v0",
                "required_check_profile_id":"mpk.go.fixed.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        ("rust", "vc") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.vc.rust_checked.v0",
            "value":{
                "contract_profile_id":"mpk.rust.contract.v0",
                "required_check_profile_id":"mpk.rust.checked.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        ("go", "policy") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.policy.go_fixed.v0",
            "value":{
                "axiom_profile":"zero-axiom",
                "checker_profile":"mvp-strict",
                "strategy_profile":"payment-policy-alpha"
            }
        }),
        ("rust", "policy") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.policy.rust_checked.v0",
            "value":{
                "axiom_profile":"mvp-theory",
                "checker_profile":"mvp-strict",
                "strategy_profile":"payment-policy-rust-alpha"
            }
        }),
        ("go", "evidence") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.evidence.go_fixed.v0",
            "value":{
                "proof_authority":"certificate_only",
                "recipe_profile_id":"mpk.go.evidence_recipe.v0",
                "require_reference_checker":true,
                "require_source_free_check":true
            }
        }),
        ("rust", "evidence") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.evidence.rust_checked.v0",
            "value":{
                "proof_authority":"certificate_only",
                "recipe_profile_id":"mpk.rust.evidence_recipe.v0",
                "require_reference_checker":true,
                "require_source_free_check":true
            }
        }),
        ("csharp", field) => load("develop/specs/vectors/csharp-profile-v0.json")
            ["profile_contracts"]
            .as_array()
            .expect("C# profile contracts")
            .iter()
            .find(|contract| contract["field"] == field)
            .unwrap_or_else(|| panic!("missing C# {field} contract"))["envelope"]
            .clone(),
        other => panic!("unknown profile contract {other:?}"),
    }
}

fn generated_pair(
    registry: &ValidatedSemanticProfileRegistry,
    source: &ValidatedSource,
    vc_contract: &Value,
) -> GeneratedPair {
    let linked = SuccessorVcSource {
        registry,
        vir: &source.vir,
        manifest: &source.manifest,
        profile_contract: vc_contract,
    };
    let vc = generate_successor_vc(linked).expect("successor VC");
    let skeleton = emit_successor_vc_skeleton(&vc, linked).expect("successor skeleton");
    GeneratedPair { vc, skeleton }
}

fn source_boundary<'a>(
    registry: &'a ValidatedSemanticProfileRegistry,
    source: &'a ValidatedSource,
    pair: &'a GeneratedPair,
    policy_contract: &'a Value,
    evidence_contract: &'a Value,
    captured: &'a [CapturedInput<'a>],
) -> SuccessorPolicySource<'a> {
    SuccessorPolicySource {
        registry,
        vir: &source.vir,
        source_map: &source.source_map,
        frontend_manifest: &source.manifest,
        vc: &pair.vc,
        skeleton: &pair.skeleton,
        policy_contract,
        evidence_contract,
        captured_inputs: captured,
    }
}

fn fixture(relative: &str, generated: &[u8]) {
    let path = repository_root().join(FIXTURE_ROOT).join(relative);
    if std::env::var_os(UPDATE_FIXTURES_ENV).as_deref() == Some(std::ffi::OsStr::new("1")) {
        fs::create_dir_all(path.parent().expect("fixture parent")).expect("create fixture parent");
        fs::write(&path, generated).expect("write fixture");
    }
    assert_eq!(
        fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display())),
        generated,
        "fixture drift: {}",
        path.display()
    );
}

fn hex_fixture(bytes: &[u8]) -> Vec<u8> {
    let mut encoded = String::with_capacity(bytes.len() * 2 + 1);
    for byte in bytes {
        use std::fmt::Write;
        write!(&mut encoded, "{byte:02x}").expect("write to String");
    }
    encoded.push('\n');
    encoded.into_bytes()
}

#[test]
fn csharp_policy_reaches_identical_byte_dual_checker_certificate_and_closed_evidence() {
    let registry = registry();
    let source = csharp_source(&registry);
    let vc_contract = profile_contract("csharp", "vc");
    let policy_contract = profile_contract("csharp", "policy");
    let evidence_contract = profile_contract("csharp", "evidence");
    let pair = generated_pair(&registry, &source, &vc_contract);
    let captured = captured_refs(&source.storage);
    let boundary = source_boundary(
        &registry,
        &source,
        &pair,
        &policy_contract,
        &evidence_contract,
        &captured,
    );
    let options = PolicyVerificationOptions {
        strict: true,
        update_fixtures: false,
    };
    let first = run_staged_successor_policy(boundary, options.clone())
        .expect("C# successor policy verification");
    let second = run_staged_successor_policy(boundary, options)
        .expect("repeat C# successor policy verification");

    assert_eq!(
        first.scan().canonical_bytes(),
        second.scan().canonical_bytes()
    );
    assert_eq!(
        first.evidence().canonical_bytes(),
        second.evidence().canonical_bytes()
    );
    assert_eq!(
        first.scan().document().schema(),
        SUCCESSOR_POLICY_SCAN_SCHEMA
    );
    assert_eq!(
        first.evidence().document().schema(),
        SUCCESSOR_POLICY_EVIDENCE_SCHEMA
    );
    assert_eq!(
        first.evidence().document().program_certificate_profile(),
        SUCCESSOR_PROGRAM_CERTIFICATE_PROFILE
    );
    assert_eq!(
        first.registration().profile(),
        CompiledSemanticProfile::CSharpScalarV0
    );
    assert_eq!(
        first.registration().strategy_profile(),
        "payment-policy-csharp-alpha"
    );
    assert_eq!(first.registration().checker_profile(), "mvp-strict");
    assert_eq!(first.registration().axiom_profile(), "mvp-theory");
    assert_eq!(
        first.registration().recipe_profile_id(),
        "mpk.csharp.evidence_recipe.v0"
    );
    let expected_contract_helper = PolicyHelperArtifact::Contract {
        id: format!("contract:{CSHARP_FUNCTION}"),
        normalized_path: "contracts/identity.json".to_owned(),
        schema: "mpk.csharp.contract.v0".to_owned(),
        raw_input_sha256: sha256_raw_file_bytes(CSHARP_CONTRACT).to_hex(),
        function_id: CSHARP_FUNCTION.to_owned(),
        contract_hash: source.vir.module().units()[0].functions()[0]
            .contracts()
            .contract_hash()
            .as_str()
            .to_owned(),
    };
    assert!(first
        .scan()
        .document()
        .helper_artifacts()
        .contains(&expected_contract_helper));

    let ProgramCertificateOutcome::Candidate(candidate) = first.program_certificate() else {
        panic!("the reflexive C# obligation must produce a dual-accepted candidate");
    };
    assert_eq!(candidate.rust_report.axiom_count, 0);
    assert_eq!(candidate.reference_report.axiom_count, 0);
    let certificate_digest = hash_hex(&certificate_hash(&candidate.bytes));
    assert_eq!(
        hash_hex(&candidate.rust_report.certificate_hash),
        certificate_digest
    );
    assert_eq!(
        candidate.reference_report.certificate_hash,
        certificate_digest
    );
    assert_eq!(
        hash_hex(&candidate.rust_report.export_hash),
        candidate.reference_report.export_hash
    );
    assert_eq!(
        hash_hex(&candidate.rust_report.axiom_report_hash),
        candidate.reference_report.axiom_report_hash
    );
    let decoded = decode_canonical_certificate(&candidate.bytes).expect("Certificate v0 bytes");
    assert_eq!(decoded, candidate.certificate);
    assert!(decoded.imports.is_empty());
    assert!(decoded.theory_certificates.is_empty());
    assert_eq!(
        decoded
            .source_manifest
            .as_ref()
            .expect("certificate-stage manifest")
            .payload,
        first.certificate_manifest().canonical_bytes()
    );

    let trusted = first.evidence().document().trusted_evidence();
    assert_eq!(trusted.certificates.len(), 1);
    assert!(trusted.theory_certificates.is_empty());
    assert_eq!(trusted.checker_verdicts.len(), 2);
    assert!(trusted.checker_verdicts.iter().all(|verdict| {
        verdict.verdict == "accepted" && verdict.certificate_ids == ["program"]
    }));
    assert!(first
        .evidence()
        .document()
        .properties()
        .iter()
        .flat_map(|property| &property.members)
        .all(|member| {
            member.status == "mpk_verified"
                && member.evidence
                    == [
                        mpk_cli::policy_schema::PolicyEvidenceReferenceV1::CheckedDeclaration {
                            certificate_id: "program".to_owned(),
                        },
                    ]
        }));
    assert!(first
        .evidence()
        .document()
        .reproduction_recipes()
        .iter()
        .all(|recipe| {
            recipe.working_directory_role == "source_root"
                && recipe
                    .argv
                    .contains(&"--profile-registry-sha256".to_owned())
                && recipe.argv.contains(&"--profile-entry-sha256".to_owned())
                && recipe.argv.contains(&"--compilation".to_owned())
                && recipe.argv.contains(&"--method".to_owned())
                && recipe
                    .argv
                    .iter()
                    .all(|argument| !argument.starts_with('/'))
        }));

    let frontend: Value =
        serde_json::from_slice(source.manifest.canonical_bytes()).expect("frontend manifest");
    let mut certificate: Value =
        serde_json::from_slice(first.certificate_manifest().canonical_bytes())
            .expect("certificate manifest");
    let vc_hash = certificate
        .as_object_mut()
        .expect("manifest object")
        .remove("vc_hash")
        .expect("certificate VC hash");
    certificate
        .as_object_mut()
        .expect("manifest object")
        .remove("source_manifest_hash");
    let mut frontend_without_hash = frontend;
    frontend_without_hash
        .as_object_mut()
        .expect("manifest object")
        .remove("source_manifest_hash");
    assert_eq!(certificate, frontend_without_hash);
    assert_eq!(vc_hash, pair.vc.hash().as_str());

    fixture("scan.json", first.scan().canonical_bytes());
    fixture(
        "source-manifest.certificate.json",
        first.certificate_manifest().canonical_bytes(),
    );
    fixture("evidence.json", first.evidence().canonical_bytes());
    fixture("program-certificate.hex", &hex_fixture(&candidate.bytes));

    let mut old_scan = first.scan().canonical_bytes().to_vec();
    old_scan.push(b'\n');
    let error = first.import_scan_json(&old_scan).unwrap_err();
    assert_eq!(error.phase(), SuccessorPolicyPhase::CanonicalTransport);
    assert_eq!(error.code(), SuccessorPolicyCode::CanonicalTransport);

    let mut promoted: Value =
        serde_json::from_slice(first.evidence().canonical_bytes()).expect("evidence JSON");
    promoted["trusted_evidence"]["checker_verdicts"][0]["checker"] =
        Value::String("compiler".to_owned());
    let error = first
        .import_evidence_json(&canonical(&promoted))
        .unwrap_err();
    assert_eq!(error.phase(), SuccessorPolicyPhase::DocumentLinkage);
    assert_eq!(error.code(), SuccessorPolicyCode::DocumentLinkage);

    let mut predecessor: Value =
        serde_json::from_slice(first.evidence().canonical_bytes()).expect("evidence JSON");
    predecessor["schema"] = Value::String("mpk.policy.evidence.v1".to_owned());
    assert_eq!(
        first
            .import_evidence_json(&canonical(&predecessor))
            .unwrap_err()
            .code(),
        SuccessorPolicyCode::DocumentLinkage
    );
    assert!(
        serde_json::from_slice::<PolicyEvidenceV1>(first.evidence().canonical_bytes()).is_err()
    );

    let crossed_policy = profile_contract("go", "policy");
    let crossed = source_boundary(
        &registry,
        &source,
        &pair,
        &crossed_policy,
        &evidence_contract,
        &captured,
    );
    let error = run_staged_successor_policy(
        crossed,
        PolicyVerificationOptions {
            strict: true,
            update_fixtures: false,
        },
    )
    .unwrap_err();
    assert_eq!(error.phase(), SuccessorPolicyPhase::ProfileContract);
    assert_eq!(error.code(), SuccessorPolicyCode::ProfileContract);

    let crossed_evidence = profile_contract("go", "evidence");
    let crossed = source_boundary(
        &registry,
        &source,
        &pair,
        &policy_contract,
        &crossed_evidence,
        &captured,
    );
    let error = run_staged_successor_policy(
        crossed,
        PolicyVerificationOptions {
            strict: true,
            update_fixtures: false,
        },
    )
    .unwrap_err();
    assert_eq!(error.phase(), SuccessorPolicyPhase::ProfileContract);
    assert_eq!(error.code(), SuccessorPolicyCode::ProfileContract);
    assert!(lookup_strategy_registration("payment-policy-csharp-alpha").is_none());
}

#[test]
fn successor_scan_is_frontend_only_and_exactly_reimported() {
    let registry = registry();
    let source = staged_source(
        &registry,
        "develop/migrations/csharp-02-staging/go/frontend/basic-arith",
        "fixtures/go-basic",
    );
    let policy_contract = profile_contract("go", "policy");
    let captured = captured_refs(&source.storage);
    let boundary = SuccessorPolicyScanSource {
        registry: &registry,
        vir: &source.vir,
        source_map: &source.source_map,
        frontend_manifest: &source.manifest,
        policy_contract: &policy_contract,
        captured_inputs: &captured,
    };

    let scan = generate_staged_successor_policy_scan(boundary)
        .expect("frontend-only successor policy scan");
    assert_eq!(scan.document().schema(), SUCCESSOR_POLICY_SCAN_SCHEMA);
    let imported = import_staged_successor_policy_scan_json(scan.canonical_bytes(), boundary)
        .expect("exact successor scan reimport");
    assert_eq!(imported.canonical_bytes(), scan.canonical_bytes());
}

#[test]
fn staged_go_and_rust_keep_their_existing_policy_and_checker_verdicts() {
    let registry = registry();
    for (profile, artifacts, sources, expected_profile, strategy, axiom) in [
        (
            "go",
            "",
            "",
            CompiledSemanticProfile::GoFixedV0,
            "payment-policy-alpha",
            "zero-axiom",
        ),
        (
            "rust",
            "develop/migrations/csharp-02-staging/rust/module-calls/artifacts",
            "rust-tools/rust2vir/testdata/positive/module-calls/source",
            CompiledSemanticProfile::RustCheckedV0,
            "payment-policy-rust-alpha",
            "mvp-theory",
        ),
    ] {
        let source = if profile == "go" {
            go_identity_source(&registry)
        } else {
            staged_source(&registry, artifacts, sources)
        };
        let vc_contract = profile_contract(profile, "vc");
        let policy_contract = profile_contract(profile, "policy");
        let evidence_contract = profile_contract(profile, "evidence");
        let pair = generated_pair(&registry, &source, &vc_contract);
        let captured = captured_refs(&source.storage);
        let run = run_staged_successor_policy(
            source_boundary(
                &registry,
                &source,
                &pair,
                &policy_contract,
                &evidence_contract,
                &captured,
            ),
            PolicyVerificationOptions {
                strict: true,
                update_fixtures: false,
            },
        )
        .unwrap_or_else(|error| panic!("{profile} successor policy: {error}"));
        assert_eq!(run.registration().profile(), expected_profile);
        assert_eq!(run.registration().strategy_profile(), strategy);
        assert_eq!(run.registration().checker_profile(), "mvp-strict");
        assert_eq!(run.registration().axiom_profile(), axiom);
        assert_eq!(run.scan().document().schema(), SUCCESSOR_POLICY_SCAN_SCHEMA);
        assert_eq!(
            run.evidence().document().schema(),
            SUCCESSOR_POLICY_EVIDENCE_SCHEMA
        );
        let context = source.vir.module().semantic_context();
        let active_vc = VcDocument {
            schema: "mpk.vc.v1".to_owned(),
            source_ir_schema: "mpk.vir.v0".to_owned(),
            source_ir_hash: pair.vc.document().source_ir_hash().as_str().to_owned(),
            input_set_hash: pair.vc.document().input_set_hash().as_str().to_owned(),
            semantic_profile: match expected_profile {
                CompiledSemanticProfile::GoFixedV0 => SemanticProfile::GoFixedV0,
                CompiledSemanticProfile::RustCheckedV0 => SemanticProfile::RustCheckedV0,
                CompiledSemanticProfile::CSharpScalarV0 => unreachable!("loop has no C# case"),
            },
            semantic_parameters: serde_json::from_value::<SemanticParameters>(
                context.semantic_parameters().value().clone(),
            )
            .expect("active semantic parameters"),
            verification_limit_profile: pair.vc.document().verification_limit_profile().to_owned(),
            functions: pair.vc.document().functions().to_vec(),
            vc_hash: ZERO_SHA256.to_owned(),
        };
        let active_outcome = assemble_program_certificate_alpha(
            &active_vc,
            pair.skeleton.skeleton().theorem_declarations(),
            CertificateSourceManifest {
                payload: run.certificate_manifest().canonical_bytes().to_vec(),
            },
        )
        .unwrap_or_else(|error| panic!("{profile} active certificate assembly: {error}"));
        assert_eq!(
            run.program_certificate(),
            &active_outcome,
            "{profile} successor verdict or certificate bytes differ from the active assembler"
        );

        let selected_function = source.manifest.manifest().selection().value()["function"]
            .as_str()
            .expect("selected function");
        assert!(run
            .evidence()
            .document()
            .properties()
            .iter()
            .flat_map(|property| &property.members)
            .all(|member| member.function_id == selected_function));
        match run.program_certificate() {
            ProgramCertificateOutcome::Candidate(candidate) => {
                assert_eq!(candidate.rust_report.axiom_count, 0);
                assert_eq!(candidate.reference_report.axiom_count, 0);
                assert!(run
                    .evidence()
                    .document()
                    .trusted_evidence()
                    .checker_verdicts
                    .iter()
                    .all(|verdict| verdict.verdict == "accepted"));
            }
            outcome => panic!("{profile} staged verdict changed: {outcome:?}"),
        }
    }
}

#[test]
fn csharp_policy_owner_is_registered_for_every_consumed_frozen_vector() {
    let manifest = load("develop/specs/vectors/manifest.json");
    for path in [
        "develop/specs/vectors/csharp-profile-v0.json",
        "develop/specs/vectors/semantic-profile-registry-v1.json",
        "develop/specs/vectors/semantic-profile-registry-v2.json",
    ] {
        let record = manifest["vectors"]
            .as_array()
            .expect("vector manifest records")
            .iter()
            .find(|record| record["path"] == path)
            .unwrap_or_else(|| panic!("missing vector manifest record {path}"));
        assert!(record["implementation_test_owners"]
            .as_array()
            .expect("implementation owners")
            .iter()
            .any(|owner| owner == "crates/mpk-cli/tests/csharp_policy_verify.rs"));
    }
}
