use mpk_cli::frontend_protocol;
use mpk_cli::successor_frontend_runner::{
    run_installed_frontend, InstalledFrontendRunCode, InstalledFrontendRunRequest,
};
use mpk_cli::successor_release_bundle::{
    validate_successor_bundle_candidate, validate_successor_release_registry,
    ACTIVE_RELEASE_REGISTRY_SHA256, CSHARP_FRONTEND_BUNDLE_ID, CSHARP_TOOLCHAIN_BUNDLE_ID,
    GO_FRONTEND_BUNDLE_ID, GO_TOOLCHAIN_BUNDLE_ID, RUST_FRONTEND_BUNDLE_ID,
    RUST_TOOLCHAIN_BUNDLE_ID,
};
use mpk_vc::java_release;
use mpk_vc::semantic_profile_registry::{validate_semantic_profile_registry, RegistryRevision};
use mpk_vc::{CapturedInput, InputKind};
use serde_json::{json, Value};
use std::env;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

// The active installed-image test executable owns the source-free resource
// fault children. Including the sandbox here keeps those hidden entrypoints
// out of the production `mpk` binary while exercising the exact production
// implementation from the composed release gate.
#[path = "../src/frontend_registry.rs"]
#[allow(unused_imports)]
mod frontend_registry;
#[path = "../src/frontend_sandbox.rs"]
#[allow(unused_imports)]
mod frontend_sandbox;

const SEMANTIC_REGISTRY_SHA256: &str =
    "fc102411ac266a38db27f904df2ca6f794bca1a216fff12377d88990e653c557";
const CSHARP_PROFILE_ENTRY_SHA256: &str =
    "d4cc54a5364af848af845a9044d0f5aec962e6e509554e9a9b75a7a9f0b6e7ac";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";

struct OwnedInput {
    kind: InputKind,
    path: String,
    bytes: Vec<u8>,
}

fn main() -> ExitCode {
    if !cfg!(target_os = "linux") {
        // The installed image and cgroup-v2 sandbox are a Linux release gate.
        // Cross-platform runs validate the source-level successor owners.
        return ExitCode::SUCCESS;
    }
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    if arguments.first().map(String::as_str) == Some("__mpk_frontend_sandbox_v0") {
        return ExitCode::from(mpk_cli::run_frontend_sandbox_bootstrap(&arguments[1..]));
    }
    if arguments.as_slice() == ["__mpk_frontend_probe_v0"] {
        return ExitCode::from(mpk_cli::run_frontend_sandbox_probe());
    }
    #[cfg(target_os = "linux")]
    if let [mode, case] = arguments.as_slice() {
        if mode == "__mpk_java_resource_fault_v0" {
            return ExitCode::from(frontend_sandbox::run_java_resource_test_child(case));
        }
        if mode == "--inside-successor-java-resource" {
            return match frontend_sandbox::test_java_resource_boundary(case) {
                Ok(()) => ExitCode::SUCCESS,
                Err(error) => {
                    eprintln!("JAVA_RESOURCE_TEST_{error:?}");
                    ExitCode::FAILURE
                }
            };
        }
    }
    let result = match arguments.as_slice() {
        [mode] if mode == "--inside-successor-cutover-go" => run_inside_installed_frontend("go"),
        [mode] if mode == "--inside-successor-cutover-rust" => {
            run_inside_installed_frontend("rust")
        }
        [mode] if mode == "--inside-successor-cutover-csharp" => {
            run_inside_installed_frontend("csharp")
        }
        [mode] if mode == "--inside-successor-cutover-java" => {
            run_inside_installed_frontend("java")
        }
        [mode] if mode == "--inside-successor-cutover-go-hostile" => {
            poison_environment();
            run_inside_installed_frontend("go")
        }
        [mode] if mode == "--inside-successor-cutover-rust-hostile" => {
            poison_environment();
            run_inside_installed_frontend("rust")
        }
        [mode] if mode == "--inside-successor-cutover-csharp-hostile" => {
            poison_environment();
            run_inside_installed_frontend("csharp")
        }
        [mode] if mode == "--inside-successor-cutover-java-hostile" => {
            poison_environment();
            run_inside_installed_frontend("java")
        }
        [mode, case] if mode == "--inside-successor-cutover-java-case" => {
            run_java_case(case).and_then(write_report)
        }
        [mode, case] if mode == "--inside-successor-cutover-java-hostile-case" => {
            poison_environment();
            run_java_case(case).and_then(write_report)
        }
        [mode] if mode == "--inside-successor-java-release-before-source" => {
            java_release_preflight(InstalledFrontendRunCode::Release)
        }
        [mode] if mode == "--inside-successor-java-release-control" => {
            java_release_preflight(InstalledFrontendRunCode::Selection)
        }
        [mode] if mode == "--inside-successor-java-trace-probe" => run_java_trace_probe(),
        [] => run_outer_cutover_gate(false),
        [mode] if mode == "--full-native-gate" => run_outer_cutover_gate(true),
        _ => Err("unexpected cutover-test arguments".to_owned()),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn run_inside_installed_frontend(language: &str) -> Result<(), String> {
    let report = match language {
        "go" => run_go(),
        "rust" => run_rust(),
        "csharp" => run_csharp(),
        "java" => run_java(),
        _ => Err("unknown installed frontend".to_owned()),
    }
    .map_err(|error| format!("{language} frontend: {error}"))?;
    write_report(report)
}

fn write_report(report: Value) -> Result<(), String> {
    print!(
        "{}",
        String::from_utf8(canonical_line(&report)?).map_err(display)?
    );
    Ok(())
}

fn run_go() -> Result<Value, String> {
    let envelope = load("fixtures/vir-go/frontend/basic-arith/frontend-envelope.json")?;
    let source_root = repository_root().join("fixtures/go-basic");
    let storage = captured_storage(&source_root, &envelope["source_manifest"])?;
    let captured = captured_refs(&storage);
    run_native(
        "go",
        &envelope,
        &captured,
        &[],
        GO_FRONTEND_BUNDLE_ID,
        GO_TOOLCHAIN_BUNDLE_ID,
    )
}

fn run_rust() -> Result<Value, String> {
    let envelope =
        load("fixtures/rust-basic/positive/checked-addition/artifacts/frontend-envelope.json")?;
    let source_root =
        repository_root().join("fixtures/rust-basic/positive/checked-addition/source");
    let storage = captured_storage(&source_root, &envelope["source_manifest"])?;
    let captured = captured_refs(&storage);
    let contracts = vec!["contracts/selected.json".to_owned()];
    run_native(
        "rust",
        &envelope,
        &captured,
        &contracts,
        RUST_FRONTEND_BUNDLE_ID,
        RUST_TOOLCHAIN_BUNDLE_ID,
    )
}

fn run_native(
    language: &str,
    envelope: &Value,
    captured: &[CapturedInput<'_>],
    contracts: &[String],
    frontend_bundle_id: &str,
    toolchain_bundle_id: &str,
) -> Result<Value, String> {
    let accepted = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: &envelope["semantic_context"],
        selection: &envelope["selection"],
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id,
        toolchain_bundle_id,
        captured_inputs: captured,
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts,
    })
    .map_err(display)?;
    let artifacts = accepted
        .envelope()
        .artifacts()
        .ok_or_else(|| format!("{language} emitted no artifacts"))?;
    ensure(
        accepted.envelope().status() == "ir-lowered",
        "frontend status",
    )?;
    ensure(accepted.envelope().phase() == "emission", "frontend phase")?;
    ensure(
        accepted.release_registry().registry_sha256 == ACTIVE_RELEASE_REGISTRY_SHA256,
        "frontend release identity",
    )?;
    Ok(json!({
        "language": language,
        "source_manifest_hash": artifacts.source_manifest().hash().as_str(),
        "source_map_hash": artifacts.source_map().hash().as_str(),
        "status": accepted.envelope().status(),
        "vir_hash": artifacts.vir().hash().as_str()
    }))
}

fn run_csharp() -> Result<Value, String> {
    let profile = load("develop/specs/vectors/csharp-profile-v0.json")?;
    let semantic_context = json!({
        "profile_registry": {
            "schema": "mpk.semantic_profile.registry.v1",
            "id": "mpk.semantic_profile.registry.v1",
            "revision": 3,
            "registry_sha256": SEMANTIC_REGISTRY_SHA256
        },
        "profile_entry_sha256": CSHARP_PROFILE_ENTRY_SHA256,
        "source_language": "csharp",
        "semantic_profile": "mpk.csharp.scalar.v0",
        "semantic_parameters": profile["semantic_parameters"].clone()
    });
    let selection = profile["case_harness"]["baseline_selection"].clone();
    let source = profile["case_harness"]["baseline_files"]["src/Policy.cs"]
        .as_str()
        .ok_or("missing C# baseline source")?
        .as_bytes()
        .to_vec();
    let mut contract =
        serde_json::to_vec(&profile["case_harness"]["baseline_files"]["contracts/approved.json"])
            .map_err(display)?;
    contract.push(b'\n');
    let captured = [
        CapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/approved.json",
            bytes: &contract,
        },
        CapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Policy.cs",
            bytes: &source,
        },
    ];
    let accepted = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: &semantic_context,
        selection: &selection,
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id: CSHARP_FRONTEND_BUNDLE_ID,
        toolchain_bundle_id: CSHARP_TOOLCHAIN_BUNDLE_ID,
        captured_inputs: &captured,
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts: &[],
    })
    .map_err(display)?;
    let artifacts = accepted
        .envelope()
        .artifacts()
        .ok_or("C# emitted no artifacts")?;
    Ok(json!({
        "language": "csharp",
        "source_manifest_hash": artifacts.source_manifest().hash().as_str(),
        "source_map_hash": artifacts.source_map().hash().as_str(),
        "status": accepted.envelope().status(),
        "vir_hash": artifacts.vir().hash().as_str()
    }))
}

fn run_java() -> Result<Value, String> {
    run_java_case("int.identity")
}

fn run_java_case(case_id: &str) -> Result<Value, String> {
    let vector = load("develop/specs/vectors/java-profile-v0.json")?;
    let case = vector["accepted_cases"]
        .as_array()
        .and_then(|cases| cases.iter().find(|case| case["id"] == case_id))
        .ok_or("Java installed case is absent")?;
    let mut storage = Vec::new();
    for (path, source) in case["sources"]
        .as_object()
        .ok_or("Java sources are absent")?
    {
        storage.push(OwnedInput {
            kind: InputKind::Source,
            path: path.clone(),
            bytes: source
                .as_str()
                .ok_or("Java source is invalid")?
                .as_bytes()
                .to_vec(),
        });
    }
    for (index, contract) in case["contracts"]
        .as_array()
        .ok_or("Java contracts are absent")?
        .iter()
        .enumerate()
    {
        storage.push(OwnedInput {
            kind: InputKind::Contract,
            path: format!("contracts/c{index}.json"),
            bytes: canonical_line(contract)?,
        });
    }
    let paths = |kind| {
        storage
            .iter()
            .filter(|input| input.kind == kind)
            .map(|input| input.path.clone())
            .collect::<Vec<_>>()
    };
    let selection = json!({"schema":"mpk.selection.java_methods.v0", "value": {
        "compilation":"installed-vector",
        "sources":paths(InputKind::Source),
        "contracts":paths(InputKind::Contract),
        "methods":case["methods"]
    }});
    let captured = captured_refs(&storage);
    let accepted = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: &vector["semantic_context_fixture"],
        selection: &selection,
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id: java_release::FRONTEND_ID,
        toolchain_bundle_id: java_release::TOOLCHAIN_ID,
        captured_inputs: &captured,
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts: &[],
    })
    .map_err(display)?;
    let artifacts = accepted
        .envelope()
        .artifacts()
        .ok_or("Java emitted no artifacts")?;
    ensure(
        accepted.envelope().status() == "ir-lowered",
        "Java frontend status",
    )?;
    ensure(
        accepted.envelope().phase() == "emission",
        "Java frontend phase",
    )?;
    ensure(
        accepted.release_registry().registry_sha256 == ACTIVE_RELEASE_REGISTRY_SHA256,
        "Java frontend release identity",
    )?;
    Ok(json!({
        "language":"java",
        "source_manifest_hash":artifacts.source_manifest().hash().as_str(),
        "source_map_hash":artifacts.source_map().hash().as_str(),
        "status":accepted.envelope().status(),
        "vir_hash":artifacts.vir().hash().as_str()
    }))
}

fn java_release_preflight(expected: InstalledFrontendRunCode) -> Result<(), String> {
    let context = &java_release::candidate().tuples[0].semantic_context;
    let selection = json!({"schema":"mpk.selection.java_methods.v0", "value": {
        "compilation":"release-preflight",
        "sources":["src/must-not-be-read.java"],
        "contracts":["contracts/must-not-be-read.json"],
        "methods":["preflight.Case::f(int)->int"]
    }});
    let result = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: context,
        selection: &selection,
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id: java_release::FRONTEND_ID,
        toolchain_bundle_id: java_release::TOOLCHAIN_ID,
        captured_inputs: &[],
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts: &[],
    });
    match result {
        Err(error) if error.code() == expected => Ok(()),
        _ => Err(format!(
            "Java release preflight did not return {} before source access",
            expected.as_str()
        )),
    }
}

fn run_java_trace_probe() -> Result<(), String> {
    let installed = frontend_registry::InstalledSuccessorRelease::open().map_err(display)?;
    let semantic = validate_semantic_profile_registry(
        &installed.semantic_registry_bytes,
        RegistryRevision::Revision3,
    )
    .map_err(display)?;
    let release = validate_successor_release_registry(&installed.registry_bytes, &semantic)
        .map_err(display)?;
    ensure(
        semantic.identity().registry_sha256() == SEMANTIC_REGISTRY_SHA256
            && release.registry_sha256() == ACTIVE_RELEASE_REGISTRY_SHA256,
        "Java trace probe release identity",
    )?;
    let expected = release
        .registry()
        .frontend_bundles
        .iter()
        .map(|bundle| (bundle.bundle_id.clone(), &bundle.inventory))
        .chain(
            release
                .registry()
                .toolchain_bundles
                .iter()
                .map(|bundle| (bundle.bundle_id.clone(), &bundle.inventory)),
        )
        .collect();
    let snapshots = installed
        .snapshot_selected_bundles(
            &expected,
            java_release::FRONTEND_ID,
            java_release::TOOLCHAIN_ID,
        )
        .map_err(display)?;
    let sandbox = frontend_sandbox::prepare_release_sandbox(java_release::HOST_ID)
        .map_err(|error| format!("Java trace probe sandbox: {error:?}"))?;
    let frontend = snapshots
        .get(java_release::FRONTEND_ID)
        .ok_or("Java trace probe frontend snapshot")?;
    let toolchain = snapshots
        .get(java_release::TOOLCHAIN_ID)
        .ok_or("Java trace probe toolchain snapshot")?;
    let output = frontend_sandbox::launch_java_trace_probe(sandbox, frontend, toolchain)
        .map_err(|error| format!("Java trace probe launch: {error:?}"))?;
    // `inactive` is the immutable T09 candidate's version label, not an
    // activation switch; the installed revision-3 descriptors own activation.
    ensure(
        output.exit_code == Some(0)
            && !output.signaled
            && output.stdout == b"java2vir 0.1.0 (Temurin 25.0.4.1+1; inactive)\n"
            && output.stderr_observed_bytes == 0
            && !output.stream_limit_exceeded,
        "Java trace probe output",
    )
}

fn run_outer_cutover_gate(full_native_gate: bool) -> Result<(), String> {
    validate_active_models()?;
    let temporary = tempfile::Builder::new()
        .prefix("mpk-successor-cutover-")
        .tempdir_in("/tmp")
        .map_err(display)?;
    let installed = temporary.path().join("installed");
    let executable = env::current_exe().map_err(display)?;
    let materialized = assembler(&[
        "materialize-fixture",
        executable.to_str().ok_or("test path is not UTF-8")?,
        installed.to_str().ok_or("installed path is not UTF-8")?,
    ])?;
    ensure(
        materialized.status.success()
            && materialized.stdout.is_empty()
            && materialized.stderr.is_empty(),
        &format!(
            "successor image materialization failed: {}",
            String::from_utf8_lossy(&materialized.stderr)
        ),
    )?;
    validate_installed_topology(&installed)?;

    let run_once = |hostile: bool| -> Result<std::process::Output, String> {
        let installed_executable = installed.join("bin/mpk");
        let mut command = assembler_command();
        command.args([
            if hostile {
                "run-installed-hostile"
            } else {
                "run-installed"
            },
            installed_executable
                .to_str()
                .ok_or("installed executable path is not UTF-8")?,
        ]);
        command.output().map_err(display)
    };
    let first = run_once(false)?;
    ensure(
        first.status.success() && first.stderr.is_empty(),
        &format!(
            "installed successor run failed: {}",
            String::from_utf8_lossy(&first.stderr)
        ),
    )?;
    let second = run_once(true)?;
    ensure(
        second.status.success() && second.stderr.is_empty() && second.stdout == first.stdout,
        "hostile ambient state changed installed successor output",
    )?;
    let report: Value = serde_json::from_slice(&first.stdout).map_err(display)?;
    ensure(
        canonical_line(&report)? == first.stdout,
        "noncanonical installed report",
    )?;
    ensure(
        report["status"] == "active_successor",
        "inactive installed report",
    )?;
    ensure(
        report["languages"]
            .as_array()
            .is_some_and(|languages| languages.len() == 4),
        "installed report did not execute all frontends",
    )?;

    if full_native_gate {
        let installed_executable = installed.join("bin/mpk");
        let native = assembler(&[
            "run-installed-java-native-gate",
            installed_executable
                .to_str()
                .ok_or("installed executable path is not UTF-8")?,
        ])?;
        ensure(
            native.status.success() && native.stderr.is_empty(),
            &format!(
                "installed Java native gate failed: {}",
                String::from_utf8_lossy(&native.stderr)
            ),
        )?;
        let native_report: Value = serde_json::from_slice(&native.stdout).map_err(display)?;
        ensure(
            canonical_line(&native_report)? == native.stdout
                && native_report["schema"] == "mpk.java.active_native_gate.v0"
                && native_report["native_architecture"] == "x86_64"
                && native_report["hostile_environment_equal"] == true
                && native_report["undelegated_cgroup_rejected"] == true
                && native_report["resource_faults"]
                    == json!(["oom", "pids", "timeout", "stdout", "stderr", "tmpfs"])
                && native_report["source_precedence_mutations"]
                    .as_array()
                    .is_some_and(|mutations| mutations.len() == 10)
                && native_report["syscall_observation"]["jvm_clone3_fallback"] == true
                && native_report["syscall_observation"]["jvm_thread_creations"]
                    .as_u64()
                    .is_some_and(|count| count > 0),
            "installed Java native report is incomplete",
        )?;
    }

    let tampered = installed
        .join("libexec/mpk/bundles")
        .join(GO_FRONTEND_BUNDLE_ID)
        .join("bin/go2vir");
    fs::set_permissions(&tampered, fs::Permissions::from_mode(0o755)).map_err(display)?;
    let mut bytes = fs::read(&tampered).map_err(display)?;
    bytes.push(0);
    fs::write(&tampered, bytes).map_err(display)?;
    fs::set_permissions(&tampered, fs::Permissions::from_mode(0o555)).map_err(display)?;
    let rejected = run_once(false)?;
    ensure(
        !rejected.status.success() && rejected.stdout.is_empty(),
        "tampered installed successor image did not fail closed",
    )?;
    Ok(())
}

fn poison_environment() {
    // Set these after the trusted test executable has started so loader
    // variables challenge child inheritance without poisoning this process.
    for (key, value) in [
        ("CLASSPATH", "/host/classes"),
        ("DOTNET_ROOT", "/host/dotnet"),
        ("HOME", "/host/home"),
        ("JAVA_HOME", "/host/jdk"),
        ("JAVA_TOOL_OPTIONS", "-javaagent:/host/agent.jar"),
        ("JDK_JAVA_OPTIONS", "-Dhost.injected=true"),
        ("JDK_JAVAC_OPTIONS", "-processor poison.Processor"),
        ("LD_LIBRARY_PATH", "/host/lib"),
        ("LD_PRELOAD", "/host/preload.so"),
        ("MPK_PLUGIN", "/host/plugin"),
        ("PATH", "/nonexistent"),
        ("_JAVA_OPTIONS", "-Dhost.legacy=true"),
    ] {
        env::set_var(key, value);
    }
}

fn validate_active_models() -> Result<(), String> {
    let semantic_bytes = read("release/bundles/semantic-profile-registry.json")?;
    let semantic = validate_semantic_profile_registry(&semantic_bytes, RegistryRevision::Revision3)
        .map_err(display)?;
    ensure(
        semantic.identity().registry_sha256() == SEMANTIC_REGISTRY_SHA256,
        "semantic registry hash",
    )?;
    let registry_bytes = read("release/bundles/bundle-registry.json")?;
    let registry =
        validate_successor_release_registry(&registry_bytes, &semantic).map_err(display)?;
    ensure(
        registry.registry_sha256() == ACTIVE_RELEASE_REGISTRY_SHA256
            && registry.registry().frontend_bundles.len() == 4
            && registry.registry().toolchain_bundles.len() == 4
            && registry.registry().tuples.len() == 5,
        "release registry is not the complete successor",
    )?;
    for language in ["go", "rust", "csharp", "java"] {
        validate_successor_bundle_candidate(
            &read(&format!("release/bundles/candidates/{language}.json"))?,
            &semantic,
        )
        .map_err(display)?;
    }
    let semantic_value: Value = serde_json::from_slice(&semantic_bytes).map_err(display)?;
    let csharp = semantic_value["profiles"]
        .as_array()
        .and_then(|profiles| {
            profiles
                .iter()
                .find(|profile| profile["source_language"] == "csharp")
        })
        .ok_or("C# semantic profile is absent")?;
    let contracts = csharp["contracts"]
        .as_object()
        .ok_or("C# contracts are absent")?;
    ensure(
        csharp["entry_sha256"] == CSHARP_PROFILE_ENTRY_SHA256
            && contracts.keys().map(String::as_str).collect::<Vec<_>>()
                == [
                    "ai",
                    "evidence",
                    "frontend",
                    "manifest",
                    "policy",
                    "release",
                    "source_map",
                    "vc",
                    "vir",
                ],
        "C# profile contracts are not the reviewed nine-contract set",
    )?;
    let review = load("develop/migrations/archive/csharp-02-final-review.json")?;
    ensure(
        review["status"] == "reviewed_zero_findings"
            && review["axiom_review"]["new_categories"] == json!([]),
        "review or axiom ledger is not clean",
    )?;
    Ok(())
}

fn validate_installed_topology(root: &Path) -> Result<(), String> {
    let expected = [
        CSHARP_FRONTEND_BUNDLE_ID,
        CSHARP_TOOLCHAIN_BUNDLE_ID,
        GO_FRONTEND_BUNDLE_ID,
        GO_TOOLCHAIN_BUNDLE_ID,
        RUST_FRONTEND_BUNDLE_ID,
        RUST_TOOLCHAIN_BUNDLE_ID,
        java_release::FRONTEND_ID,
        java_release::TOOLCHAIN_ID,
    ];
    let mut actual = fs::read_dir(root.join("libexec/mpk/bundles"))
        .map_err(display)?
        .map(|entry| entry.map(|value| value.file_name()).map_err(display))
        .collect::<Result<Vec<_>, _>>()?;
    actual.sort();
    let mut expected = expected.map(std::ffi::OsString::from).to_vec();
    expected.sort();
    ensure(actual == expected, "installed bundle set")?;
    ensure(
        fs::read(root.join("share/mpk/bundle-registry.json")).map_err(display)?
            == read("release/bundles/bundle-registry.json")?
            && fs::read(root.join("share/mpk/semantic-profile-registry.json")).map_err(display)?
                == read("release/bundles/semantic-profile-registry.json")?,
        "installed registries differ from active bytes",
    )?;
    Ok(())
}

fn captured_storage(source_root: &Path, manifest: &Value) -> Result<Vec<OwnedInput>, String> {
    manifest["inputs"]
        .as_array()
        .ok_or("manifest inputs are absent")?
        .iter()
        .map(|entry| {
            let kind = match entry["kind"].as_str().ok_or("input kind is absent")? {
                "source" => InputKind::Source,
                "contract" => InputKind::Contract,
                "build_manifest" => InputKind::BuildManifest,
                "lockfile" => InputKind::Lockfile,
                _ => return Err("unknown input kind".to_owned()),
            };
            let path = entry["normalized_path"]
                .as_str()
                .ok_or("input path is absent")?
                .to_owned();
            let disk = source_root.join(&path);
            let bytes = match fs::read(&disk) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match path.as_str() {
                    "go.sum" => Vec::new(),
                    "Cargo.toml" => GENERATED_CARGO_TOML.to_vec(),
                    "Cargo.lock" => GENERATED_CARGO_LOCK.to_vec(),
                    _ => return Err(format!("read {}: {error}", disk.display())),
                },
                Err(error) => return Err(format!("read {}: {error}", disk.display())),
            };
            Ok(OwnedInput { kind, path, bytes })
        })
        .collect()
}

fn captured_refs(storage: &[OwnedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.path,
            bytes: &input.bytes,
        })
        .collect()
}

fn assembler(arguments: &[&str]) -> Result<std::process::Output, String> {
    assembler_command()
        .args(arguments)
        .output()
        .map_err(display)
}

fn assembler_command() -> Command {
    let mut command = Command::new("python3");
    command
        .arg(repository_root().join("scripts/successor_release_bundles.py"))
        .current_dir(repository_root())
        .env_clear()
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .env("PYTHONDONTWRITEBYTECODE", "1");
    command
}

fn load(relative: &str) -> Result<Value, String> {
    serde_json::from_slice(&read(relative)?).map_err(display)
}

fn read(relative: &str) -> Result<Vec<u8>, String> {
    fs::read(repository_root().join(relative)).map_err(display)
}

fn canonical_line(value: &Value) -> Result<Vec<u8>, String> {
    let mut bytes = serde_json::to_vec(value).map_err(display)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn ensure(condition: bool, message: &str) -> Result<(), String> {
    condition.then_some(()).ok_or_else(|| message.to_owned())
}

fn display(error: impl std::fmt::Display) -> String {
    error.to_string()
}
