use mpk_cli::frontend_protocol::FrontendProcessFacts;
use mpk_cli::successor_frontend_protocol::{
    validate_successor_frontend_process, SuccessorFrontendProtocolRequest,
};
use mpk_vc::semantic_profile_registry::{
    validate_registry_selection_envelope, validate_registry_semantic_context,
    validate_semantic_profile_registry, RegistryRevision, ValidatedSemanticProfileRegistry,
};
use mpk_vc::{CapturedInput, InputKind, ReleaseRegistryIdentity};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};

const ACTIVE_ROOT: &str = "fixtures/rust-basic/positive";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";

struct OwnedCapturedInput {
    kind: InputKind,
    path: String,
    bytes: Vec<u8>,
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    fs::read(repository_root().join(relative.as_ref()))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.as_ref().display()))
}

fn json(relative: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&read(relative)).expect("checked-in JSON")
}

fn semantic_registry() -> ValidatedSemanticProfileRegistry {
    validate_semantic_profile_registry(
        &read("release/bundles/semantic-profile-registry.json"),
        RegistryRevision::Revision2,
    )
    .expect("revision-2 semantic registry")
}

fn kind(value: &Value) -> InputKind {
    match value.as_str().expect("input kind") {
        "source" => InputKind::Source,
        "contract" => InputKind::Contract,
        "build_manifest" => InputKind::BuildManifest,
        "lockfile" => InputKind::Lockfile,
        other => panic!("unknown input kind {other}"),
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = kind(&entry["kind"]);
            let path = entry["normalized_path"]
                .as_str()
                .expect("input path")
                .to_owned();
            let disk_path = repository_root().join(source_root).join(&path);
            let bytes = match fs::read(&disk_path) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match kind {
                    InputKind::BuildManifest if path == "Cargo.toml" => {
                        GENERATED_CARGO_TOML.to_vec()
                    }
                    InputKind::Lockfile if path == "Cargo.lock" => GENERATED_CARGO_LOCK.to_vec(),
                    _ => panic!("read {}: {error}", disk_path.display()),
                },
                Err(error) => panic!("read {}: {error}", disk_path.display()),
            };
            OwnedCapturedInput { kind, path, bytes }
        })
        .collect()
}

fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.path,
            bytes: &input.bytes,
        })
        .collect()
}

fn process_line(mut bytes: Vec<u8>, exit_code: i32) -> (Vec<u8>, i32) {
    if bytes.ends_with(b"\n") {
        assert!(!bytes[..bytes.len() - 1].contains(&b'\n'));
    } else {
        bytes.push(b'\n');
    }
    (bytes, exit_code)
}

fn artifact_path<'a>(case: &'a Value, kind: &str) -> &'a str {
    case["artifacts"]
        .as_array()
        .expect("artifacts")
        .iter()
        .find(|artifact| artifact["kind"] == kind)
        .unwrap_or_else(|| panic!("missing {kind} for {}", case["id"]))["path"]
        .as_str()
        .expect("artifact path")
}

#[test]
fn active_rust_envelopes_use_the_successor_protocol_family() {
    let registry = semantic_registry();
    let active_index = json(format!("{ACTIVE_ROOT}/frontend-index.json"));

    for case in active_index["cases"].as_array().expect("positive cases") {
        let id = case["id"].as_str().expect("case ID");
        let envelope_bytes =
            read(Path::new(ACTIVE_ROOT).join(artifact_path(case, "frontend_envelope")));
        let envelope: Value =
            serde_json::from_slice(&envelope_bytes).expect("successor envelope JSON");
        let semantic_context =
            validate_registry_semantic_context(&registry, &envelope["semantic_context"])
                .unwrap_or_else(|error| panic!("{id}: semantic context rejected: {error}"));
        let selection = validate_registry_selection_envelope(
            &registry,
            &semantic_context,
            &envelope["selection"],
        )
        .unwrap_or_else(|error| panic!("{id}: selection rejected: {error}"));
        let release_registry: ReleaseRegistryIdentity =
            serde_json::from_value(envelope["source_manifest"]["release_registry"].clone())
                .expect("release-registry identity");
        let storage = captured_storage(
            case["source_root"].as_str().expect("source root"),
            &envelope["source_manifest"],
        );
        let captured = captured_refs(&storage);
        let (stdout, exit_code) = process_line(envelope_bytes, 0);
        let accepted = validate_successor_frontend_process(
            SuccessorFrontendProtocolRequest {
                registry: &registry,
                semantic_context: &semantic_context,
                selection: &selection,
                release_registry: &release_registry,
                captured_inputs: &captured,
                synthetic_permissions: &[],
            },
            FrontendProcessFacts {
                exit_code: Some(exit_code),
                signaled: false,
                stdout: &stdout,
                stderr_observed_bytes: 0,
            },
        )
        .unwrap_or_else(|error| panic!("{id}: successor protocol rejected: {error}"));
        assert_eq!(accepted.status(), "ir-lowered");
        assert_eq!(accepted.phase(), "emission");
        assert!(accepted.artifacts().is_some());
    }
}
