use mpk_cli::successor_frontend_runner::{run_installed_frontend, InstalledFrontendRunRequest};
use mpk_cli::successor_release_bundle::{
    validate_successor_bundle_candidate, validate_successor_release_registry,
    ACTIVE_RELEASE_REGISTRY_SHA256, CSHARP_FRONTEND_BUNDLE_ID, CSHARP_TOOLCHAIN_BUNDLE_ID,
    GO_FRONTEND_BUNDLE_ID, GO_TOOLCHAIN_BUNDLE_ID, RUST_FRONTEND_BUNDLE_ID,
    RUST_TOOLCHAIN_BUNDLE_ID,
};
use mpk_vc::semantic_profile_registry::{validate_semantic_profile_registry, RegistryRevision};
use mpk_vc::{CapturedInput, InputKind};
use serde_json::{json, Value};
use std::env;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode};

const SEMANTIC_REGISTRY_SHA256: &str =
    "6928e49ab2d0af03bdc1b92c189f99308f815e77edb3850a5f5a8fd9a3d48b75";
const CSHARP_PROFILE_ENTRY_SHA256: &str =
    "d4cc54a5364af848af845a9044d0f5aec962e6e509554e9a9b75a7a9f0b6e7ac";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";

struct OwnedInput {
    kind: InputKind,
    path: String,
    bytes: Vec<u8>,
}

fn main() -> ExitCode {
    if !cfg!(target_os = "linux") {
        // The installed image and cgroup-v2 sandbox are a Linux release gate.
        // Cross-platform runs validate the source-level successor owners.
        return ExitCode::SUCCESS;
    }
    let arguments = env::args().skip(1).collect::<Vec<_>>();
    if arguments.first().map(String::as_str) == Some("__mpk_frontend_sandbox_v0") {
        return ExitCode::from(mpk_cli::run_frontend_sandbox_bootstrap(&arguments[1..]));
    }
    if arguments.as_slice() == ["__mpk_frontend_probe_v0"] {
        return ExitCode::from(mpk_cli::run_frontend_sandbox_probe());
    }
    let result = match arguments.as_slice() {
        [mode] if mode == "--inside-successor-cutover-go" => run_inside_installed_frontend("go"),
        [mode] if mode == "--inside-successor-cutover-rust" => {
            run_inside_installed_frontend("rust")
        }
        [mode] if mode == "--inside-successor-cutover-csharp" => {
            run_inside_installed_frontend("csharp")
        }
        [] => run_outer_cutover_gate(),
        _ => Err("unexpected cutover-test arguments".to_owned()),
    };
    match result {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("{error}");
            ExitCode::FAILURE
        }
    }
}

fn run_inside_installed_frontend(language: &str) -> Result<(), String> {
    let report = match language {
        "go" => run_go(),
        "rust" => run_rust(),
        "csharp" => run_csharp(),
        _ => Err("unknown installed frontend".to_owned()),
    }
    .map_err(|error| format!("{language} frontend: {error}"))?;
    print!(
        "{}",
        String::from_utf8(canonical_line(&report)?).map_err(display)?
    );
    Ok(())
}

fn run_go() -> Result<Value, String> {
    let envelope = load("fixtures/vir-go/frontend/basic-arith/frontend-envelope.json")?;
    let source_root = repository_root().join("fixtures/go-basic");
    let storage = captured_storage(&source_root, &envelope["source_manifest"])?;
    let captured = captured_refs(&storage);
    run_native(
        "go",
        &envelope,
        &captured,
        &[],
        GO_FRONTEND_BUNDLE_ID,
        GO_TOOLCHAIN_BUNDLE_ID,
    )
}

fn run_rust() -> Result<Value, String> {
    let envelope =
        load("fixtures/rust-basic/positive/checked-addition/artifacts/frontend-envelope.json")?;
    let source_root =
        repository_root().join("fixtures/rust-basic/positive/checked-addition/source");
    let storage = captured_storage(&source_root, &envelope["source_manifest"])?;
    let captured = captured_refs(&storage);
    let contracts = vec!["contracts/selected.json".to_owned()];
    run_native(
        "rust",
        &envelope,
        &captured,
        &contracts,
        RUST_FRONTEND_BUNDLE_ID,
        RUST_TOOLCHAIN_BUNDLE_ID,
    )
}

fn run_native(
    language: &str,
    envelope: &Value,
    captured: &[CapturedInput<'_>],
    contracts: &[String],
    frontend_bundle_id: &str,
    toolchain_bundle_id: &str,
) -> Result<Value, String> {
    let accepted = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: &envelope["semantic_context"],
        selection: &envelope["selection"],
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id,
        toolchain_bundle_id,
        captured_inputs: captured,
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts,
    })
    .map_err(display)?;
    let artifacts = accepted
        .envelope()
        .artifacts()
        .ok_or_else(|| format!("{language} emitted no artifacts"))?;
    ensure(
        accepted.envelope().status() == "ir-lowered",
        "frontend status",
    )?;
    ensure(accepted.envelope().phase() == "emission", "frontend phase")?;
    ensure(
        accepted.release_registry().registry_sha256 == ACTIVE_RELEASE_REGISTRY_SHA256,
        "frontend release identity",
    )?;
    Ok(json!({
        "language": language,
        "source_manifest_hash": artifacts.source_manifest().hash().as_str(),
        "source_map_hash": artifacts.source_map().hash().as_str(),
        "status": accepted.envelope().status(),
        "vir_hash": artifacts.vir().hash().as_str()
    }))
}

fn run_csharp() -> Result<Value, String> {
    let profile = load("develop/specs/vectors/csharp-profile-v0.json")?;
    let semantic_context = json!({
        "profile_registry": {
            "schema": "mpk.semantic_profile.registry.v1",
            "id": "mpk.semantic_profile.registry.v1",
            "revision": 2,
            "registry_sha256": SEMANTIC_REGISTRY_SHA256
        },
        "profile_entry_sha256": CSHARP_PROFILE_ENTRY_SHA256,
        "source_language": "csharp",
        "semantic_profile": "mpk.csharp.scalar.v0",
        "semantic_parameters": profile["semantic_parameters"].clone()
    });
    let selection = profile["case_harness"]["baseline_selection"].clone();
    let source = profile["case_harness"]["baseline_files"]["src/Policy.cs"]
        .as_str()
        .ok_or("missing C# baseline source")?
        .as_bytes()
        .to_vec();
    let mut contract =
        serde_json::to_vec(&profile["case_harness"]["baseline_files"]["contracts/approved.json"])
            .map_err(display)?;
    contract.push(b'\n');
    let captured = [
        CapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/approved.json",
            bytes: &contract,
        },
        CapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Policy.cs",
            bytes: &source,
        },
    ];
    let accepted = run_installed_frontend(InstalledFrontendRunRequest {
        semantic_context: &semantic_context,
        selection: &selection,
        release_registry_id: "mpk.release.registry.v1",
        release_registry_sha256: ACTIVE_RELEASE_REGISTRY_SHA256,
        frontend_bundle_id: CSHARP_FRONTEND_BUNDLE_ID,
        toolchain_bundle_id: CSHARP_TOOLCHAIN_BUNDLE_ID,
        captured_inputs: &captured,
        synthetic_permissions: &[],
        staged_directories: &[],
        staged_placeholders: &[],
        contracts: &[],
    })
    .map_err(display)?;
    let artifacts = accepted
        .envelope()
        .artifacts()
        .ok_or("C# emitted no artifacts")?;
    Ok(json!({
        "language": "csharp",
        "source_manifest_hash": artifacts.source_manifest().hash().as_str(),
        "source_map_hash": artifacts.source_map().hash().as_str(),
        "status": accepted.envelope().status(),
        "vir_hash": artifacts.vir().hash().as_str()
    }))
}

fn run_outer_cutover_gate() -> Result<(), String> {
    validate_active_models()?;
    let temporary = tempfile::Builder::new()
        .prefix("mpk-successor-cutover-")
        .tempdir_in("/tmp")
        .map_err(display)?;
    let installed = temporary.path().join("installed");
    let executable = env::current_exe().map_err(display)?;
    let materialized = assembler(&[
        "materialize-fixture",
        executable.to_str().ok_or("test path is not UTF-8")?,
        installed.to_str().ok_or("installed path is not UTF-8")?,
    ])?;
    ensure(
        materialized.status.success()
            && materialized.stdout.is_empty()
            && materialized.stderr.is_empty(),
        &format!(
            "successor image materialization failed: {}",
            String::from_utf8_lossy(&materialized.stderr)
        ),
    )?;
    validate_installed_topology(&installed)?;

    let run_once = |hostile: bool| -> Result<std::process::Output, String> {
        let installed_executable = installed.join("bin/mpk");
        let mut command = assembler_command();
        command.args([
            "run-installed",
            installed_executable
                .to_str()
                .ok_or("installed executable path is not UTF-8")?,
        ]);
        if hostile {
            command
                .env("DOTNET_ROOT", "/host/dotnet")
                .env("HOME", "/host/home")
                .env("LD_LIBRARY_PATH", "/host/lib")
                .env("MPK_PLUGIN", "/host/plugin");
        }
        command.output().map_err(display)
    };
    let first = run_once(false)?;
    ensure(
        first.status.success() && first.stderr.is_empty(),
        &format!(
            "installed successor run failed: {}",
            String::from_utf8_lossy(&first.stderr)
        ),
    )?;
    let second = run_once(true)?;
    ensure(
        second.status.success() && second.stderr.is_empty() && second.stdout == first.stdout,
        "hostile ambient state changed installed successor output",
    )?;
    let report: Value = serde_json::from_slice(&first.stdout).map_err(display)?;
    ensure(
        canonical_line(&report)? == first.stdout,
        "noncanonical installed report",
    )?;
    ensure(
        report["status"] == "active_successor",
        "inactive installed report",
    )?;
    ensure(
        report["languages"]
            .as_array()
            .is_some_and(|languages| languages.len() == 3),
        "installed report did not execute all frontends",
    )?;

    let tampered = installed
        .join("libexec/mpk/bundles")
        .join(GO_FRONTEND_BUNDLE_ID)
        .join("bin/go2vir");
    fs::set_permissions(&tampered, fs::Permissions::from_mode(0o755)).map_err(display)?;
    let mut bytes = fs::read(&tampered).map_err(display)?;
    bytes.push(0);
    fs::write(&tampered, bytes).map_err(display)?;
    fs::set_permissions(&tampered, fs::Permissions::from_mode(0o555)).map_err(display)?;
    let rejected = run_once(false)?;
    ensure(
        !rejected.status.success() && rejected.stdout.is_empty(),
        "tampered installed successor image did not fail closed",
    )?;
    Ok(())
}

fn validate_active_models() -> Result<(), String> {
    let semantic_bytes = read("release/bundles/semantic-profile-registry.json")?;
    let semantic = validate_semantic_profile_registry(&semantic_bytes, RegistryRevision::Revision2)
        .map_err(display)?;
    ensure(
        semantic.identity().registry_sha256() == SEMANTIC_REGISTRY_SHA256,
        "semantic registry hash",
    )?;
    let registry_bytes = read("release/bundles/bundle-registry.json")?;
    let registry =
        validate_successor_release_registry(&registry_bytes, &semantic).map_err(display)?;
    ensure(
        registry.registry_sha256() == ACTIVE_RELEASE_REGISTRY_SHA256
            && registry.registry().frontend_bundles.len() == 3
            && registry.registry().toolchain_bundles.len() == 3
            && registry.registry().tuples.len() == 4,
        "release registry is not the complete successor",
    )?;
    for language in ["go", "rust", "csharp"] {
        validate_successor_bundle_candidate(
            &read(&format!("release/bundles/candidates/{language}.json"))?,
            &semantic,
        )
        .map_err(display)?;
    }
    let semantic_value: Value = serde_json::from_slice(&semantic_bytes).map_err(display)?;
    let csharp = semantic_value["profiles"]
        .as_array()
        .and_then(|profiles| {
            profiles
                .iter()
                .find(|profile| profile["source_language"] == "csharp")
        })
        .ok_or("C# semantic profile is absent")?;
    let contracts = csharp["contracts"]
        .as_object()
        .ok_or("C# contracts are absent")?;
    ensure(
        csharp["entry_sha256"] == CSHARP_PROFILE_ENTRY_SHA256
            && contracts.keys().map(String::as_str).collect::<Vec<_>>()
                == [
                    "ai",
                    "evidence",
                    "frontend",
                    "manifest",
                    "policy",
                    "release",
                    "source_map",
                    "vc",
                    "vir",
                ],
        "C# profile contracts are not the reviewed nine-contract set",
    )?;
    let review = load("develop/migrations/archive/csharp-02-final-review.json")?;
    ensure(
        review["status"] == "reviewed_zero_findings"
            && review["axiom_review"]["new_categories"] == json!([]),
        "review or axiom ledger is not clean",
    )?;
    Ok(())
}

fn validate_installed_topology(root: &Path) -> Result<(), String> {
    let expected = [
        CSHARP_FRONTEND_BUNDLE_ID,
        CSHARP_TOOLCHAIN_BUNDLE_ID,
        GO_FRONTEND_BUNDLE_ID,
        GO_TOOLCHAIN_BUNDLE_ID,
        RUST_FRONTEND_BUNDLE_ID,
        RUST_TOOLCHAIN_BUNDLE_ID,
    ];
    let mut actual = fs::read_dir(root.join("libexec/mpk/bundles"))
        .map_err(display)?
        .map(|entry| entry.map(|value| value.file_name()).map_err(display))
        .collect::<Result<Vec<_>, _>>()?;
    actual.sort();
    let mut expected = expected.map(std::ffi::OsString::from).to_vec();
    expected.sort();
    ensure(actual == expected, "installed bundle set")?;
    ensure(
        fs::read(root.join("share/mpk/bundle-registry.json")).map_err(display)?
            == read("release/bundles/bundle-registry.json")?
            && fs::read(root.join("share/mpk/semantic-profile-registry.json")).map_err(display)?
                == read("release/bundles/semantic-profile-registry.json")?,
        "installed registries differ from active bytes",
    )?;
    Ok(())
}

fn captured_storage(source_root: &Path, manifest: &Value) -> Result<Vec<OwnedInput>, String> {
    manifest["inputs"]
        .as_array()
        .ok_or("manifest inputs are absent")?
        .iter()
        .map(|entry| {
            let kind = match entry["kind"].as_str().ok_or("input kind is absent")? {
                "source" => InputKind::Source,
                "contract" => InputKind::Contract,
                "build_manifest" => InputKind::BuildManifest,
                "lockfile" => InputKind::Lockfile,
                _ => return Err("unknown input kind".to_owned()),
            };
            let path = entry["normalized_path"]
                .as_str()
                .ok_or("input path is absent")?
                .to_owned();
            let disk = source_root.join(&path);
            let bytes = match fs::read(&disk) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match path.as_str() {
                    "go.sum" => Vec::new(),
                    "Cargo.toml" => GENERATED_CARGO_TOML.to_vec(),
                    "Cargo.lock" => GENERATED_CARGO_LOCK.to_vec(),
                    _ => return Err(format!("read {}: {error}", disk.display())),
                },
                Err(error) => return Err(format!("read {}: {error}", disk.display())),
            };
            Ok(OwnedInput { kind, path, bytes })
        })
        .collect()
}

fn captured_refs(storage: &[OwnedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.path,
            bytes: &input.bytes,
        })
        .collect()
}

fn assembler(arguments: &[&str]) -> Result<std::process::Output, String> {
    assembler_command()
        .args(arguments)
        .output()
        .map_err(display)
}

fn assembler_command() -> Command {
    let mut command = Command::new("python3");
    command
        .arg(repository_root().join("scripts/successor_release_bundles.py"))
        .current_dir(repository_root())
        .env_clear()
        .env("PATH", "/usr/local/bin:/usr/bin:/bin")
        .env("PYTHONDONTWRITEBYTECODE", "1");
    command
}

fn load(relative: &str) -> Result<Value, String> {
    serde_json::from_slice(&read(relative)?).map_err(display)
}

fn read(relative: &str) -> Result<Vec<u8>, String> {
    fs::read(repository_root().join(relative)).map_err(display)
}

fn canonical_line(value: &Value) -> Result<Vec<u8>, String> {
    let mut bytes = serde_json::to_vec(value).map_err(display)?;
    bytes.push(b'\n');
    Ok(bytes)
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn ensure(condition: bool, message: &str) -> Result<(), String> {
    condition.then_some(()).ok_or_else(|| message.to_owned())
}

fn display(error: impl std::fmt::Display) -> String {
    error.to_string()
}
