[package]
name = "mpk-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
mpk-cert = { path = "../crates/mpk-cert" }
mpk-kernel = { path = "../crates/mpk-kernel" }

[[bin]]
name = "certificate_decoder"
path = "fuzz_targets/certificate_decoder.rs"
test = false
doc = false
bench = false

[workspace]
