[package]
name = "rust2vir"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false
autoexamples = false
autotests = true
autobenches = false

[lib]
name = "rust2vir_internal"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "rust2vir"
path = "src/bin/rust2vir.rs"
test = false
bench = false

[[bin]]
name = "rust2vir-driver"
path = "src/bin/rust2vir-driver.rs"
test = false
bench = false

[profile.release]
opt-level = 3
debug = 0
strip = "none"
debug-assertions = false
overflow-checks = true
lto = "thin"
panic = "unwind"
incremental = false
codegen-units = 1
