#![allow(dead_code)]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use mpk_cli::successor_policy::{
    run_successor_policy, PolicyVerificationOptions, SuccessorPolicySource,
};
use mpk_vc::semantic_profile_registry::{
    canonical_registry_transport, validate_semantic_profile_registry, RegistryRevision,
    ValidatedSemanticProfileRegistry,
};
use mpk_vc::successor_source_artifacts::{
    import_successor_source_manifest_json, import_successor_source_map_json,
    import_successor_vir_json, successor_contract_hash_value, successor_source_manifest_hash_value,
    successor_source_map_hash_value, successor_vir_hash_value, SuccessorSourceManifestStage,
    SuccessorSourceManifestValidationContext, SuccessorSourceMapValidationContext,
    ValidatedSuccessorSourceManifest, ValidatedSuccessorSourceMap, ValidatedSuccessorVir,
};
use mpk_vc::successor_vc::{
    emit_successor_vc_skeleton, generate_successor_vc, SuccessorVcSource, ValidatedSuccessorVc,
    ValidatedSuccessorVcSkeleton,
};
use mpk_vc::{
    canonical_json_bytes, input_set_hash, parse_strict_json, sha256_raw_file_bytes, CapturedInput,
    InputEntry, InputKind, ReleaseRegistryIdentity, SourceReference, StrictJsonLimits,
    SyntheticPermission,
};
use serde_json::{json, Value};

pub(super) const ZERO_SHA256: &str =
    "0000000000000000000000000000000000000000000000000000000000000000";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";
pub(super) const CSHARP_FUNCTION: &str = "Vector.RequiredChecks::Identity(i32)->i32";
const CSHARP_SOURCE: &[u8] =
    include_bytes!("../../../../fixtures/csharp/policy/source/src/Required.cs");
pub(super) const CSHARP_CONTRACT: &[u8] =
    include_bytes!("../../../../fixtures/csharp/policy/source/contracts/identity.json");
const GO_SOURCE: &[u8] = b"package arith\n\nfunc Identity(x int64) int64 { return x }\n";
const UPDATE_FIXTURES_ENV: &str = "MPK_UPDATE_CSHARP_POLICY_FIXTURES";
const FIXTURE_ROOT: &str = "fixtures/csharp/policy";

pub(super) struct OwnedCapturedInput {
    kind: InputKind,
    normalized_path: String,
    bytes: Vec<u8>,
}

pub(super) struct ValidatedSource {
    pub(super) storage: Vec<OwnedCapturedInput>,
    pub(super) vir: ValidatedSuccessorVir,
    pub(super) source_map: ValidatedSuccessorSourceMap,
    pub(super) manifest: ValidatedSuccessorSourceManifest,
}

pub(super) struct GeneratedPair {
    pub(super) vc: ValidatedSuccessorVc,
    pub(super) skeleton: ValidatedSuccessorVcSkeleton,
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    fs::read(repository_root().join(relative.as_ref()))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.as_ref().display()))
}

pub(super) fn load(relative: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&read(relative)).expect("checked-in JSON")
}

pub(super) fn canonical(value: &Value) -> Vec<u8> {
    let encoded = serde_json::to_vec(value).expect("JSON serializes");
    let strict = parse_strict_json(
        &encoded,
        StrictJsonLimits::new(268_435_456, 268_435_456, 768, 1_048_576),
    )
    .expect("strict JSON");
    canonical_json_bytes(&strict).expect("canonical JSON")
}

pub(super) fn registry() -> ValidatedSemanticProfileRegistry {
    validate_semantic_profile_registry(
        &read("release/bundles/semantic-profile-registry.json"),
        RegistryRevision::Revision2,
    )
    .expect("revision-2 semantic registry")
}

pub(super) fn candidate_registry() -> ValidatedSemanticProfileRegistry {
    let vector = load("develop/specs/vectors/semantic-profile-registry-v3.json");
    validate_semantic_profile_registry(
        &canonical_registry_transport(&vector["registry"])
            .expect("canonical revision-3 semantic registry"),
        RegistryRevision::Revision3,
    )
    .expect("inactive revision-3 semantic registry")
}

fn input_kind(value: &Value) -> InputKind {
    match value.as_str().expect("input kind") {
        "source" => InputKind::Source,
        "contract" => InputKind::Contract,
        "build_manifest" => InputKind::BuildManifest,
        "lockfile" => InputKind::Lockfile,
        other => panic!("unknown input kind {other}"),
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = input_kind(&entry["kind"]);
            let normalized_path = entry["normalized_path"]
                .as_str()
                .expect("normalized input path")
                .to_owned();
            let path = repository_root().join(source_root).join(&normalized_path);
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match kind {
                    InputKind::BuildManifest if normalized_path == "Cargo.toml" => {
                        GENERATED_CARGO_TOML.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "Cargo.lock" => {
                        GENERATED_CARGO_LOCK.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "go.sum" => Vec::new(),
                    _ => panic!("read captured input {}: {error}", path.display()),
                },
                Err(error) => panic!("read captured input {}: {error}", path.display()),
            };
            assert_eq!(entry["size_bytes"], bytes.len() as u64);
            assert_eq!(entry["sha256"], sha256_raw_file_bytes(&bytes).to_hex());
            OwnedCapturedInput {
                kind,
                normalized_path,
                bytes,
            }
        })
        .collect()
}

pub(super) fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.normalized_path,
            bytes: &input.bytes,
        })
        .collect()
}

pub(super) fn staged_source(
    registry: &ValidatedSemanticProfileRegistry,
    artifact_root: &str,
    source_root: &str,
) -> ValidatedSource {
    let vir_bytes = read(format!("{artifact_root}/vir.json"));
    let map_bytes = read(format!("{artifact_root}/source-map.json"));
    let manifest_bytes = read(format!("{artifact_root}/source-manifest.frontend.json"));
    let manifest_value: Value = serde_json::from_slice(&manifest_bytes).expect("manifest JSON");
    let map_value: Value = serde_json::from_slice(&map_bytes).expect("source-map JSON");
    let storage = captured_storage(source_root, &manifest_value);
    let captured = captured_refs(&storage);
    let vir = import_successor_vir_json(&vir_bytes, registry).expect("successor VIR");
    let synthetic_permissions = map_value["entries"]
        .as_array()
        .expect("source-map entries")
        .iter()
        .filter(|entry| entry["origin"]["kind"] == "synthetic")
        .map(|entry| {
            let reason = entry["origin"]["reason"]
                .as_str()
                .expect("synthetic reason");
            assert_eq!(reason, "go.control_flow_join");
            SyntheticPermission {
                reference: serde_json::from_value::<SourceReference>(entry["reference"].clone())
                    .expect("synthetic reference"),
                reason: reason.to_owned(),
            }
        })
        .collect::<Vec<_>>();
    let source_map = import_successor_source_map_json(
        &map_bytes,
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &synthetic_permissions,
        },
    )
    .expect("successor source map");
    let release_registry = serde_json::from_value::<ReleaseRegistryIdentity>(
        manifest_value["release_registry"].clone(),
    )
    .expect("release-registry identity");
    let manifest = import_successor_source_manifest_json(
        &manifest_bytes,
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("successor source manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

pub(super) fn csharp_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let context =
        load("release/bundles/candidates/csharp.json")["tuples"][0]["semantic_context"].clone();
    let i32_type = json!({"kind":"bv","width":32,"signed":true});
    let mut contract = json!({
        "semantic_context": context.clone(),
        "unit_id": "payment-policy",
        "function_id": CSHARP_FUNCTION,
        "requires": [],
        "ensures": [{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies": [],
        "panic": "forbidden",
        "termination": "total",
        "loops": [],
        "contract_hash": ZERO_SHA256
    });
    contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&contract)
            .expect("C# contract hash")
            .as_str()
            .to_owned(),
    );
    let mut vir = json!({
        "schema":"mpk.vir.v1",
        "semantic_context":context,
        "units":[{
            "id":"payment-policy",
            "name":"payment-policy",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":CSHARP_FUNCTION,
                "unit_id":"payment-policy",
                "name":"Identity",
                "params":[{"id":"arg0","type":i32_type.clone()}],
                "results":[{"id":"result0","type":i32_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":contract,
                "features_used":[]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir["vir_hash"] = Value::String(
        successor_vir_hash_value(&vir)
            .expect("C# VIR hash")
            .as_str()
            .to_owned(),
    );
    let vir = import_successor_vir_json(&canonical(&vir), registry).expect("C# successor VIR");

    let storage = vec![
        OwnedCapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/identity.json".to_owned(),
            bytes: CSHARP_CONTRACT.to_vec(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Required.cs".to_owned(),
            bytes: CSHARP_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"src/Required.cs",
            "start":0,
            "end":CSHARP_SOURCE.len()
        })
    };
    let mut source_map = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":[{
            "reference":{"kind":"function","unit_id":"payment-policy","function_id":CSHARP_FUNCTION},
            "origin":origin()
        },{
            "reference":{
                "kind":"terminator",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":"bb0"
            },
            "origin":origin()
        }],
        "source_map_hash":ZERO_SHA256
    });
    source_map["source_map_hash"] = Value::String(
        successor_source_map_hash_value(&source_map)
            .expect("C# source-map hash")
            .as_str()
            .to_owned(),
    );
    let source_map = import_successor_source_map_json(
        &canonical(&source_map),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("C# successor source map");

    let inputs = storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release_registry_value = load("release/bundles/bundle-registry.json");
    let release_registry = ReleaseRegistryIdentity {
        schema: release_registry_value["schema"]
            .as_str()
            .expect("release schema")
            .to_owned(),
        id: release_registry_value["id"]
            .as_str()
            .expect("release ID")
            .to_owned(),
        registry_sha256: release_registry_value["registry_sha256"]
            .as_str()
            .expect("release hash")
            .to_owned(),
    };
    let mut manifest = json!({
        "schema":"mpk.source_manifest.v1",
        "semantic_context":vir.module().semantic_context(),
        "selection":{
            "schema":"mpk.selection.csharp_methods.v0",
            "value":{
                "compilation":"payment-policy",
                "contracts":["contracts/identity.json"],
                "methods":[CSHARP_FUNCTION],
                "sources":["src/Required.cs"]
            }
        },
        "limit_profile":"mpk.vir.limits.v0",
        "release_registry":release_registry,
        "toolchain":{
            "bundle_id":"toolchain.csharp.roslyn-5_6_0.dotnet-10_0_11.candidate.v1",
            "distribution_sha256":"6cc7711334ffcd9216cfb241e1508491abb62a13b01ebc9b2d883a1ace9627bc",
            "components":[]
        },
        "frontend":{
            "bundle_id":"frontend.csharp.csharp2vir.candidate.v1",
            "name":"csharp2vir",
            "version":"0.1.0",
            "binary_sha256":"0783dc269c152ad1b13e77f42f9eff6f6891002c65890bc1445f2fe1a1a0410d",
            "subordinate_binaries":[]
        },
        "units":[{"identity":"payment-policy","name":"payment-policy","kind":"compilation"}],
        "target":{"id":"linux-x64","pointer_width":64},
        "inputs":inputs,
        "input_set_hash":input_set_hash(&inputs).expect("input-set hash").as_str(),
        "vir_hash":vir.hash().as_str(),
        "source_map_hash":source_map.hash().as_str(),
        "source_manifest_hash":ZERO_SHA256
    });
    manifest["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&manifest)
            .expect("C# source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("C# successor manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

pub(super) fn java_source(
    registry: &ValidatedSemanticProfileRegistry,
    case: &Value,
) -> ValidatedSource {
    let envelope: Value =
        serde_json::from_str(case["envelope"].as_str().expect("Java frontend envelope"))
            .expect("Java frontend envelope JSON");
    let storage = case["captured_inputs"]
        .as_array()
        .expect("Java captured inputs")
        .iter()
        .map(|input| OwnedCapturedInput {
            kind: match input["kind"].as_str().expect("Java input kind") {
                "contract" => InputKind::Contract,
                "source" => InputKind::Source,
                other => panic!("unexpected Java input kind {other}"),
            },
            normalized_path: input["path"].as_str().expect("Java input path").to_owned(),
            bytes: input["text"]
                .as_str()
                .expect("Java input bytes")
                .as_bytes()
                .to_vec(),
        })
        .collect::<Vec<_>>();
    let captured = captured_refs(&storage);
    let vir = import_successor_vir_json(&canonical(&envelope["ir"]["value"]), registry)
        .expect("Java successor VIR");
    let source_map = import_successor_source_map_json(
        &canonical(&envelope["source_map"]),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("Java successor source map");
    let release_registry = serde_json::from_value::<ReleaseRegistryIdentity>(
        envelope["source_manifest"]["release_registry"].clone(),
    )
    .expect("Java release-registry identity");
    let manifest = import_successor_source_manifest_json(
        &canonical(&envelope["source_manifest"]),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("Java successor manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

pub(super) fn java_source_with_callee_preconditions(
    registry: &ValidatedSemanticProfileRegistry,
    case: &Value,
) -> ValidatedSource {
    let mut derived = case.clone();
    let mut envelope: Value = serde_json::from_str(
        derived["envelope"]
            .as_str()
            .expect("Java frontend envelope"),
    )
    .expect("Java frontend envelope JSON");
    let self_equal_raw = json!({
        "op":"eq",
        "args":[
            {"parameter":"arg"},
            {"parameter":"arg"}
        ]
    });
    for captured in derived["captured_inputs"]
        .as_array_mut()
        .expect("Java captured inputs")
        .iter_mut()
        .filter(|input| input["kind"] == "contract")
    {
        let mut raw: Value =
            serde_json::from_str(captured["text"].as_str().expect("Java raw contract bytes"))
                .expect("Java raw contract JSON");
        let parameter = match raw["method"].as_str().expect("Java contract method") {
            "vector.Case::f(int)->int" => "x",
            "vector.Case::g(int)->int" => "y",
            other => panic!("unexpected Java call.direct method {other}"),
        };
        let mut require = self_equal_raw.clone();
        require["args"][0]["parameter"] = Value::String(parameter.to_owned());
        require["args"][1]["parameter"] = Value::String(parameter.to_owned());
        raw["requires"] = json!([require]);
        let mut bytes = canonical(&raw);
        bytes.push(b'\n');
        captured["text"] = Value::String(String::from_utf8(bytes).expect("contract UTF-8"));
    }

    let functions = envelope["ir"]["value"]["units"][0]["functions"]
        .as_array_mut()
        .expect("Java VIR functions");
    let mut contract_hashes = BTreeMap::new();
    for function in functions.iter_mut() {
        function["contracts"]["requires"] = json!([{
            "op":"eq",
            "lhs":{"var":"arg0"},
            "rhs":{"var":"arg0"}
        }]);
        function["contracts"]["contract_hash"] = Value::String(ZERO_SHA256.to_owned());
        let hash = successor_contract_hash_value(&function["contracts"])
            .expect("derived Java contract hash")
            .as_str()
            .to_owned();
        function["contracts"]["contract_hash"] = Value::String(hash.clone());
        contract_hashes.insert(
            function["id"]
                .as_str()
                .expect("derived Java function ID")
                .to_owned(),
            hash,
        );
    }
    for instruction in functions
        .iter_mut()
        .flat_map(|function| function["blocks"].as_array_mut().expect("Java blocks"))
        .flat_map(|block| {
            block["instructions"]
                .as_array_mut()
                .expect("Java instructions")
        })
        .filter(|instruction| instruction["kind"] == "CallStatic")
    {
        let callee = instruction["function"]
            .as_str()
            .expect("Java static callee");
        instruction["contract_hash"] = Value::String(
            contract_hashes
                .get(callee)
                .expect("derived Java callee contract")
                .clone(),
        );
    }
    envelope["ir"]["value"]["vir_hash"] = Value::String(ZERO_SHA256.to_owned());
    let vir_hash = successor_vir_hash_value(&envelope["ir"]["value"])
        .expect("derived Java VIR hash")
        .as_str()
        .to_owned();
    envelope["ir"]["value"]["vir_hash"] = Value::String(vir_hash.clone());
    envelope["ir"]["sha256"] = Value::String(vir_hash.clone());

    envelope["source_map"]["source_ir_hash"] = Value::String(vir_hash.clone());
    envelope["source_map"]["source_map_hash"] = Value::String(ZERO_SHA256.to_owned());
    let map_hash = successor_source_map_hash_value(&envelope["source_map"])
        .expect("derived Java source-map hash")
        .as_str()
        .to_owned();
    envelope["source_map"]["source_map_hash"] = Value::String(map_hash.clone());

    for entry in envelope["source_manifest"]["inputs"]
        .as_array_mut()
        .expect("Java manifest inputs")
    {
        let path = entry["normalized_path"]
            .as_str()
            .expect("Java manifest input path");
        let captured = derived["captured_inputs"]
            .as_array()
            .expect("Java captured inputs")
            .iter()
            .find(|captured| captured["path"] == path)
            .expect("derived Java captured input");
        let bytes = captured["text"]
            .as_str()
            .expect("derived Java input bytes")
            .as_bytes();
        entry["size_bytes"] = json!(bytes.len());
        entry["sha256"] = Value::String(sha256_raw_file_bytes(bytes).to_hex());
    }
    let inputs =
        serde_json::from_value::<Vec<InputEntry>>(envelope["source_manifest"]["inputs"].clone())
            .expect("derived Java manifest inputs");
    envelope["source_manifest"]["input_set_hash"] = Value::String(
        input_set_hash(&inputs)
            .expect("derived Java input-set hash")
            .as_str()
            .to_owned(),
    );
    envelope["source_manifest"]["vir_hash"] = Value::String(vir_hash);
    envelope["source_manifest"]["source_map_hash"] = Value::String(map_hash);
    envelope["source_manifest"]["source_manifest_hash"] = Value::String(ZERO_SHA256.to_owned());
    envelope["source_manifest"]["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&envelope["source_manifest"])
            .expect("derived Java source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let mut envelope_bytes = canonical(&envelope);
    envelope_bytes.push(b'\n');
    derived["envelope"] =
        Value::String(String::from_utf8(envelope_bytes).expect("derived envelope UTF-8"));
    java_source(registry, &derived)
}

pub(super) fn go_identity_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let baseline = load("fixtures/vir-go/frontend/basic-arith/source-manifest.frontend.json");
    let context = baseline["semantic_context"].clone();
    let package = "github.com/finitefield-org/mpk/fixtures/go-basic/positive/arith";
    let function = format!("{package}.Identity");
    let i64_type = json!({"kind":"bv","width":64,"signed":true});
    let mut contract = json!({
        "semantic_context":context.clone(),
        "unit_id":package,
        "function_id":function,
        "requires":[],
        "ensures":[{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies":[],
        "panic":"forbidden",
        "termination":"total",
        "loops":[],
        "contract_hash":ZERO_SHA256
    });
    contract["contract_hash"] = Value::String(
        successor_contract_hash_value(&contract)
            .expect("Go contract hash")
            .as_str()
            .to_owned(),
    );
    let mut vir = json!({
        "schema":"mpk.vir.v1",
        "semantic_context":context,
        "units":[{
            "id":package,
            "name":"arith",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":function,
                "unit_id":package,
                "name":"Identity",
                "params":[{"id":"arg0","type":i64_type.clone()}],
                "results":[{"id":"result0","type":i64_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":contract,
                "features_used":[]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir["vir_hash"] = Value::String(
        successor_vir_hash_value(&vir)
            .expect("Go VIR hash")
            .as_str()
            .to_owned(),
    );
    let vir = import_successor_vir_json(&canonical(&vir), registry).expect("Go successor VIR");

    let storage = vec![
        OwnedCapturedInput {
            kind: InputKind::BuildManifest,
            normalized_path: "go.mod".to_owned(),
            bytes: read("fixtures/go-basic/go.mod"),
        },
        OwnedCapturedInput {
            kind: InputKind::Lockfile,
            normalized_path: "go.sum".to_owned(),
            bytes: Vec::new(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "positive/arith/arith.go".to_owned(),
            bytes: GO_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"positive/arith/arith.go",
            "start":0,
            "end":GO_SOURCE.len()
        })
    };
    let mut source_map = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":[{
            "reference":{"kind":"function","unit_id":package,"function_id":function},
            "origin":origin()
        },{
            "reference":{
                "kind":"terminator",
                "unit_id":package,
                "function_id":function,
                "block":"bb0"
            },
            "origin":origin()
        }],
        "source_map_hash":ZERO_SHA256
    });
    source_map["source_map_hash"] = Value::String(
        successor_source_map_hash_value(&source_map)
            .expect("Go source-map hash")
            .as_str()
            .to_owned(),
    );
    let source_map = import_successor_source_map_json(
        &canonical(&source_map),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("Go successor source map");
    let inputs = storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release_registry =
        serde_json::from_value::<ReleaseRegistryIdentity>(baseline["release_registry"].clone())
            .expect("Go release-registry identity");
    let mut manifest = baseline;
    manifest["selection"]["value"]["function"] = Value::String(function);
    manifest["inputs"] = serde_json::to_value(&inputs).expect("Go inputs");
    manifest["input_set_hash"] = Value::String(
        input_set_hash(&inputs)
            .expect("Go input-set hash")
            .as_str()
            .to_owned(),
    );
    manifest["vir_hash"] = Value::String(vir.hash().as_str().to_owned());
    manifest["source_map_hash"] = Value::String(source_map.hash().as_str().to_owned());
    manifest["source_manifest_hash"] = Value::String(ZERO_SHA256.to_owned());
    manifest["source_manifest_hash"] = Value::String(
        successor_source_manifest_hash_value(&manifest)
            .expect("Go source-manifest hash")
            .as_str()
            .to_owned(),
    );
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("Go successor manifest");
    ValidatedSource {
        storage,
        vir,
        source_map,
        manifest,
    }
}

pub(super) fn profile_contract(profile: &str, field: &str) -> Value {
    match (profile, field) {
        ("go", "vc") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.vc.go_fixed.v0",
            "value":{
                "contract_profile_id":"mpk.go.contract.v0",
                "required_check_profile_id":"mpk.go.fixed.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        ("rust", "vc") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.vc.rust_checked.v0",
            "value":{
                "contract_profile_id":"mpk.rust.contract.v0",
                "required_check_profile_id":"mpk.rust.checked.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        ("go", "policy") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.policy.go_fixed.v0",
            "value":{
                "axiom_profile":"zero-axiom",
                "checker_profile":"mvp-strict",
                "strategy_profile":"payment-policy-alpha"
            }
        }),
        ("rust", "policy") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.policy.rust_checked.v0",
            "value":{
                "axiom_profile":"mvp-theory",
                "checker_profile":"mvp-strict",
                "strategy_profile":"payment-policy-rust-alpha"
            }
        }),
        ("go", "evidence") => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.evidence.go_fixed.v0",
            "value":{
                "proof_authority":"certificate_only",
                "recipe_profile_id":"mpk.go.evidence_recipe.v0",
                "require_reference_checker":true,
                "require_source_free_check":true
            }
        }),
        ("rust", "evidence") => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.evidence.rust_checked.v0",
            "value":{
                "proof_authority":"certificate_only",
                "recipe_profile_id":"mpk.rust.evidence_recipe.v0",
                "require_reference_checker":true,
                "require_source_free_check":true
            }
        }),
        ("csharp", field) => load("develop/specs/vectors/csharp-profile-v0.json")
            ["profile_contracts"]
            .as_array()
            .expect("C# profile contracts")
            .iter()
            .find(|contract| contract["field"] == field)
            .unwrap_or_else(|| panic!("missing C# {field} contract"))["envelope"]
            .clone(),
        ("java", field) => load("develop/specs/vectors/java-profile-v0.json")["profile_contracts"]
            .as_array()
            .expect("Java profile contracts")
            .iter()
            .find(|contract| contract["field"] == field)
            .unwrap_or_else(|| panic!("missing Java {field} contract"))["envelope"]
            .clone(),
        other => panic!("unknown profile contract {other:?}"),
    }
}

pub(super) fn generated_pair(
    registry: &ValidatedSemanticProfileRegistry,
    source: &ValidatedSource,
    vc_contract: &Value,
) -> GeneratedPair {
    let linked = SuccessorVcSource {
        registry,
        vir: &source.vir,
        manifest: &source.manifest,
        profile_contract: vc_contract,
    };
    let vc = generate_successor_vc(linked).expect("successor VC");
    let skeleton = emit_successor_vc_skeleton(&vc, linked).expect("successor skeleton");
    GeneratedPair { vc, skeleton }
}

pub(super) fn source_boundary<'a>(
    registry: &'a ValidatedSemanticProfileRegistry,
    source: &'a ValidatedSource,
    pair: &'a GeneratedPair,
    policy_contract: &'a Value,
    evidence_contract: &'a Value,
    captured: &'a [CapturedInput<'a>],
) -> SuccessorPolicySource<'a> {
    SuccessorPolicySource {
        registry,
        vir: &source.vir,
        source_map: &source.source_map,
        frontend_manifest: &source.manifest,
        vc: &pair.vc,
        skeleton: &pair.skeleton,
        policy_contract,
        evidence_contract,
        captured_inputs: captured,
    }
}

pub(super) fn fixture(relative: &str, generated: &[u8]) {
    let path = repository_root().join(FIXTURE_ROOT).join(relative);
    if std::env::var_os(UPDATE_FIXTURES_ENV).as_deref() == Some(std::ffi::OsStr::new("1")) {
        fs::create_dir_all(path.parent().expect("fixture parent")).expect("create fixture parent");
        fs::write(&path, generated).expect("write fixture");
    }
    assert_eq!(
        fs::read(&path).unwrap_or_else(|error| panic!("read {}: {error}", path.display())),
        generated,
        "fixture drift: {}",
        path.display()
    );
}

pub(super) fn hex_fixture(bytes: &[u8]) -> Vec<u8> {
    let mut encoded = String::with_capacity(bytes.len() * 2 + 1);
    for byte in bytes {
        use std::fmt::Write;
        write!(&mut encoded, "{byte:02x}").expect("write to String");
    }
    encoded.push('\n');
    encoded.into_bytes()
}

pub(super) struct NamedPolicyRun {
    pub profile: &'static str,
    pub run: mpk_cli::successor_policy::SuccessorPolicyRun,
}

pub(super) fn validated_registry() -> ValidatedSemanticProfileRegistry {
    registry()
}

pub(super) fn ai_contract(profile: &str) -> Value {
    match profile {
        "go" => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.ai.go_fixed.v0",
            "value":{
                "display_language":"Go",
                "projection_profile_id":"mpk.go.ai_projection.v0",
                "proof_authority":false,
                "redaction_profile_id":"minimal-v1",
                "source_access":false
            }
        }),
        "rust" => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.ai.rust_checked.v0",
            "value":{
                "display_language":"Rust",
                "projection_profile_id":"mpk.rust.ai_projection.v0",
                "proof_authority":false,
                "redaction_profile_id":"minimal-v1",
                "source_access":false
            }
        }),
        "csharp" => profile_contract("csharp", "ai"),
        "java" => profile_contract("java", "ai"),
        other => panic!("unknown AI profile contract {other}"),
    }
}

pub(super) fn complete_successor_policy_runs(
    registry: &ValidatedSemanticProfileRegistry,
) -> Vec<NamedPolicyRun> {
    [
        ("go", "", ""),
        (
            "rust",
            "fixtures/rust-basic/positive/module-calls/artifacts",
            "rust-tools/rust2vir/testdata/positive/module-calls/source",
        ),
        ("csharp", "", ""),
    ]
    .into_iter()
    .map(|(profile, artifacts, sources)| {
        let source = match profile {
            "go" => go_identity_source(registry),
            "rust" => staged_source(registry, artifacts, sources),
            "csharp" => csharp_source(registry),
            _ => unreachable!("closed profile list"),
        };
        let vc_contract = profile_contract(profile, "vc");
        let policy_contract = profile_contract(profile, "policy");
        let evidence_contract = profile_contract(profile, "evidence");
        let pair = generated_pair(registry, &source, &vc_contract);
        let captured = captured_refs(&source.storage);
        let run = run_successor_policy(
            source_boundary(
                registry,
                &source,
                &pair,
                &policy_contract,
                &evidence_contract,
                &captured,
            ),
            PolicyVerificationOptions {
                strict: true,
                update_fixtures: false,
            },
        )
        .unwrap_or_else(|error| panic!("{profile} successor policy: {error}"));
        NamedPolicyRun { profile, run }
    })
    .collect()
}

pub(super) fn repository_path(relative: impl AsRef<Path>) -> PathBuf {
    repository_root().join(relative)
}

pub(super) fn checked_in_json(relative: impl AsRef<Path>) -> Value {
    load(relative)
}
