import hashlib,json,pathlib,shutil
b=pathlib.Path(__file__).parent;r=pathlib.Path('/private/tmp/mpk-w09-refreeze-consumer-continuation');frozen=pathlib.Path('/private/tmp/mpk-w09-refreeze-metadata-integration');prefix=pathlib.Path('develop/migrations/csharp-03/ordinary-foundation');rows=[];owners=[];h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();backup=b/'ordinary-before-6-7-completed';backup.mkdir(exist_ok=False)
for number in ['6','7']:
 receipt=json.loads((b/f'completed-ordinary-owner-stages-{number}.json').read_bytes())
 selected=[x for x in receipt['files'] if number=='6' or x['family']!='control-predicates']
 owner_names=sorted({x['family'] for x in selected});owners.extend([dict(run=number,family=family) for family in owner_names])
 for row in selected:
  path=prefix/row['family']/row['original_path'];old=r/path;fresh=b/f'ordinary-regeneration-{number}/goldens'/row['family']/row['generated_path'];assert h(old)==row['original_raw_sha256'] and h(fresh)==row['generated_raw_sha256']
  assert h(frozen/path)==h(old)
  if fresh.suffix=='.hex':assert row['certificate_bytes_preserved'] and old.read_bytes()==fresh.read_bytes();continue
  assert fresh.suffix=='.json' and row['semantic_metadata_preserved'];prior=backup/row['family']/row['original_path'];prior.parent.mkdir(parents=True,exist_ok=True);shutil.copyfile(old,prior);old.write_bytes(fresh.read_bytes());assert h(old)==row['generated_raw_sha256'];rows.append(dict(run=number,path=str(path),original_raw_sha256=row['original_raw_sha256'],promoted_raw_sha256=h(old)))
receipt={'schema':'mpk.csharp_practical.t01_w09.completed_owner_promotion.v1','status':'passed_exact_promotion_of_13_completed_source_owners','source_commit':'957bd9c8db1adfa4b29594a4ef8b822b57d2193c','owners':owners,'metadata_files_promoted':rows,'certificate_files_byte_preserved':146,'selection_reason':'Only the two completed binding guard/order owners and eleven completed string/data/ownership/fold owners are promoted. Control predicates still require changed-name graph/dual acceptance and their integrated dependency replay; the remaining nine phase-6 source owners still run from the unchanged checkout. Every promoted metadata file has a complete successful owner stage and exact semantic comparison, and all 146 corresponding certificates retain exact bytes.','original_application_proof_ids_pending':987,'full_t01_gate':'deferred_to_final_W10','full_t06_gate':'deferred_to_W12'};(b/'completed-definition-owner-promotion.json').write_text(json.dumps(receipt,sort_keys=True,indent=2)+'\n');assert len(owners)==13;print(json.dumps({'owners':len(owners),'metadata_files':len(rows),'certificate_files_preserved':146}))
