import gzip,hashlib,json,pathlib,shutil
b=pathlib.Path(__file__).parent;r=pathlib.Path('/private/tmp/mpk-w09-refreeze-consumer-continuation');out=r/'develop/migrations/csharp-03/probes/boolean-proof-elimination-refreeze/ordinary-metadata-6-7-completed';out.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();promotion=json.loads((b/'completed-definition-owner-promotion.json').read_bytes());stages=[]
for number in ['6','7']:
 manifest=json.loads((b/f'ordinary-source-manifest-{number}.json').read_bytes());frozen=pathlib.Path('/private/tmp/mpk-w09-refreeze-metadata-integration');assert all(h(frozen/p)==sha for p,sha in manifest['hashes'].items())
 for name in [f'ordinary-source-manifest-{number}.json',f'ordinary-regeneration-plan-{number}.json',f'run-ordinary-regeneration-{number}.py',f'completed-ordinary-owner-stages-{number}.json']:shutil.copyfile(b/name,out/name)
 state=json.loads((b/f'ordinary-regeneration-{number}/status.json').read_bytes())
 for owner in [x for x in promotion['owners'] if x['run']==number]:
  stage=next(s for s in state['stages'] if s['destination']==owner['family']);assert stage['exit_code']==0 and stage['test_counts']==['1'];label=stage['stage'];source=b/f'ordinary-regeneration-{number}'/(label+'.log.txt');assert h(source)==stage['log_sha256'];target=out/'logs'/f'{number}-{label}.log.txt';target.parent.mkdir(exist_ok=True);shutil.copyfile(source,target);stages.append(dict(run=number,**stage))
 failed=state['stages'][-1] if state['status']=='failed' else None
 if failed:
  source=b/f'ordinary-regeneration-{number}'/(failed['stage']+'.log.txt');assert failed['exit_code']==101 and h(source)==failed['log_sha256'];target=out/'failures'/('initial-'+failed['stage']+'.log.txt.gz');target.parent.mkdir(exist_ok=True)
  with target.open('wb') as f,gzip.GzipFile(fileobj=f,mode='wb',mtime=0) as gz:gz.write(source.read_bytes())
  assert hashlib.sha256(gzip.decompress(target.read_bytes())).hexdigest()==failed['log_sha256'];(target.parent/'failure.json').write_text(json.dumps({'stage':failed,'parent_status':state['status'],'source_inputs_unchanged_at_checkpoint':True,'archive_sha256':h(target),'raw_log_sha256':failed['log_sha256'],'reason':'Integrated predicates compare the complete current control-edge metadata; that dependency still carries the previous foundation linkage. Regenerate its actual source owner before retrying.'},sort_keys=True,indent=2)+'\n')
for name in ['completed-definition-owner-promotion.json','promote-completed-definition-owners.py','compare-completed-ordinary-owner-stages.py','save-completed-definition-owner-checkpoint.py']:shutil.copyfile(b/name,out/name)
receipt={'schema':'mpk.csharp_practical.t01_w09.completed_definition_owner_checkpoint.v1','status':'passed_13_actual_source_owners_exact_metadata_promotion_and_146_unchanged_certificates','source_commit':promotion['source_commit'],'selection_reason':promotion['selection_reason'],'owners':stages,'metadata_files_promoted':70,'certificate_files_byte_preserved':146,'checkpoint_owner_corpora_total':52,'checkpoint_certificate_total':958,'checkpoint_exact_byte_retention_total':943,'checkpoint_prior_name_graph_rebinding_dual_acceptances':15,'original_application_proof_ids_pending':987,'post_promotion_pin_checks':'pending','remaining_linkage':'binding reconstruction and remaining phase-6 owners running; changed control/contract names, nested JSON wrapper lineage and integrated dependencies pending','full_t01_gate':'deferred_to_final_W10','full_t06_gate':'deferred_to_W12'};(out/'receipt.json').write_text(json.dumps(receipt,sort_keys=True,indent=2)+'\n');print(json.dumps({k:v for k,v in receipt.items() if k not in ['owners','selection_reason']}))
