[package]
name = "rust2vir-fuzz"
version = "0.0.0"
edition = "2021"
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { version = "=0.4.9" }
rust2vir_internal = { package = "rust2vir", path = "/mpk/frontend", version = "=0.1.0" }

[[bin]]
name = "driver_protocol"
path = "fuzz_targets/driver_protocol.rs"
test = false
doc = false
bench = false

[[bin]]
name = "rust_contract"
path = "fuzz_targets/rust_contract.rs"
test = false
doc = false
bench = false
