from datetime import datetime,timezone
from hashlib import sha256
from pathlib import Path
import json,shutil
repo=Path('/private/tmp/mpk-w09-packed-pattern-proofs');root=Path('/private/tmp/mpk-w09-identity-proofs');source=root/'server-linux/final';base=repo/'develop/migrations/csharp-03/ordinary-foundation/verification-logs/identity-proofs';audit=json.loads((source/'final-audit.json').read_bytes());status=json.loads((source/'status.json').read_bytes());execution=json.loads((source/'fetch-execution.json').read_bytes())
assert audit['status']=='passed_independent_terminal_linux_audit' and audit['commit']=='1b32c1860967b34a04c67956e70de7233aaecafa'
assert status['status']=='passed_targeted_tests_lint_format' and execution['exit_code']==0
assert audit['git_blob_files_verified']==1016 and len(audit['exported_file_hashes'])==47
assert status['exported_hashes']==json.loads((base/'expected-certificates.json').read_bytes())
assert not (base/'server-linux').exists();shutil.copytree(root/'server-linux',base/'server-linux')
for name in ('fetch-linux.py','preserve-linux.py'):shutil.copyfile(root/name,base/'tool-sources'/name)
p=base/'verification.json';v=json.loads(p.read_bytes());v.update(status='passed_scoped_local_dual_checker_linux_verification',recorded_at=datetime.now(timezone.utc).isoformat(),linux_verification='passed independent terminal audit of exact public source 1b32c186; target test, Clippy and format; 1016 Git blobs, four harness files, all logs/test binary and 47 exact exports verified',linux_receipt='server-linux/final/status.json',linux_audit='server-linux/final/final-audit.json',linux_source_commit=audit['commit']);p.write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
p=repo/'develop/migrations/csharp-03/ordinary-foundation/unit-7-identity-proofs-review.md';s=p.read_text();s=s.replace('Published-source Linux verification remains pending. See\nverification-logs/identity-proofs/verification.json.','Exact public-source Linux verification at 1b32c186 passes the targeted test,\nClippy and format. Its independent terminal audit verifies 1,016 source/fixture\nGit blobs, four harness files, all logs and the actual test binary, and all 47\nexports against the local outputs. This remains scoped evidence; W09 and the\napplication assembly are incomplete. See\nverification-logs/identity-proofs/verification.json.');p.write_text(s)
p=repo/'develop/docs/08_csharp_practical_subset_design-todo.md';s=p.read_text();s=s.replace('Published-source Linux verification remains\npending. All 987 original application proof IDs, 25 generic operations, native','Exact public-source Linux verification passes the same targeted test,\nClippy and format; its terminal audit verifies 1,016 Git blobs, four harness\nfiles, all logs/test binary and 47 exact exports. All 987 original application\nproof IDs, 25 generic operations, native');p.write_text(s)
p=repo/'develop/migrations/csharp-03/ordinary-foundation/w09-completion-audit.json';d=json.loads(p.read_bytes());u=next(u for u in d['units'] if u['unit']==7);checkpoint=u['original_identity_projection_checkpoint'];checkpoint.update(status='passed_scoped_local_same_byte_dual_checker_and_linux_checks',scope='All original identity projection sequents retain receiver/domain/complete equality operands on the unchanged foundation proof prefix; 44 unchanged contexts reuse exact prior checker evidence. Exact public-source Linux target test, Clippy and format pass independent terminal audit of 1016 Git blobs and all 47 local-matching exports. All 987 application proof IDs and 456 remaining binding sequents stay pending; this does not complete W09.');p.write_text(json.dumps(d,indent=2)+'\n');print(json.dumps(v))
