use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};
use std::process::Command;

const EXPECTED_MANIFEST: &[u8] = br#"[package]
name = "rust2vir"
version = "0.1.0"
edition = "2021"
publish = false
autobins = false
autoexamples = false
autotests = true
autobenches = false

[lib]
name = "rust2vir_internal"
path = "src/lib.rs"
doctest = false

[[bin]]
name = "rust2vir"
path = "src/bin/rust2vir.rs"
test = false
bench = false

[[bin]]
name = "rust2vir-driver"
path = "src/bin/rust2vir-driver.rs"
test = false
bench = false

[profile.release]
opt-level = 3
debug = 0
strip = "none"
debug-assertions = false
overflow-checks = true
lto = "thin"
panic = "unwind"
incremental = false
codegen-units = 1
"#;

const EXPECTED_LOCK: &[u8] = br#"# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "rust2vir"
version = "0.1.0"
"#;

const EXPECTED_TOOLCHAIN: &[u8] = br#"[toolchain]
channel = "nightly-2025-06-01"
components = ["clippy", "llvm-tools-preview", "rustc-dev", "rustfmt"]
targets = ["i686-unknown-linux-gnu", "x86_64-unknown-linux-gnu"]
profile = "minimal"
"#;

fn package_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).to_path_buf()
}

#[test]
fn frozen_project_files_have_the_exact_registered_bytes() {
    let root = package_root();
    let cases = [
        ("Cargo.toml", EXPECTED_MANIFEST),
        ("Cargo.lock", EXPECTED_LOCK),
        ("rust-toolchain.toml", EXPECTED_TOOLCHAIN),
    ];
    for (relative, expected) in cases {
        let bytes = fs::read(root.join(relative)).expect("read frozen project file");
        assert_eq!(bytes, expected, "{relative}");
        assert_eq!(bytes.last(), Some(&b'\n'), "{relative}");
    }
}

#[test]
fn version_identity_is_stable() {
    assert_eq!(
        rust2vir_internal::version_line("rust2vir"),
        "rust2vir 0.1.0-profile-v1-staging (rustc 4d08223c054cf5a56d9761ca925fd46ffebe7115)"
    );
}

#[test]
fn binaries_expose_only_the_frozen_version_identity() {
    for (binary, name) in [
        (env!("CARGO_BIN_EXE_rust2vir"), "rust2vir"),
        (env!("CARGO_BIN_EXE_rust2vir-driver"), "rust2vir-driver"),
    ] {
        let output = Command::new(binary).arg("--version").output().unwrap();
        assert!(output.status.success(), "{name}");
        assert!(output.stderr.is_empty(), "{name}");
        assert_eq!(
            String::from_utf8(output.stdout).unwrap(),
            format!(
                "{name} 0.1.0-profile-v1-staging (rustc 4d08223c054cf5a56d9761ca925fd46ffebe7115)\n"
            )
        );
    }
}

#[test]
fn driver_requires_the_fixed_private_request_before_compiler_analysis() {
    let executable = std::env::current_exe().unwrap();
    let fake_rustc = executable
        .parent()
        .unwrap()
        .join(format!("fake-rustc-{}", std::process::id()));
    fs::write(
        &fake_rustc,
        b"#!/bin/sh\nprintf '%s\\n' 'commit-hash: 0000000000000000000000000000000000000000'\n",
    )
    .unwrap();
    fs::set_permissions(&fake_rustc, fs::Permissions::from_mode(0o755)).unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_rust2vir-driver"))
        .arg(&fake_rustc)
        .output()
        .unwrap();
    fs::remove_file(&fake_rustc).unwrap();

    assert_eq!(output.status.code(), Some(1));
    assert!(output.stdout.is_empty());
    assert_eq!(output.stderr, b"RUST_FRONTEND_DRIVER_PROTOCOL_FILESYSTEM\n");
}
