#![allow(internal_features)]
#![feature(rustc_private)]

extern crate rustc_abi;
extern crate rustc_ast;
extern crate rustc_driver;
extern crate rustc_hir;
extern crate rustc_index;
extern crate rustc_interface;
extern crate rustc_middle;
extern crate rustc_session;
extern crate rustc_span;
extern crate rustc_target;

#[path = "../src/rustc_driver.rs"]
mod rustc_driver_adapter;

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;

use rust2vir_internal::cli::{
    LowerRequest, ReleaseArguments, RustSelection, RustTarget, SEMANTIC_PROFILE,
};
use rust2vir_internal::driver_protocol::{
    construct_request, encode_lowered, parse_output_transport, DriverComponentIdentity,
    DriverReleaseIdentity, DriverStatus,
};
use rust2vir_internal::emit::success_envelope;
use rust2vir_internal::file_loader::SnapshotFileLoader;
use rust2vir_internal::json::{self, JsonValue};
use rust2vir_internal::manifest;
use rust2vir_internal::mir_access::{
    MIR_DIALECT_SHA256, MIR_DIALECT_SUMMARY, MIR_PROFILE_ID, MIR_QUERY,
};
use rust2vir_internal::module_closure;
use rust2vir_internal::preflight;
use rust2vir_internal::sha256::{digest, hex};
use rust2vir_internal::snapshot::Snapshot;
use rust2vir_internal::{EXPECTED_RUSTC_COMMIT, EXPECTED_RUSTC_RELEASE};

const UPDATE_ENV: &str = "MPK_UPDATE_RUST_POSITIVE_CORPUS";
const SHA_FRONTEND: &str = "dd8715c3a54e0e02a940cfac5b61ed87d0ca8afb9b6259e853c0dd700e32f344";
const SHA_DRIVER: &str = "84d2c05f7c9e49b68c5eb79dde3566791d52f2603baa10e2bcf8f9f4ad7c3da7";
const SHA_TOOLCHAIN: &str = "86dab73dadd3a3184064e7d7da7e878562eba4cfc4c8a969bc8f44a5e865c90a";
const REGISTRY_SHA256: &str = "7877c7c04fae912815713a8a7f6f9900198721ea572788f6f48d1dbe3f00afbd";
const CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";
const CATEGORIES: &[&str] = &[
    "boolean_short_circuit",
    "signed_unsigned_max",
    "checked_addition",
    "minimum_literal_negation",
    "division",
    "cross_width_shifts",
    "array_bounds",
    "struct_move",
    "early_return",
    "cross_module_calls",
    "usize_targets",
    "multi_file_closure",
];
static NEXT_TEMP: AtomicU64 = AtomicU64::new(0);

#[derive(Clone, Copy)]
struct Case {
    id: &'static str,
    fixture: &'static str,
    artifact_dir: &'static str,
    category: &'static str,
    target: RustTarget,
    function: &'static str,
    contracts: &'static [&'static str],
    excluded_sources: &'static [&'static str],
    required_kinds: &'static [&'static str],
    required_ops: &'static [&'static str],
    required_checks: &'static [&'static str],
    required_features: &'static [&'static str],
    minimum_functions: usize,
}

const CASES: &[Case] = &[
    Case {
        id: "boolean-short-circuit",
        fixture: "boolean-short-circuit",
        artifact_dir: "artifacts",
        category: "boolean_short_circuit",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::boolean_short_circuit",
        contracts: &[
            "contracts/guarded-and.json",
            "contracts/guarded-or.json",
            "contracts/identity.json",
            "contracts/negation.json",
            "contracts/selected.json",
        ],
        excluded_sources: &[],
        required_kinds: &["BinOp", "CallStatic", "UnaryOp"],
        required_ops: &["bv_udiv", "not"],
        required_checks: &["divisor_nonzero"],
        required_features: &["branch", "call_static"],
        minimum_functions: 5,
    },
    Case {
        id: "signed-unsigned-max",
        fixture: "signed-unsigned-max",
        artifact_dir: "artifacts",
        category: "signed_unsigned_max",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::max_values",
        contracts: &["contracts/helper.json", "contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["BinOp", "CallStatic"],
        required_ops: &["signed_ge", "signed_gt", "unsigned_gt"],
        required_checks: &[],
        required_features: &["branch", "call_static"],
        minimum_functions: 2,
    },
    Case {
        id: "checked-addition",
        fixture: "checked-addition",
        artifact_dir: "artifacts",
        category: "checked_addition",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::checked_addition",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["BinOp"],
        required_ops: &["bv_add"],
        required_checks: &["integer_no_overflow"],
        required_features: &[],
        minimum_functions: 1,
    },
    Case {
        id: "minimum-negation",
        fixture: "minimum-negation",
        artifact_dir: "artifacts",
        category: "minimum_literal_negation",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::minimum_or_negate",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["Const", "UnaryOp"],
        required_ops: &["bv_neg"],
        required_checks: &["integer_no_overflow"],
        required_features: &["branch"],
        minimum_functions: 1,
    },
    Case {
        id: "signed-division",
        fixture: "signed-division",
        artifact_dir: "artifacts",
        category: "division",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::signed_division",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["BinOp"],
        required_ops: &["bv_sdiv"],
        required_checks: &["divisor_nonzero", "signed_divrem_representable"],
        required_features: &[],
        minimum_functions: 1,
    },
    Case {
        id: "cross-width-shifts",
        fixture: "cross-width-shifts",
        artifact_dir: "artifacts",
        category: "cross_width_shifts",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::cross_width_shifts",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["BinOp"],
        required_ops: &["bv_lshr", "bv_shl"],
        required_checks: &["shift_count_less_than_width", "shift_count_nonnegative"],
        required_features: &[],
        minimum_functions: 1,
    },
    Case {
        id: "array-bounds",
        fixture: "array-bounds",
        artifact_dir: "artifacts",
        category: "array_bounds",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::array_bounds",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["Index"],
        required_ops: &[],
        required_checks: &["index_in_bounds"],
        required_features: &["array"],
        minimum_functions: 1,
    },
    Case {
        id: "struct-move",
        fixture: "struct-move",
        artifact_dir: "artifacts",
        category: "struct_move",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::construct_move_read",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["BinOp", "Copy", "Field", "MakeStruct"],
        required_ops: &["bv_add"],
        required_checks: &["integer_no_overflow"],
        required_features: &["struct"],
        minimum_functions: 1,
    },
    Case {
        id: "early-return",
        fixture: "early-return",
        artifact_dir: "artifacts",
        category: "early_return",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::early_return",
        contracts: &["contracts/selected.json"],
        excluded_sources: &[],
        required_kinds: &["UnaryOp"],
        required_ops: &["bv_neg"],
        required_checks: &["integer_no_overflow"],
        required_features: &["branch"],
        minimum_functions: 1,
    },
    Case {
        id: "module-calls",
        fixture: "module-calls",
        artifact_dir: "artifacts",
        category: "cross_module_calls",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::cross_module",
        contracts: &[
            "contracts/private.json",
            "contracts/public.json",
            "contracts/selected.json",
        ],
        excluded_sources: &[],
        required_kinds: &["CallStatic"],
        required_ops: &[],
        required_checks: &[],
        required_features: &["call_static"],
        minimum_functions: 3,
    },
    Case {
        id: "usize-i686",
        fixture: "usize-targets",
        artifact_dir: "artifacts/i686",
        category: "usize_targets",
        target: RustTarget::I686UnknownLinuxGnu,
        function: "vector::usize_index",
        contracts: &["contracts/i686.json"],
        excluded_sources: &[],
        required_kinds: &["Index"],
        required_ops: &[],
        required_checks: &["index_in_bounds"],
        required_features: &["array"],
        minimum_functions: 1,
    },
    Case {
        id: "usize-x86_64",
        fixture: "usize-targets",
        artifact_dir: "artifacts/x86_64",
        category: "usize_targets",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::usize_index",
        contracts: &["contracts/x86_64.json"],
        excluded_sources: &[],
        required_kinds: &["Index"],
        required_ops: &[],
        required_checks: &["index_in_bounds"],
        required_features: &["array"],
        minimum_functions: 1,
    },
    Case {
        id: "multi-file-closure",
        fixture: "multi-file-closure",
        artifact_dir: "artifacts",
        category: "multi_file_closure",
        target: RustTarget::X86_64UnknownLinuxGnu,
        function: "vector::multi_file",
        contracts: &[
            "contracts/private.json",
            "contracts/public.json",
            "contracts/selected.json",
        ],
        excluded_sources: &["src/unrelated.rs"],
        required_kinds: &["CallStatic"],
        required_ops: &[],
        required_checks: &[],
        required_features: &["call_static"],
        minimum_functions: 3,
    },
];

#[derive(Clone, Debug, Eq, PartialEq)]
struct FrontendArtifacts {
    envelope: Vec<u8>,
    vir: Vec<u8>,
    source_map: Vec<u8>,
    source_manifest: Vec<u8>,
    private_request: Vec<u8>,
    private_result: Vec<u8>,
    raw_lowering: Vec<u8>,
    raw_source_map: Vec<u8>,
    captured_sources: Vec<String>,
    function_count: usize,
    instruction_count: usize,
    safety_check_count: usize,
    call_count: usize,
    source_map_entries: usize,
}

struct TempPackage {
    root: PathBuf,
}

impl TempPackage {
    fn new(case: &Case, run: usize) -> Self {
        let serial = NEXT_TEMP.fetch_add(1, Ordering::Relaxed);
        let root = std::env::temp_dir().join(format!(
            "rust2vir-positive-{}-{run}-{}-{serial}",
            case.id,
            std::process::id()
        ));
        let source = root.join("source");
        fs::create_dir_all(source.join("src")).expect("create positive source root");
        fs::create_dir_all(source.join("contracts")).expect("create positive contracts root");
        fs::create_dir(root.join("private")).expect("create snapshot parent");
        fs::create_dir(root.join("target")).expect("create rustc output root");
        fs::write(source.join("Cargo.toml"), CARGO_TOML).expect("write Cargo.toml");
        fs::write(source.join("Cargo.lock"), CARGO_LOCK).expect("write Cargo.lock");
        copy_tree(&fixture_root(case).join("source"), &source);
        Self { root }
    }

    fn source(&self) -> PathBuf {
        self.root.join("source")
    }

    fn private(&self) -> PathBuf {
        self.root.join("private")
    }

    fn target(&self) -> PathBuf {
        self.root.join("target")
    }
}

impl Drop for TempPackage {
    fn drop(&mut self) {
        if self.root.exists() {
            fs::remove_dir_all(&self.root).expect("remove positive corpus package");
        }
    }
}

#[test]
fn positive_corpus_is_successor_only_snapshot_backed_and_byte_deterministic() {
    assert_case_inventory();
    let update = std::env::var_os(UPDATE_ENV).is_some();
    let expected_root = fixture_base();
    let output_root = expected_root.clone();
    let mut index_cases = Vec::with_capacity(CASES.len());

    for case in CASES {
        let first = compile_case(case, 0);
        let second = compile_case(case, 1);
        assert_eq!(first, second, "{} clean compiler runs", case.id);
        assert_case_coverage(case, &first);
        for bytes in [
            first.envelope.as_slice(),
            first.vir.as_slice(),
            first.source_map.as_slice(),
            first.source_manifest.as_slice(),
        ] {
            assert_no_path_leakage(case, bytes);
        }

        let artifact_base = format!("{}/{}", case.fixture, case.artifact_dir);
        let artifacts = [
            (
                "frontend_envelope",
                "frontend-envelope.json",
                &first.envelope,
            ),
            ("vir", "vir.json", &first.vir),
            ("source_map", "source-map.json", &first.source_map),
            (
                "source_manifest_frontend",
                "source-manifest.frontend.json",
                &first.source_manifest,
            ),
            (
                "private_request",
                "driver-request.json",
                &first.private_request,
            ),
            (
                "private_result",
                "driver-result.json",
                &first.private_result,
            ),
            ("raw_lowering", "raw-lowering.json", &first.raw_lowering),
            (
                "raw_source_map",
                "raw-source-map.json",
                &first.raw_source_map,
            ),
        ];
        let mut artifact_rows = Vec::new();
        for (kind, name, bytes) in artifacts {
            let relative = format!("{artifact_base}/{name}");
            if update {
                write_generated(&output_root.join(&relative), bytes);
            } else {
                assert_eq!(
                    fs::read(expected_root.join(&relative))
                        .unwrap_or_else(|error| panic!("read {relative}: {error}")),
                    *bytes,
                    "{relative}"
                );
            }
            artifact_rows.push(artifact_value(kind, &relative, bytes));
        }
        index_cases.push(case_index_value(case, &first, artifact_rows));
    }

    let index = frontend_index(index_cases);
    if update {
        write_generated(&output_root.join("frontend-index.json"), &index);
    } else {
        assert_eq!(
            fs::read(expected_root.join("frontend-index.json")).expect("read frontend index"),
            index
        );
    }
}

fn compile_case(case: &Case, run: usize) -> FrontendArtifacts {
    let package = TempPackage::new(case, run);
    let request = lower_request(case, package.source());
    let validated = manifest::validate(
        &request,
        preflight::run(&request).unwrap_or_else(|error| panic!("{} preflight: {error:?}", case.id)),
    )
    .unwrap_or_else(|error| panic!("{} manifest: {error:?}", case.id));
    let (closure, _) = module_closure::discover(validated)
        .unwrap_or_else(|error| panic!("{} module closure: {error:?}", case.id));
    let captured_sources = closure
        .source_inputs()
        .map(|input| input.normalized_path.as_str().to_owned())
        .collect::<Vec<_>>();
    for excluded in case.excluded_sources {
        assert!(
            !captured_sources.iter().any(|path| path == excluded),
            "{} captured excluded source {excluded}",
            case.id
        );
    }
    let snapshot = Snapshot::create(&package.private(), &closure)
        .unwrap_or_else(|error| panic!("{} snapshot: {error:?}", case.id));
    let private_request = construct_request(&request, snapshot.inputs(), &release_identity())
        .unwrap_or_else(|error| panic!("{} private request: {error:?}", case.id));
    let loader = SnapshotFileLoader::from_request(
        snapshot.path(),
        closure.library_root.as_str(),
        &private_request,
    )
    .unwrap_or_else(|error| panic!("{} source loader: {error:?}", case.id));
    let lowering = rustc_driver_adapter::lower_primary(
        &compiler_arguments(case, &snapshot, &closure.library_root, &package.target()),
        &private_request,
        Arc::new(loader),
    )
    .unwrap_or_else(|error| panic!("{} compiler lowering: {error:?}", case.id));
    let raw_lowering = json::canonical(&lowering.raw_lowering).expect("canonical raw lowering");
    let raw_source_map =
        json::canonical(&lowering.raw_source_map).expect("canonical raw source map");
    let driver_transport = encode_lowered(
        &private_request,
        lowering.raw_lowering,
        lowering.raw_source_map,
    )
    .unwrap_or_else(|error| panic!("{} private output: {error:?}", case.id));
    let output = parse_output_transport(
        &driver_transport,
        &private_request,
        DriverStatus::Lowered.exit_code(),
        false,
    )
    .unwrap_or_else(|error| panic!("{} validate private output: {error:?}", case.id));
    let envelope = success_envelope(&request, &private_request, &output, false)
        .unwrap_or_else(|_| panic!("{} public envelope", case.id));
    let public = json::parse(&envelope[..envelope.len() - 1], envelope.len())
        .unwrap_or_else(|error| panic!("{} parse envelope: {error:?}", case.id));
    let root = public.as_object().expect("frontend envelope object");
    let vir_value = &root["ir"].as_object().expect("IR envelope")["value"];
    let source_map_value = &root["source_map"];
    let source_manifest_value = &root["source_manifest"];
    let vir = json::canonical(vir_value).expect("canonical VIR");
    let source_map = json::canonical(source_map_value).expect("canonical source map");
    let source_manifest = json::canonical(source_manifest_value).expect("canonical manifest");
    let functions = functions(vir_value).collect::<Vec<_>>();
    let instructions = functions
        .iter()
        .flat_map(|function| instructions(function))
        .collect::<Vec<_>>();
    let safety_check_count = instructions
        .iter()
        .map(|instruction| {
            member(instruction, "safety_checks")
                .as_array()
                .unwrap()
                .len()
        })
        .sum();
    let call_count = instructions
        .iter()
        .filter(|instruction| member(instruction, "kind").as_str() == Some("CallStatic"))
        .count();
    let source_map_entries = member(source_map_value, "entries")
        .as_array()
        .unwrap()
        .len();
    FrontendArtifacts {
        envelope,
        vir,
        source_map,
        source_manifest,
        private_request: private_request.transport().to_vec(),
        private_result: driver_transport,
        raw_lowering,
        raw_source_map,
        captured_sources,
        function_count: functions.len(),
        instruction_count: instructions.len(),
        safety_check_count,
        call_count,
        source_map_entries,
    }
}

fn assert_case_coverage(case: &Case, artifacts: &FrontendArtifacts) {
    let vir = json::parse(&artifacts.vir, artifacts.vir.len()).expect("parse generated VIR");
    let functions = functions(&vir).collect::<Vec<_>>();
    assert!(
        functions.len() >= case.minimum_functions,
        "{} function closure",
        case.id
    );
    assert!(functions
        .iter()
        .any(|function| { member(function, "id").as_str() == Some(case.function) }));
    let instructions = functions
        .iter()
        .flat_map(|function| instructions(function))
        .collect::<Vec<_>>();
    let kinds = instructions
        .iter()
        .map(|instruction| member(instruction, "kind").as_str().unwrap())
        .collect::<BTreeSet<_>>();
    let operations = instructions
        .iter()
        .filter_map(|instruction| optional_member(instruction, "op").and_then(JsonValue::as_str))
        .collect::<BTreeSet<_>>();
    let checks = instructions
        .iter()
        .flat_map(|instruction| member(instruction, "safety_checks").as_array().unwrap())
        .map(|check| member(check, "kind").as_str().unwrap())
        .collect::<BTreeSet<_>>();
    let features = functions
        .iter()
        .flat_map(|function| member(function, "features_used").as_array().unwrap())
        .map(|feature| feature.as_str().unwrap())
        .collect::<BTreeSet<_>>();
    for required in case.required_kinds {
        assert!(
            kinds.contains(required),
            "{} missing instruction {required}",
            case.id
        );
    }
    for required in case.required_ops {
        assert!(
            operations.contains(required),
            "{} missing operation {required}",
            case.id
        );
    }
    for required in case.required_checks {
        assert!(
            checks.contains(required),
            "{} missing safety check {required}",
            case.id
        );
    }
    for required in case.required_features {
        assert!(
            features.contains(required),
            "{} missing feature {required}",
            case.id
        );
    }
    if case.category == "minimum_literal_negation" {
        let minimum = instructions
            .iter()
            .find(|instruction| {
                member(instruction, "kind").as_str() == Some("Const")
                    && optional_member(instruction, "value")
                        .and_then(|value| optional_member(value, "int"))
                        .and_then(|value| optional_member(value, "value"))
                        .and_then(JsonValue::as_str)
                        == Some("-128")
            })
            .expect("canonical i8 minimum Const");
        assert!(member(minimum, "safety_checks")
            .as_array()
            .unwrap()
            .is_empty());
    }
    if case.category == "usize_targets" {
        let selected = functions
            .iter()
            .find(|function| member(function, "id").as_str() == Some(case.function))
            .unwrap();
        let index = member(selected, "params").as_array().unwrap()[1]
            .as_object()
            .unwrap()["type"]
            .as_object()
            .unwrap()["width"]
            .integer()
            .unwrap();
        assert_eq!(index, i64::from(case.target.pointer_width()));
    }
}

fn assert_case_inventory() {
    assert_eq!(CASES.len(), 13);
    let ids = CASES.iter().map(|case| case.id).collect::<BTreeSet<_>>();
    assert_eq!(ids.len(), CASES.len());
    let categories = CASES
        .iter()
        .map(|case| case.category)
        .collect::<BTreeSet<_>>();
    assert_eq!(categories, CATEGORIES.iter().copied().collect());
    assert_eq!(
        CASES
            .iter()
            .filter(|case| case.category == "usize_targets")
            .map(|case| case.target.pointer_width())
            .collect::<BTreeSet<_>>(),
        BTreeSet::from([32, 64])
    );
}

fn lower_request(case: &Case, source_root: PathBuf) -> LowerRequest {
    LowerRequest {
        source_root,
        selection: RustSelection {
            package: "vector".to_owned(),
            crate_name: "vector".to_owned(),
            kind: "lib",
            function: case.function.to_owned(),
        },
        semantic_profile: SEMANTIC_PROFILE,
        target: case.target,
        release: ReleaseArguments {
            frontend_bundle_id: rust2vir_internal::successor::FRONTEND_ID.to_owned(),
            frontend_sha256: SHA_FRONTEND.to_owned(),
            release_registry_id: "mpk.release.registry.v1".to_owned(),
            release_registry_sha256: REGISTRY_SHA256.to_owned(),
            toolchain_bundle_id: rust2vir_internal::successor::TOOLCHAIN_ID.to_owned(),
            toolchain_root: PathBuf::from("/not-emitted/toolchain"),
            toolchain_distribution_sha256: SHA_TOOLCHAIN.to_owned(),
            driver: PathBuf::from("/not-emitted/rust2vir-driver"),
            driver_sha256: SHA_DRIVER.to_owned(),
        },
        contracts: case
            .contracts
            .iter()
            .map(|path| (*path).to_owned())
            .collect(),
    }
}

fn release_identity() -> DriverReleaseIdentity {
    DriverReleaseIdentity {
        frontend_bundle_id: rust2vir_internal::successor::FRONTEND_ID.to_owned(),
        frontend_binary_sha256: SHA_FRONTEND.to_owned(),
        driver_binary_sha256: SHA_DRIVER.to_owned(),
        toolchain_bundle_id: rust2vir_internal::successor::TOOLCHAIN_ID.to_owned(),
        toolchain_distribution_sha256: SHA_TOOLCHAIN.to_owned(),
        toolchain_components: vec![
            component(
                "executable",
                "cargo",
                EXPECTED_RUSTC_RELEASE,
                "4ab49080934031ce3b87b1a8792e685f99819e8a3f537f110a339d7331f1dcea",
                None,
            ),
            component(
                "content",
                "native-runtime",
                "nightly-2025-06-01",
                "6d8ebe276575c5019abdc97051baf78e166354249eca4d6b65f638c5fb171005",
                None,
            ),
            component(
                "content",
                "rust-compiler-runtime",
                "nightly-2025-06-01",
                "7698b22d00656113340f692fd9212a1494077fd470f924948945e690da401292",
                None,
            ),
            component(
                "content",
                "rust-target-i686",
                "nightly-2025-06-01",
                "8f606996b669eb0f4314309d145d93c6eeaad8b261791584387bcff46ccafb0a",
                None,
            ),
            component(
                "content",
                "rust-target-x86_64",
                "nightly-2025-06-01",
                "d8c45533753e17186cefde3e0830f7b358a8b4c818eb732d8814a31861335a15",
                None,
            ),
            component(
                "executable",
                "rustc",
                EXPECTED_RUSTC_RELEASE,
                "a7c2179d845e8f40305bace1657b903f10d149cc6d72b0c08ecef75487418922",
                Some(EXPECTED_RUSTC_COMMIT),
            ),
        ],
    }
}

fn component(
    kind: &str,
    name: &str,
    release: &str,
    sha256: &str,
    commit_hash: Option<&str>,
) -> DriverComponentIdentity {
    DriverComponentIdentity {
        kind: kind.to_owned(),
        name: name.to_owned(),
        release: release.to_owned(),
        sha256: sha256.to_owned(),
        commit_hash: commit_hash.map(str::to_owned),
    }
}

fn compiler_arguments(
    case: &Case,
    snapshot: &Snapshot,
    library_root: &rust2vir_internal::path::PortablePath,
    output: &Path,
) -> Vec<String> {
    let source = snapshot.input_path(library_root);
    [
        "/mpk/toolchain/bin/rustc".to_owned(),
        "--crate-name".to_owned(),
        "vector".to_owned(),
        "--edition=2021".to_owned(),
        source.to_str().expect("UTF-8 snapshot source").to_owned(),
        "--crate-type".to_owned(),
        "lib".to_owned(),
        "--emit=metadata".to_owned(),
        "--out-dir".to_owned(),
        output.to_str().expect("UTF-8 output path").to_owned(),
        "--target".to_owned(),
        case.target.id().to_owned(),
        "-C".to_owned(),
        "overflow-checks=yes".to_owned(),
        "-C".to_owned(),
        "panic=abort".to_owned(),
        "-C".to_owned(),
        "debug-assertions=no".to_owned(),
        "-C".to_owned(),
        "opt-level=0".to_owned(),
        "-Z".to_owned(),
        "mir-opt-level=0".to_owned(),
        "--remap-path-prefix=/mpk/input=.".to_owned(),
    ]
    .into_iter()
    .collect()
}

fn frontend_index(cases: Vec<JsonValue>) -> Vec<u8> {
    json::canonical(&JsonValue::Object(BTreeMap::from([
        (
            "accepted_mir".to_owned(),
            JsonValue::Object(BTreeMap::from([
                (
                    "compiler_commit".to_owned(),
                    string(EXPECTED_RUSTC_COMMIT),
                ),
                ("dialect_sha256".to_owned(), string(MIR_DIALECT_SHA256)),
                ("dialect_summary".to_owned(), string(MIR_DIALECT_SUMMARY)),
                ("findings".to_owned(), JsonValue::Array(Vec::new())),
                ("profile_id".to_owned(), string(MIR_PROFILE_ID)),
                ("query".to_owned(), string(MIR_QUERY)),
            ])),
        ),
        (
            "categories".to_owned(),
            JsonValue::Array(CATEGORIES.iter().map(|value| string(value)).collect()),
        ),
        ("cases".to_owned(), JsonValue::Array(cases)),
        ("deterministic_runs".to_owned(), number(2)),
        (
            "private_protocol".to_owned(),
            JsonValue::Object(BTreeMap::from([
                (
                    "payload_hash_domain".to_owned(),
                    string("MPK-RUST-DRIVER-PAYLOAD-1.0"),
                ),
                (
                    "raw_lowering_schema".to_owned(),
                    string("mpk.rust.driver.lowering.v1"),
                ),
                (
                    "raw_source_map_schema".to_owned(),
                    string("mpk.rust.driver.raw_source_map.v1"),
                ),
                (
                    "request_hash_domain".to_owned(),
                    string("MPK-RUST-DRIVER-REQUEST-1.0"),
                ),
                (
                    "request_schema".to_owned(),
                    string("mpk.rust.driver.request.v1"),
                ),
                (
                    "result_schema".to_owned(),
                    string("mpk.rust.driver.v1"),
                ),
            ])),
        ),
        (
            "release_registry".to_owned(),
            JsonValue::Object(BTreeMap::from([
                ("id".to_owned(), string("mpk.release.registry.v1")),
                ("registry_sha256".to_owned(), string(REGISTRY_SHA256)),
                (
                    "schema".to_owned(),
                    string("mpk.release.bundle_registry.v1"),
                ),
            ])),
        ),
        (
            "schema".to_owned(),
            string("mpk.rust.positive_frontend_corpus.v1"),
        ),
        (
            "semantic_contexts".to_owned(),
            JsonValue::Array(vec![
                rust2vir_internal::successor::semantic_context("i686-unknown-linux-gnu", 32),
                rust2vir_internal::successor::semantic_context("x86_64-unknown-linux-gnu", 64),
            ]),
        ),
        (
            "update_command".to_owned(),
            string("MPK_UPDATE_RUST_POSITIVE_CORPUS=1 CARGO_NET_OFFLINE=true CARGO_TARGET_DIR=rust-tools/rust2vir/target LD_LIBRARY_PATH=release/build-input-cache/rust/2fa1c788c00506390b422ba01fc101b99001be5bc1146f2a43c340742f7d3cf6/toolchain/lib RUSTC=release/build-input-cache/rust/2fa1c788c00506390b422ba01fc101b99001be5bc1146f2a43c340742f7d3cf6/toolchain/bin/rustc release/build-input-cache/rust/2fa1c788c00506390b422ba01fc101b99001be5bc1146f2a43c340742f7d3cf6/toolchain/bin/cargo test --manifest-path rust-tools/rust2vir/Cargo.toml --locked --test positive_corpus"),
        ),
    ])))
    .expect("canonical frontend index")
}

fn case_index_value(
    case: &Case,
    artifacts: &FrontendArtifacts,
    artifact_rows: Vec<JsonValue>,
) -> JsonValue {
    JsonValue::Object(BTreeMap::from([
        ("artifacts".to_owned(), JsonValue::Array(artifact_rows)),
        (
            "captured_sources".to_owned(),
            JsonValue::Array(
                artifacts
                    .captured_sources
                    .iter()
                    .map(|path| string(path))
                    .collect(),
            ),
        ),
        ("category".to_owned(), string(case.category)),
        (
            "contracts".to_owned(),
            JsonValue::Array(case.contracts.iter().map(|path| string(path)).collect()),
        ),
        ("diagnostics".to_owned(), JsonValue::Array(Vec::new())),
        ("fixture".to_owned(), string(case.fixture)),
        ("frontend_phase".to_owned(), string("emission")),
        ("frontend_status".to_owned(), string("ir-lowered")),
        (
            "function_count".to_owned(),
            number(artifacts.function_count),
        ),
        ("id".to_owned(), string(case.id)),
        (
            "instruction_count".to_owned(),
            number(artifacts.instruction_count),
        ),
        ("call_count".to_owned(), number(artifacts.call_count)),
        (
            "pointer_width".to_owned(),
            number(case.target.pointer_width()),
        ),
        (
            "safety_check_count".to_owned(),
            number(artifacts.safety_check_count),
        ),
        (
            "selection".to_owned(),
            rust2vir_internal::successor::selection_envelope("vector", "vector", case.function),
        ),
        (
            "semantic_context".to_owned(),
            rust2vir_internal::successor::semantic_context(
                case.target.id(),
                case.target.pointer_width(),
            ),
        ),
        (
            "source_map_entries".to_owned(),
            number(artifacts.source_map_entries),
        ),
        ("target_id".to_owned(), string(case.target.id())),
        (
            "source_root".to_owned(),
            string(&format!(
                "rust-tools/rust2vir/testdata/positive/{}/source",
                case.fixture
            )),
        ),
    ]))
}

fn artifact_value(kind: &str, path: &str, bytes: &[u8]) -> JsonValue {
    JsonValue::Object(BTreeMap::from([
        ("bytes".to_owned(), number(bytes.len())),
        ("kind".to_owned(), string(kind)),
        ("path".to_owned(), string(path)),
        ("sha256".to_owned(), string(&hex(&digest(bytes)))),
    ]))
}

fn fixture_base() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("testdata/positive")
}

fn fixture_root(case: &Case) -> PathBuf {
    fixture_base().join(case.fixture)
}

fn copy_tree(source: &Path, destination: &Path) {
    let mut entries = fs::read_dir(source)
        .unwrap_or_else(|error| panic!("read {}: {error}", source.display()))
        .map(|entry| entry.expect("fixture entry"))
        .collect::<Vec<_>>();
    entries.sort_by_key(|entry| entry.file_name());
    for entry in entries {
        let target = destination.join(entry.file_name());
        if entry.file_type().expect("fixture type").is_dir() {
            fs::create_dir_all(&target).expect("create fixture directory");
            copy_tree(&entry.path(), &target);
        } else {
            fs::copy(entry.path(), target).expect("copy fixture input");
        }
    }
}

fn write_generated(path: &Path, bytes: &[u8]) {
    fs::create_dir_all(path.parent().expect("generated artifact parent"))
        .expect("create generated artifact parent");
    fs::write(path, bytes).expect("write generated corpus artifact");
}

fn functions(vir: &JsonValue) -> impl Iterator<Item = &JsonValue> {
    member(vir, "units")
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|unit| member(unit, "functions").as_array().unwrap())
}

fn instructions(function: &JsonValue) -> impl Iterator<Item = &JsonValue> {
    member(function, "blocks")
        .as_array()
        .unwrap()
        .iter()
        .flat_map(|block| member(block, "instructions").as_array().unwrap())
}

fn member<'a>(value: &'a JsonValue, name: &str) -> &'a JsonValue {
    &value.as_object().expect("JSON object")[name]
}

fn optional_member<'a>(value: &'a JsonValue, name: &str) -> Option<&'a JsonValue> {
    value.as_object().and_then(|object| object.get(name))
}

fn string(value: &str) -> JsonValue {
    JsonValue::String(value.to_owned())
}

fn number(value: impl ToString) -> JsonValue {
    JsonValue::Number(value.to_string())
}

fn assert_no_path_leakage(case: &Case, bytes: &[u8]) {
    let text = std::str::from_utf8(bytes).expect("artifact UTF-8");
    for forbidden in [
        "/root/",
        "/tmp/",
        "/mpk/input",
        "/mpk/toolchain",
        "/not-emitted/",
        "rust2vir-positive-",
    ] {
        assert!(!text.contains(forbidden), "{} leaked {forbidden}", case.id);
    }
}
