//! Primary conformance owner for inactive `mpk.ai.api.v2` staging.

use std::fs;
use std::path::{Path, PathBuf};

use mpk_core::TermNode;
use mpk_kernel::verify_certificate_bytes;
use mpk_vc::semantic_profile_registry::{
    validate_semantic_profile_registry, RegistryRevision, ValidatedSemanticProfileRegistry,
};
use mpk_vc::successor_source_artifacts::{
    import_successor_source_manifest_json, import_successor_source_map_json,
    import_successor_vir_json, successor_contract_hash_value, successor_source_manifest_hash_value,
    successor_source_map_hash_value, successor_vir_hash_value, SuccessorSourceManifestStage,
    SuccessorSourceManifestValidationContext, SuccessorSourceMapValidationContext,
    ValidatedSuccessorSourceManifest, ValidatedSuccessorSourceMap, ValidatedSuccessorVir,
};
use mpk_vc::{
    canonical_json_bytes, input_set_hash, parse_strict_json, sha256_raw_file_bytes, CapturedInput,
    InputEntry, InputKind, ReleaseRegistryIdentity, SourceReference, StrictJsonLimits,
    SyntheticPermission, VcTerm,
};
use serde_json::{json, Value};

use crate::proof_api::{IntroProofRequest, ReflProofRequest};
use crate::session::{SessionId, StartSessionRequest};
use crate::successor_api::{
    resolve_route, SuccessorApiError, SuccessorApiErrorCode, SuccessorApiService,
    SuccessorFrontendArtifactStore, SuccessorFrontendArtifacts, SuccessorSessionSourceState,
    SuccessorValidationPhase, SUCCESSOR_AI_API_PROFILE, SUCCESSOR_API_REJECTION_MESSAGE,
    SUCCESSOR_ROUTES,
};
use crate::v1_router::{
    parse_request as parse_v1_request, resolve_route, V1ErrorCode, AI_API_V1_PROFILE, V1_ROUTES,
};
use crate::vc_api::materialize_target;
use crate::vir_api::{V1ApiService, ValidatedFrontendArtifactStore};

const ZERO_SHA256: &str = "0000000000000000000000000000000000000000000000000000000000000000";
const GENERATED_CARGO_TOML: &[u8] = b"[package]\nname = \"vector\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[lib]\nname = \"vector\"\npath = \"src/lib.rs\"\n\n[features]\ndefault = []\n";
const GENERATED_CARGO_LOCK: &[u8] = b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"vector\"\nversion = \"0.1.0\"\n";
const CSHARP_FUNCTION: &str = "Vector.RequiredChecks::Identity(i32)->i32";
const CSHARP_SOURCE: &[u8] =
    include_bytes!("../../../fixtures/csharp/policy/source/src/Required.cs");
const CSHARP_CONTRACT: &[u8] =
    include_bytes!("../../../fixtures/csharp/policy/source/contracts/identity.json");

#[derive(Clone)]
struct ValidatedSource {
    vir: ValidatedSuccessorVir,
    source_map: ValidatedSuccessorSourceMap,
    manifest: ValidatedSuccessorSourceManifest,
}

struct Profiles {
    go: ValidatedSource,
    rust: ValidatedSource,
    csharp: ValidatedSource,
}

struct OwnedCapturedInput {
    kind: InputKind,
    normalized_path: String,
    bytes: Vec<u8>,
}

#[test]
fn v2_routes_and_transports_are_closed_against_both_generations() {
    let active_vectors = load("develop/specs/vectors/ai-api-v1.json");
    assert_eq!(active_vectors["api_profile"], AI_API_V1_PROFILE);
    let vector_routes = active_vectors["route_registry"]
        .as_array()
        .expect("AI API v1 route vectors");
    assert_eq!(SUCCESSOR_ROUTES.len(), V1_ROUTES.len());
    assert_eq!(SUCCESSOR_ROUTES.len(), vector_routes.len());
    for ((successor, active), vector) in SUCCESSOR_ROUTES.iter().zip(V1_ROUTES).zip(vector_routes) {
        assert_eq!(successor.method, active.method);
        assert_eq!(successor.path, active.path);
        assert_eq!(successor.handler, active.handler);
        assert_eq!(vector["method"], active.method);
        assert_eq!(vector["path"], active.path);
        assert_eq!(vector["handler"], active.handler.as_str());
        assert_eq!(
            resolve_route(SUCCESSOR_AI_API_PROFILE, successor.method, successor.path)
                .expect("successor route resolves"),
            successor.handler
        );
        assert_eq!(
            resolve_route(active.method, active.path).expect("active route still resolves"),
            active.handler
        );
    }
    let error = resolve_route(AI_API_V1_PROFILE, "POST", "/vir/import")
        .expect_err("old API profile rejects at the successor router");
    assert_error(
        error,
        SuccessorValidationPhase::Route,
        SuccessorApiErrorCode::ApiProfile,
    );
    let error = resolve_route(SUCCESSOR_AI_API_PROFILE, "POST", "/v2/vir/import")
        .expect_err("route aliases reject");
    assert_error(
        error,
        SuccessorValidationPhase::Route,
        SuccessorApiErrorCode::RouteUnknown,
    );

    let registry = registry();
    let csharp = csharp_source(&registry);
    let store = store(&registry, std::slice::from_ref(&csharp));
    let mut service = SuccessorApiService::new(registry, store).expect("service builds");
    let old_start = canonical_transport(&json!({
        "module_name":"Example.Api.Old",
        "proof_profile":"mvp-strict"
    }));
    let error = service
        .handle_start_session(&old_start)
        .expect_err("v1 session shape rejects in v2");
    assert_error(
        error,
        SuccessorValidationPhase::Shape,
        SuccessorApiErrorCode::Shape,
    );
    assert_eq!(service.mutation_count(), 0);

    let mut successor_start = start_request(&csharp, "Example.Api.Successor");
    let successor_transport = canonical_transport(&successor_start);
    let error = parse_v1_request::<StartSessionRequest>(&successor_transport, 1_048_576)
        .err()
        .expect("v2 session shape rejects in v1");
    assert_eq!(error.code, V1ErrorCode::Shape);
    successor_start["api_profile"] = json!(AI_API_V1_PROFILE);
    let error = service
        .handle_start_session(&canonical_transport(&successor_start))
        .expect_err("old discriminator rejects");
    assert_error(
        error,
        SuccessorValidationPhase::Route,
        SuccessorApiErrorCode::ApiProfile,
    );
    assert_eq!(service.mutation_count(), 0);

    assert_vector_ownership();
}

#[test]
fn all_three_profiles_produce_deterministic_bound_successor_sessions_and_vcs() {
    let registry = registry();
    let profiles = profiles(&registry);
    let store = store(
        &registry,
        &[
            profiles.go.clone(),
            profiles.rust.clone(),
            profiles.csharp.clone(),
        ],
    );

    for (name, source) in [
        ("Go", &profiles.go),
        ("Rust", &profiles.rust),
        ("CSharp", &profiles.csharp),
    ] {
        let first = run_profile(&registry, &store, source, name);
        let second = run_profile(&registry, &store, source, name);
        assert_eq!(first, second, "{name} API bytes are deterministic");
        for response in &first {
            assert!(response.ends_with(b"\n"));
            let value = response_value(response);
            assert_eq!(value["api_profile"], SUCCESSOR_AI_API_PROFILE);
            assert_eq!(value["helper_only"], true);
            assert!(value.get("accepted").is_none());
            assert!(value.get("mpk_verified").is_none());
            assert!(value.get("proof_evidence").is_none());
        }
        let generated = response_value(&first[2]);
        assert_eq!(generated["source_ir_schema"], "mpk.vir.v1");
        assert_eq!(
            generated["source_manifest_schema"],
            "mpk.source_manifest.v1"
        );
        assert_eq!(generated["source_vc_schema"], "mpk.vc.v2");
        assert_eq!(
            generated["semantic_context"]["source_language"],
            source.vir.module().semantic_context().source_language()
        );
        assert_eq!(
            generated["selection"],
            serde_json::to_value(source.manifest.manifest().selection())
                .expect("selection serializes")
        );
    }
}

#[test]
fn crossed_old_stale_and_noncanonical_operations_reject_atomically() {
    let registry = registry();
    let profiles = profiles(&registry);
    let store = store(
        &registry,
        &[
            profiles.go.clone(),
            profiles.rust.clone(),
            profiles.csharp.clone(),
        ],
    );
    let mut service = SuccessorApiService::new(registry, store).expect("service builds");

    let mut unknown = import_request("s404", &profiles.go);
    unknown["semantic_context"] = json!({});
    let error = service
        .handle_vir_import(&canonical_transport(&unknown))
        .expect_err("unknown session precedes context validation");
    assert_eq!(error.code, SuccessorApiErrorCode::UnknownSession);
    assert_eq!(service.mutation_count(), 0);

    let go_start = response_value(
        &service
            .handle_start_session(&canonical_transport(&start_request(
                &profiles.go,
                "Example.Api.Go",
            )))
            .expect("Go session starts"),
    );
    let rust_start = response_value(
        &service
            .handle_start_session(&canonical_transport(&start_request(
                &profiles.rust,
                "Example.Api.Rust",
            )))
            .expect("Rust session starts"),
    );
    assert_eq!(go_start["session_id"], "s1");
    assert_eq!(rust_start["session_id"], "s2");

    let before = fingerprint(&service, &["s1", "s2"]);
    let mut crossed_identity = import_request("s1", &profiles.rust);
    crossed_identity["session_id"] = json!("s1");
    let error = service
        .handle_vir_import(&canonical_transport(&crossed_identity))
        .expect_err("cross-profile session identity rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before);

    let mut crossed_selection = import_request("s1", &profiles.go);
    crossed_selection["selection"] =
        serde_json::to_value(profiles.rust.manifest.manifest().selection())
            .expect("Rust selection serializes");
    let error = service
        .handle_vir_import(&canonical_transport(&crossed_selection))
        .expect_err("cross-profile selection rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before);

    let mut crossed_artifact = import_request("s1", &profiles.go);
    crossed_artifact["vir"] =
        serde_json::from_slice(profiles.rust.vir.canonical_bytes()).expect("Rust VIR JSON");
    crossed_artifact["source_ir_hash"] = json!(profiles.rust.vir.hash().as_str());
    let error = service
        .handle_vir_import(&canonical_transport(&crossed_artifact))
        .expect_err("crossed successor VIR rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before);

    let mut old = import_request("s1", &profiles.go);
    old["source_ir_schema"] = json!("mpk.vir.v0");
    let error = service
        .handle_vir_import(&canonical_transport(&old))
        .expect_err("old VIR discriminator rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::VirSchema);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before);

    let pretty = pretty_transport(&import_request("s2", &profiles.rust));
    let error = service
        .handle_vir_import(&pretty)
        .expect_err("noncanonical request rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::CanonicalTransport);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before);

    service
        .handle_vir_import(&canonical_transport(&import_request("s1", &profiles.go)))
        .expect("Go VIR imports");
    service
        .handle_vir_import(&canonical_transport(&import_request("s2", &profiles.rust)))
        .expect("Rust VIR imports");
    let before_generate = fingerprint(&service, &["s1", "s2"]);
    let mut crossed_manifest = generate_request("s1", &profiles.go);
    crossed_manifest["source_manifest_hash"] = json!(profiles.rust.manifest.hash().as_str());
    crossed_manifest["input_set_hash"] =
        json!(profiles.rust.manifest.manifest().input_set_hash().as_str());
    let error = service
        .handle_vc_generate(&canonical_transport(&crossed_manifest))
        .expect_err("crossed manifest capability rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before_generate);

    let generated = response_value(
        &service
            .handle_vc_generate(&canonical_transport(&generate_request("s1", &profiles.go)))
            .expect("Go VC generates"),
    );
    let context = vc_context(&generated);
    let before_context_failure = fingerprint(&service, &["s1", "s2"]);
    let mut stale = context.clone();
    stale["vc_hash"] = json!(ZERO_SHA256);
    let error = service
        .handle_vc_list(&canonical_transport(&stale))
        .expect_err("stale VC rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before_context_failure);

    let mut old_vc = context.clone();
    old_vc["source_vc_schema"] = json!("mpk.vc.v1");
    let error = service
        .handle_vc_list(&canonical_transport(&old_vc))
        .expect_err("old VC discriminator rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::ContextMismatch);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before_context_failure);

    let mut unknown_target = context;
    unknown_target["target"] = json!({"kind":"member","id":"missing"});
    let error = service
        .handle_vc_start_proof(&canonical_transport(&unknown_target))
        .expect_err("unknown target rejects");
    assert_eq!(error.code, SuccessorApiErrorCode::TargetUnknown);
    assert_eq!(fingerprint(&service, &["s1", "s2"]), before_context_failure);

    let mut active = V1ApiService::new(ValidatedFrontendArtifactStore::empty());
    active
        .start_session(StartSessionRequest::new("Example.Api.Active"))
        .expect("active session starts");
    let before_active = active.mutation_count();
    let error = active
        .handle_vir_import(&canonical_transport(&import_request("s1", &profiles.go)))
        .expect_err("successor request rejects at active boundary");
    assert_eq!(error.code, V1ErrorCode::Shape);
    assert_eq!(active.mutation_count(), before_active);
}

#[test]
fn failed_target_materialization_does_not_leave_partial_helper_state() {
    let mut proof_service = crate::session::ApiService::new();
    let session_id = proof_service
        .start_session(StartSessionRequest::new("Example.Api.AtomicTarget"))
        .expect("session starts")
        .session_id;
    let session = proof_service
        .session_mut(&session_id)
        .expect("session exists");
    let before = (session.terms().len(), session.environment().len());
    let target = VcTerm::Apply {
        function: "Std.Logic.And".to_owned(),
        args: vec![VcTerm::Constant {
            name: "invalid-name".to_owned(),
        }],
    };

    materialize_target(session, &target).expect_err("late-invalid target name rejects");

    assert_eq!((session.terms().len(), session.environment().len()), before);
}

#[test]
fn helper_candidate_success_does_not_change_certificate_acceptance_authority() {
    let registry = registry();
    let csharp = csharp_source(&registry);
    let store = store(&registry, std::slice::from_ref(&csharp));
    let mut service = SuccessorApiService::new(registry, store).expect("service builds");
    service
        .handle_start_session(&canonical_transport(&start_request(
            &csharp,
            "Example.Api.CSharp",
        )))
        .expect("C# session starts");
    service
        .handle_vir_import(&canonical_transport(&import_request("s1", &csharp)))
        .expect("C# VIR imports");
    let generated = response_value(
        &service
            .handle_vc_generate(&canonical_transport(&generate_request("s1", &csharp)))
            .expect("C# VC generates"),
    );
    let list = response_value(
        &service
            .handle_vc_list(&canonical_transport(&vc_context(&generated)))
            .expect("C# VC lists"),
    );
    let member_id = list["members"]
        .as_array()
        .expect("member list")
        .iter()
        .find(|member| member["kind"] == "postcondition")
        .expect("postcondition member")["member_id"]
        .as_str()
        .expect("member ID")
        .to_owned();

    let mut start = vc_context(&generated);
    start["target"] = json!({"kind":"member","id":member_id});
    let started = response_value(
        &service
            .handle_vc_start_proof(&canonical_transport(&start))
            .expect("proof target starts"),
    );
    assert_eq!(started["target_id"], "t1");
    build_identity_recipe(&mut service, "s1", "t1");

    let mut attach = vc_context(&generated);
    attach["target_id"] = json!("t1");
    attach["candidate_id"] = json!("candidate-csharp-identity");
    attach["proof_root"] = json!(2);
    service
        .handle_vc_attach_candidate(&canonical_transport(&attach))
        .expect("candidate attaches");

    let valid_certificate =
        decode_hex(include_str!("../../../fixtures/cert-basic/one-theorem.hex"));
    let invalid_certificate = b"AI helper output is not a certificate".to_vec();
    let valid_before = verify_certificate_bytes(&valid_certificate);
    let invalid_before = verify_certificate_bytes(&invalid_certificate);

    let mut check = vc_context(&generated);
    check["target_id"] = json!("t1");
    check["mode"] = json!("fail_fast_per_candidate");
    check["candidates"] = json!([{
        "candidate_id":"candidate-csharp-identity",
        "proof_root":2
    }]);
    let response = service
        .handle_vc_check_candidate(&canonical_transport(&check))
        .expect("bound helper candidate checks");
    let value = response_value(&response);
    assert_eq!(value["results"][0]["helper_status"], "valid");
    assert_eq!(value["helper_only"], true);
    assert!(value.get("accepted").is_none());
    assert!(value.get("proof_evidence").is_none());

    assert_eq!(verify_certificate_bytes(&valid_certificate), valid_before);
    assert_eq!(
        verify_certificate_bytes(&invalid_certificate),
        invalid_before
    );
    assert!(valid_before.is_ok());
    assert!(invalid_before.is_err());
}

fn run_profile(
    registry: &ValidatedSemanticProfileRegistry,
    store: &SuccessorFrontendArtifactStore,
    source: &ValidatedSource,
    name: &str,
) -> Vec<Vec<u8>> {
    let mut service =
        SuccessorApiService::new(registry.clone(), store.clone()).expect("service builds");
    let start = service
        .handle_start_session(&canonical_transport(&start_request(
            source,
            format!("Example.Api.{name}"),
        )))
        .expect("session starts");
    let import = service
        .handle_vir_import(&canonical_transport(&import_request("s1", source)))
        .expect("VIR imports");
    let generate = service
        .handle_vc_generate(&canonical_transport(&generate_request("s1", source)))
        .expect("VC generates");
    let generated = response_value(&generate);
    let list = service
        .handle_vc_list(&canonical_transport(&vc_context(&generated)))
        .expect("VC lists");
    assert_eq!(service.mutation_count(), 3);
    assert!(matches!(
        service.source_state(&SessionId("s1".to_owned())),
        Some(SuccessorSessionSourceState::VcGenerated(_))
    ));
    vec![start, import, generate, list]
}

fn build_identity_recipe(service: &mut SuccessorApiService, session: &str, target_id: &str) {
    let session_id = SessionId(session.to_owned());
    let target = service
        .target_term_id(&session_id, target_id)
        .expect("target term exists");
    let (outer_domain, inner, inner_domain, equality, reflected) = {
        let session = service
            .proof_service()
            .session(&session_id)
            .expect("session exists");
        let outer = session.core_term_id(target).expect("target core term");
        let TermNode::Pi {
            ty: outer_domain,
            body: inner,
        } = session.terms().node(outer).clone()
        else {
            panic!("member target has outer binder")
        };
        let TermNode::Pi {
            ty: inner_domain,
            body: equality,
        } = session.terms().node(inner).clone()
        else {
            panic!("member target has implication binder")
        };
        let TermNode::App { arguments, .. } = session.terms().node(equality).clone() else {
            panic!("member target has equality")
        };
        (outer_domain, inner, inner_domain, equality, arguments[0])
    };
    let (outer_domain, inner, inner_domain, equality, reflected) = {
        let session = service
            .proof_service_mut()
            .session_mut(&session_id)
            .expect("session exists");
        (
            session
                .register_term_id(outer_domain)
                .expect("outer domain"),
            session.register_term_id(inner).expect("inner target"),
            session
                .register_term_id(inner_domain)
                .expect("inner domain"),
            session.register_term_id(equality).expect("equality"),
            session.register_term_id(reflected).expect("reflected term"),
        )
    };
    let refl = service
        .proof_service_mut()
        .proof_refl(ReflProofRequest {
            session_id: session_id.clone(),
            term: reflected,
            expected_type: equality,
        })
        .expect("refl builds");
    assert_eq!(refl.proof_id.0, 0);
    let inner_intro = service
        .proof_service_mut()
        .proof_intro(IntroProofRequest {
            session_id: session_id.clone(),
            domain_type: inner_domain,
            body_proof: refl.proof_id,
            expected_type: inner,
        })
        .expect("inner intro builds");
    assert_eq!(inner_intro.proof_id.0, 1);
    let outer_intro = service
        .proof_service_mut()
        .proof_intro(IntroProofRequest {
            session_id,
            domain_type: outer_domain,
            body_proof: inner_intro.proof_id,
            expected_type: target,
        })
        .expect("outer intro builds");
    assert_eq!(outer_intro.proof_id.0, 2);
}

fn start_request(source: &ValidatedSource, module_name: impl Into<String>) -> Value {
    json!({
        "api_profile":SUCCESSOR_AI_API_PROFILE,
        "module_name":module_name.into(),
        "proof_profile":"mvp-strict",
        "semantic_context":source.vir.module().semantic_context(),
        "selection":source.manifest.manifest().selection()
    })
}

fn import_request(session_id: &str, source: &ValidatedSource) -> Value {
    json!({
        "api_profile":SUCCESSOR_AI_API_PROFILE,
        "session_id":session_id,
        "semantic_context":source.vir.module().semantic_context(),
        "selection":source.manifest.manifest().selection(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":source.vir.hash().as_str(),
        "vir":serde_json::from_slice::<Value>(source.vir.canonical_bytes()).expect("VIR JSON")
    })
}

fn generate_request(session_id: &str, source: &ValidatedSource) -> Value {
    json!({
        "api_profile":SUCCESSOR_AI_API_PROFILE,
        "session_id":session_id,
        "semantic_context":source.vir.module().semantic_context(),
        "selection":source.manifest.manifest().selection(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":source.vir.hash().as_str(),
        "source_manifest_schema":"mpk.source_manifest.v1",
        "source_manifest_hash":source.manifest.hash().as_str(),
        "input_set_hash":source.manifest.manifest().input_set_hash().as_str()
    })
}

fn vc_context(generated: &Value) -> Value {
    json!({
        "api_profile":generated["api_profile"],
        "session_id":generated["session_id"],
        "semantic_context":generated["semantic_context"],
        "selection":generated["selection"],
        "source_ir_schema":generated["source_ir_schema"],
        "source_ir_hash":generated["source_ir_hash"],
        "source_manifest_schema":generated["source_manifest_schema"],
        "source_manifest_hash":generated["source_manifest_hash"],
        "input_set_hash":generated["input_set_hash"],
        "source_vc_schema":generated["source_vc_schema"],
        "vc_hash":generated["vc_hash"]
    })
}

fn fingerprint(service: &SuccessorApiService, sessions: &[&str]) -> String {
    let states = sessions
        .iter()
        .map(|session| {
            let id = SessionId((*session).to_owned());
            let source = service
                .source_state(&id)
                .map(SuccessorSessionSourceState::label)
                .unwrap_or("missing");
            let proof = service.proof_service().session(&id);
            format!(
                "{session}:{source}:{}:{}:{}:{}",
                proof.map_or(0, |session| session.terms().len()),
                proof.map_or(0, |session| session.environment().len()),
                proof.map_or(0, |session| session.proof_node_count()),
                proof.map_or(0, |session| session.theory_certificate_count())
            )
        })
        .collect::<Vec<_>>()
        .join("|");
    format!("{}|{states}", service.mutation_count())
}

fn assert_error(
    error: SuccessorApiError,
    phase: SuccessorValidationPhase,
    code: SuccessorApiErrorCode,
) {
    assert_eq!(error.phase(), phase);
    assert_eq!(error.code, code);
    let value = serde_json::to_value(error).expect("error serializes");
    assert_eq!(value["message"], SUCCESSOR_API_REJECTION_MESSAGE);
    assert!(value.get("phase").is_none());
    assert!(value
        .as_object()
        .expect("error object")
        .values()
        .all(|value| !value.is_null()));
}

fn assert_vector_ownership() {
    let manifest = load("develop/specs/vectors/manifest.json");
    for path in [
        "develop/specs/vectors/ai-api-v1.json",
        "develop/specs/vectors/csharp-profile-v0.json",
        "develop/specs/vectors/semantic-profile-registry-v1.json",
        "develop/specs/vectors/semantic-profile-registry-v2.json",
    ] {
        let record = manifest["vectors"]
            .as_array()
            .expect("vector manifest")
            .iter()
            .find(|record| record["path"] == path)
            .unwrap_or_else(|| panic!("missing vector record {path}"));
        assert!(record["implementation_test_owners"]
            .as_array()
            .expect("owners")
            .iter()
            .any(|owner| owner == "crates/mpk-api/src/v2_tests.rs"));
    }
}

fn profiles(registry: &ValidatedSemanticProfileRegistry) -> Profiles {
    Profiles {
        go: staged_source(
            registry,
            "fixtures/vir-go/frontend/basic-arith",
            "fixtures/go-basic",
        ),
        rust: staged_source(
            registry,
            "fixtures/rust-basic/positive/checked-addition/artifacts",
            "rust-tools/rust2vir/testdata/positive/checked-addition/source",
        ),
        csharp: csharp_source(registry),
    }
}

fn store(
    registry: &ValidatedSemanticProfileRegistry,
    sources: &[ValidatedSource],
) -> SuccessorFrontendArtifactStore {
    SuccessorFrontendArtifactStore::from_frontend_successes(
        registry,
        sources.iter().map(|source| SuccessorFrontendArtifacts {
            vir: source.vir.clone(),
            source_map: source.source_map.clone(),
            source_manifest: source.manifest.clone(),
            vc_profile_contract: profile_contract(
                source.vir.module().semantic_context().source_language(),
            ),
        }),
    )
    .expect("successor store builds")
}

fn registry() -> ValidatedSemanticProfileRegistry {
    validate_semantic_profile_registry(
        &read("release/bundles/semantic-profile-registry.json"),
        RegistryRevision::Revision2,
    )
    .expect("revision-2 registry")
}

fn profile_contract(profile: &str) -> Value {
    match profile {
        "go" => json!({
            "profile_entry_sha256":"b10ec338d1f2b3fefc015e4d46c27def43e92ff3d87341624b48c93db951ca96",
            "contract_id":"mpk.profile.vc.go_fixed.v0",
            "value":{
                "contract_profile_id":"mpk.go.contract.v0",
                "required_check_profile_id":"mpk.go.fixed.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        "rust" => json!({
            "profile_entry_sha256":"1cee9716bb21d07e07b8bc1de59ecaf83437549a4d595039486312260816f057",
            "contract_id":"mpk.profile.vc.rust_checked.v0",
            "value":{
                "contract_profile_id":"mpk.rust.contract.v0",
                "required_check_profile_id":"mpk.rust.checked.v0",
                "verification_limit_profile_id":"mpk.verify.limits.v0"
            }
        }),
        "csharp" => load("develop/specs/vectors/csharp-profile-v0.json")["profile_contracts"]
            .as_array()
            .expect("C# profile contracts")
            .iter()
            .find(|contract| contract["field"] == "vc")
            .expect("C# VC contract")["envelope"]
            .clone(),
        other => panic!("unknown profile {other}"),
    }
}

fn staged_source(
    registry: &ValidatedSemanticProfileRegistry,
    artifact_root: &str,
    source_root: &str,
) -> ValidatedSource {
    let vir_bytes = read(format!("{artifact_root}/vir.json"));
    let map_bytes = read(format!("{artifact_root}/source-map.json"));
    let manifest_bytes = read(format!("{artifact_root}/source-manifest.frontend.json"));
    let map_value: Value = serde_json::from_slice(&map_bytes).expect("source-map JSON");
    let manifest_value: Value = serde_json::from_slice(&manifest_bytes).expect("manifest JSON");
    let storage = captured_storage(source_root, &manifest_value);
    let captured = captured_refs(&storage);
    let vir = import_successor_vir_json(&vir_bytes, registry).expect("successor VIR");
    let synthetic_permissions = map_value["entries"]
        .as_array()
        .expect("source-map entries")
        .iter()
        .filter(|entry| entry["origin"]["kind"] == "synthetic")
        .map(|entry| SyntheticPermission {
            reference: serde_json::from_value::<SourceReference>(entry["reference"].clone())
                .expect("synthetic reference"),
            reason: entry["origin"]["reason"]
                .as_str()
                .expect("synthetic reason")
                .to_owned(),
        })
        .collect::<Vec<_>>();
    let source_map = import_successor_source_map_json(
        &map_bytes,
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &synthetic_permissions,
        },
    )
    .expect("successor source map");
    let release_registry = serde_json::from_value::<ReleaseRegistryIdentity>(
        manifest_value["release_registry"].clone(),
    )
    .expect("release registry identity");
    let manifest = import_successor_source_manifest_json(
        &manifest_bytes,
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("successor source manifest");
    ValidatedSource {
        vir,
        source_map,
        manifest,
    }
}

fn csharp_source(registry: &ValidatedSemanticProfileRegistry) -> ValidatedSource {
    let context =
        load("release/bundles/candidates/csharp.json")["tuples"][0]["semantic_context"].clone();
    let i32_type = json!({"kind":"bv","width":32,"signed":true});
    let mut contract = json!({
        "semantic_context":context.clone(),
        "unit_id":"payment-policy",
        "function_id":CSHARP_FUNCTION,
        "requires":[],
        "ensures":[{"lhs":{"result":0},"op":"eq","rhs":{"var":"arg0"}}],
        "modifies":[],
        "panic":"forbidden",
        "termination":"total",
        "loops":[],
        "contract_hash":ZERO_SHA256
    });
    contract["contract_hash"] = json!(successor_contract_hash_value(&contract)
        .expect("C# contract hash")
        .as_str());
    let mut vir_value = json!({
        "schema":"mpk.vir.v1",
        "semantic_context":context,
        "units":[{
            "id":"payment-policy",
            "name":"payment-policy",
            "type_decls":[],
            "const_decls":[],
            "functions":[{
                "id":CSHARP_FUNCTION,
                "unit_id":"payment-policy",
                "name":"Identity",
                "params":[{"id":"arg0","type":i32_type.clone()}],
                "results":[{"id":"result0","type":i32_type}],
                "locals":[],
                "blocks":[{
                    "label":"bb0",
                    "parameters":[],
                    "instructions":[],
                    "terminator":{"kind":"Return","values":[{"var":"arg0"}]}
                }],
                "contracts":contract,
                "features_used":[]
            }]
        }],
        "vir_hash":ZERO_SHA256
    });
    vir_value["vir_hash"] = json!(successor_vir_hash_value(&vir_value)
        .expect("C# VIR hash")
        .as_str());
    let vir = import_successor_vir_json(&canonical(&vir_value), registry).expect("C# VIR");

    let storage = vec![
        OwnedCapturedInput {
            kind: InputKind::Contract,
            normalized_path: "contracts/identity.json".to_owned(),
            bytes: CSHARP_CONTRACT.to_vec(),
        },
        OwnedCapturedInput {
            kind: InputKind::Source,
            normalized_path: "src/Required.cs".to_owned(),
            bytes: CSHARP_SOURCE.to_vec(),
        },
    ];
    let captured = captured_refs(&storage);
    let origin = || {
        json!({
            "kind":"source",
            "input_kind":"source",
            "normalized_path":"src/Required.cs",
            "start":0,
            "end":CSHARP_SOURCE.len()
        })
    };
    let mut source_map_value = json!({
        "schema":"mpk.source_map.v1",
        "semantic_context":vir.module().semantic_context(),
        "source_ir_schema":"mpk.vir.v1",
        "source_ir_hash":vir.hash().as_str(),
        "entries":[{
            "reference":{"kind":"function","unit_id":"payment-policy","function_id":CSHARP_FUNCTION},
            "origin":origin()
        },{
            "reference":{
                "kind":"terminator",
                "unit_id":"payment-policy",
                "function_id":CSHARP_FUNCTION,
                "block":"bb0"
            },
            "origin":origin()
        }],
        "source_map_hash":ZERO_SHA256
    });
    source_map_value["source_map_hash"] = json!(successor_source_map_hash_value(&source_map_value)
        .expect("C# map hash")
        .as_str());
    let source_map = import_successor_source_map_json(
        &canonical(&source_map_value),
        SuccessorSourceMapValidationContext {
            registry,
            vir: &vir,
            captured_inputs: &captured,
            synthetic_permissions: &[],
        },
    )
    .expect("C# source map");

    let inputs = storage
        .iter()
        .map(|input| InputEntry {
            kind: input.kind,
            normalized_path: input.normalized_path.clone(),
            size_bytes: input.bytes.len() as i64,
            sha256: sha256_raw_file_bytes(&input.bytes).to_hex(),
        })
        .collect::<Vec<_>>();
    let release = load("release/bundles/bundle-registry.json");
    let release_registry = ReleaseRegistryIdentity {
        schema: release["schema"].as_str().expect("schema").to_owned(),
        id: release["id"].as_str().expect("ID").to_owned(),
        registry_sha256: release["registry_sha256"]
            .as_str()
            .expect("hash")
            .to_owned(),
    };
    let mut manifest_value = json!({
        "schema":"mpk.source_manifest.v1",
        "semantic_context":vir.module().semantic_context(),
        "selection":{
            "schema":"mpk.selection.csharp_methods.v0",
            "value":{
                "compilation":"payment-policy",
                "contracts":["contracts/identity.json"],
                "methods":[CSHARP_FUNCTION],
                "sources":["src/Required.cs"]
            }
        },
        "limit_profile":"mpk.vir.limits.v0",
        "release_registry":release_registry,
        "toolchain":{
            "bundle_id":"toolchain.csharp.roslyn-5_6_0.dotnet-10_0_11.candidate.v1",
            "distribution_sha256":"6cc7711334ffcd9216cfb241e1508491abb62a13b01ebc9b2d883a1ace9627bc",
            "components":[]
        },
        "frontend":{
            "bundle_id":"frontend.csharp.csharp2vir.candidate.v1",
            "name":"csharp2vir",
            "version":"0.1.0",
            "binary_sha256":"0783dc269c152ad1b13e77f42f9eff6f6891002c65890bc1445f2fe1a1a0410d",
            "subordinate_binaries":[]
        },
        "units":[{"identity":"payment-policy","name":"payment-policy","kind":"compilation"}],
        "target":{"id":"linux-x64","pointer_width":64},
        "inputs":inputs,
        "input_set_hash":input_set_hash(&inputs).expect("input hash").as_str(),
        "vir_hash":vir.hash().as_str(),
        "source_map_hash":source_map.hash().as_str(),
        "source_manifest_hash":ZERO_SHA256
    });
    manifest_value["source_manifest_hash"] =
        json!(successor_source_manifest_hash_value(&manifest_value)
            .expect("C# manifest hash")
            .as_str());
    let manifest = import_successor_source_manifest_json(
        &canonical(&manifest_value),
        SuccessorSourceManifestStage::Frontend,
        SuccessorSourceManifestValidationContext {
            registry,
            vir: &vir,
            source_map: &source_map,
            captured_inputs: &captured,
            expected_release_registry: &release_registry,
        },
    )
    .expect("C# manifest");
    ValidatedSource {
        vir,
        source_map,
        manifest,
    }
}

fn captured_storage(source_root: &str, manifest: &Value) -> Vec<OwnedCapturedInput> {
    manifest["inputs"]
        .as_array()
        .expect("manifest inputs")
        .iter()
        .map(|entry| {
            let kind = match entry["kind"].as_str().expect("input kind") {
                "source" => InputKind::Source,
                "contract" => InputKind::Contract,
                "build_manifest" => InputKind::BuildManifest,
                "lockfile" => InputKind::Lockfile,
                other => panic!("unknown input kind {other}"),
            };
            let normalized_path = entry["normalized_path"]
                .as_str()
                .expect("input path")
                .to_owned();
            let path = repository_root().join(source_root).join(&normalized_path);
            let bytes = match fs::read(&path) {
                Ok(bytes) => bytes,
                Err(error) if error.kind() == std::io::ErrorKind::NotFound => match kind {
                    InputKind::BuildManifest if normalized_path == "Cargo.toml" => {
                        GENERATED_CARGO_TOML.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "Cargo.lock" => {
                        GENERATED_CARGO_LOCK.to_vec()
                    }
                    InputKind::Lockfile if normalized_path == "go.sum" => Vec::new(),
                    _ => panic!("read {}: {error}", path.display()),
                },
                Err(error) => panic!("read {}: {error}", path.display()),
            };
            assert_eq!(entry["size_bytes"], bytes.len() as u64);
            assert_eq!(entry["sha256"], sha256_raw_file_bytes(&bytes).to_hex());
            OwnedCapturedInput {
                kind,
                normalized_path,
                bytes,
            }
        })
        .collect()
}

fn captured_refs(storage: &[OwnedCapturedInput]) -> Vec<CapturedInput<'_>> {
    storage
        .iter()
        .map(|input| CapturedInput {
            kind: input.kind,
            normalized_path: &input.normalized_path,
            bytes: &input.bytes,
        })
        .collect()
}

fn repository_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .expect("repository root")
}

fn read(relative: impl AsRef<Path>) -> Vec<u8> {
    fs::read(repository_root().join(relative.as_ref()))
        .unwrap_or_else(|error| panic!("read {}: {error}", relative.as_ref().display()))
}

fn load(relative: impl AsRef<Path>) -> Value {
    serde_json::from_slice(&read(relative)).expect("checked-in JSON")
}

fn canonical(value: &Value) -> Vec<u8> {
    let serialized = serde_json::to_vec(value).expect("JSON serializes");
    let strict = parse_strict_json(
        &serialized,
        StrictJsonLimits::new(268_435_456, 268_435_456, 768, 1_048_576),
    )
    .expect("strict JSON");
    canonical_json_bytes(&strict).expect("canonical JSON")
}

fn canonical_transport(value: &Value) -> Vec<u8> {
    let mut bytes = canonical(value);
    bytes.push(b'\n');
    bytes
}

fn pretty_transport(value: &Value) -> Vec<u8> {
    let mut bytes = serde_json::to_vec_pretty(value).expect("pretty JSON");
    bytes.push(b'\n');
    bytes
}

fn response_value(bytes: &[u8]) -> Value {
    serde_json::from_slice(bytes.strip_suffix(b"\n").expect("response LF")).expect("response JSON")
}

fn decode_hex(contents: &str) -> Vec<u8> {
    let hex = contents
        .chars()
        .filter(|character| !character.is_whitespace())
        .collect::<String>();
    assert_eq!(hex.len() % 2, 0);
    hex.as_bytes()
        .chunks_exact(2)
        .map(|chunk| {
            u8::from_str_radix(std::str::from_utf8(chunk).expect("hex UTF-8"), 16)
                .expect("hex byte")
        })
        .collect()
}
