import hashlib,json,pathlib,shutil
b=pathlib.Path(__file__).parent;r=pathlib.Path('/private/tmp/mpk-w09-refreeze-consumer-continuation');out=b/'pattern-consumer-promotion-plan';out.mkdir(exist_ok=False);h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();lineage=json.loads((b/'completed-control-pattern-consumers-with-producer-names.json').read_bytes());assert not lineage['failures'];graphs=json.loads((b/'control-pattern-consumer-name-graphs/status.json').read_bytes());assert graphs['status'].startswith('passed_all_21') and len(graphs['stages'])==21;map11=json.loads((b/'context-name-rebindings-11.json').read_bytes());plans=json.loads((b/'control-pattern-consumer-changed-certificates.json').read_bytes());reused=[]
for row in plans['cases']:
 parent=row['same_complete_graph_pair_as_parent']
 if parent is None:continue
 s=json.loads((b/parent['owner']/'status.json').read_bytes());assert s['status'].startswith('passed_all_');g=next(x for x in s['stages'] if x['label']==parent['label']);assert (row['original_raw_sha256'],row['generated_raw_sha256'])==(g['original_raw_sha256'],g['generated_raw_sha256']);parentmap={'control-execution-name-graphs':'context-name-rebindings-7.json','control-pattern-scope-name-graphs':'context-name-rebindings-9.json','control-pattern-capture-name-graphs':'context-name-rebindings-10.json'}[parent['owner']];m=json.loads((b/parentmap).read_bytes());extra={k:v for k,v in map11.items() if m.get(k)!=v};raw=bytes.fromhex(pathlib.Path(row['original_path']).read_text());assert not any(k.encode() in raw for k in extra);dual=row['same_exact_fresh_certificate_as_parent'];s=json.loads((b/dual['owner']/'status.json').read_bytes());assert s['status'].startswith('passed_all_');stages=[x for x in s['stages'] if x['case']==dual['label']];assert {x['backend'] for x in stages}=={'rust','go'};assert all(x['exit_code']==0 and x['verdict']=='accepted' and x['input_sha256']==hashlib.sha256(bytes.fromhex(pathlib.Path(row['generated_path']).read_text())).hexdigest() for x in stages);reused.append({'case':row['label'],'complete_original_fresh_pair':True,'additional_name_mapping_absent_from_complete_predecessor':True,'parent_graph':parent,'parent_acceptance':dual})
assert len(reused)==33;changes=[]
for row in lineage['files']:
 path='develop/migrations/csharp-03/ordinary-foundation/'+row['family']+'/'+row['generated_path'];old=r/path;fresh=b/'control-pattern-consumer-regeneration/generated'/row['family'].removeprefix('control-predicates/')/row['generated_path'];assert h(old)==row['original_raw_sha256'] and h(fresh)==row['generated_raw_sha256'];dest=out/'files'/path;dest.parent.mkdir(parents=True,exist_ok=True);shutil.copy2(fresh,dest);changes.append({'path':path,'before_raw_sha256':h(old),'raw_sha256':h(fresh),'kind':'certificate' if fresh.suffix=='.hex' else 'metadata'})
receipt={'status':'reviewable_complete_generation_lineage_and_graphs_pending_21_dual_acceptances_and_four_original_owners','selection_reason':'Reconcile only the remaining current primitive/route/packed pattern programs and exact route control metadata. Actual 54-program generation and strict imports, complete metadata lineage, all 21 distinct changed graphs and 33 complete old/fresh pair reuses pass. Fresh Rust/Go acceptance for the 21 distinct certificates and the four original semantic owner tests are still required; this plan is not promoted or complete. The historical 61-condition bytes remain archived and all 18 complete typed declaration closures survive after SHA-pinned, independently derived name mappings.','programs':54,'complete_graphs':21,'reused_complete_pairs':reused,'required_fresh_checker_stages':42,'required_original_owner_tests':4,'changes':changes,'application_proof_ids_pending':987,'full_t01_gate':'deferred_to_final_W10','full_t06_gate':'deferred_to_W12'};(out/'plan.json').write_text(json.dumps(receipt,sort_keys=True,indent=2)+'\n');print('reviewable paths',len(changes),'exact graph/checker pair reuses',len(reused))
