import hashlib,json,pathlib,subprocess,time
b=pathlib.Path(__file__).parent;out=b/'historical-pattern-condition-closure-review';out.mkdir(exist_ok=False);old=pathlib.Path('/private/tmp/mpk-w09-refreeze-metadata-integration/develop/migrations/csharp-03/ordinary-foundation/control-predicates/with-pattern-observations');current=b/'control-pattern-consumer-regeneration/generated/with-pattern-primitives';binary=b/'compare-historical-pattern-condition-closures';mapping=b/'context-name-rebindings-11.json';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();paths=[binary,mapping,b/'compare-historical-pattern-condition-closures.rs',b/'historical-pattern-condition-closure-compile-command.json']+list(old.glob('*.hex'))+list(current.glob('*.hex'));manifest={str(p):h(p) for p in paths};(out/'manifest.json').write_text(json.dumps(manifest,sort_keys=True,indent=2)+'\n');state={'status':'running','selection_reason':'Before adjusting the current original-source test historical comparison, require every declaration kind, complete type/body/proof tree, generated constructor/recursor flag, variable, binder, argument and level order from all eighteen historical 61-condition certificates to survive in the actual current 81-condition producer output. Apply only independently replayed context names to the old name table; do not normalize terms or omit definitions. Historical bytes remain untouched.','application_proof_ids_pending':987,'whole_gate':'deferred_to_final_T01_W10_and_T06_W12'}
def save():(out/'status.json').write_text(json.dumps(state,sort_keys=True,indent=2)+'\n')
start=time.monotonic();save()
try:
 with (out/'report.json').open('wb') as stdout,(out/'stderr.txt').open('wb') as stderr:
  p=subprocess.Popen([str(binary),str(mapping),str(old),str(current)],stdout=stdout,stderr=stderr);state['process_pid']=p.pid;save();code=p.wait()
 state['exit_code']=code;assert code==0;report=json.loads((out/'report.json').read_bytes());assert report['status'].startswith('passed_all_18_') and len(report['sources'])==18;assert all(h(pathlib.Path(p))==sha for p,sha in manifest.items());state['status']='passed_all_18_full_historical_definition_closures_after_actual_name_rebinding';state['source_unchanged']=True
except BaseException as e:state['status']='failed';state['error']=repr(e);raise
finally:state['elapsed_seconds']=time.monotonic()-start;save()
print(json.dumps(state))
